version: 0.2

phases:
  install:
    commands:
      # Upgrade apt
      - apt-get upgrade

      # Update libs
      - apt-get update

      # Install node
      - curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
      - sudo apt-get install -y nodejs

      # Install chromium
      - apt-get -y install chromium-browser
  pre_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
  build:
    commands:
      - chmod +x aws_scripts/build.sh
      - echo IM Build started on `date`
      - aws_scripts/build.sh mvn -B deploy
      - mvn sonar:sonar
  post_build:
    commands:
      - IP=$(curl http://checkip.amazonaws.com)/32
      - echo $IP of CodeBuild Instance
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - aws_scripts/**/*
    - api/target/api/**/*
    - frontend/dist/**/*
