DROP DATABASE IF EXISTS im4;
CREATE DATABASE im4;
USE im4;

DROP TABLE IF EXISTS document;
CREATE TABLE document (
    dbid INT AUTO_INCREMENT         COMMENT 'Unique DBID generated by hashing the iri',
    data JSON NOT NULL              COMMENT 'Original JSON document content',
    iri VARCHAR(255)                GENERATED ALWAYS AS (`data` ->> '$."@document"') VIRTUAL NOT NULL,

    PRIMARY KEY document_dbid_pk (dbid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS concept;
CREATE TABLE concept (
    dbid INT AUTO_INCREMENT,
    data JSON NOT NULL,
    status TINYINT NOT NULL DEFAULT 0 COMMENT 'Status - 0 = Draft, 1 = Incomplete, 2 = Active, 3 = Deprecated',
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    id VARCHAR(50) COLLATE utf8_bin   GENERATED ALWAYS AS (`data` ->> '$."@id"') STORED NOT NULL,
    document VARCHAR(250)             GENERATED ALWAYS AS (`data` ->> '$."@document"') VIRTUAL NOT NULL,
    name VARCHAR(60)                  GENERATED ALWAYS AS (`data` ->> '$."@name"') STORED NOT NULL,
    description VARCHAR(400)          GENERATED ALWAYS AS (`data` ->> '$."@description"') VIRTUAL,
    scheme VARCHAR(50)                GENERATED ALWAYS AS (`data` ->> '$."@code_scheme"') VIRTUAL,
    code VARCHAR(20) COLLATE utf8_bin GENERATED ALWAYS AS (`data` ->> '$."@code"') VIRTUAL,

    PRIMARY KEY concept_dbid_pk (dbid),
    UNIQUE KEY concept_id_uq (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


PREPARE stmt FROM 'ALTER TABLE concept AUTO_INCREMENT = 1';
EXECUTE stmt;

DEALLOCATE PREPARE stmt;
