DROP DATABASE IF EXISTS im4;
CREATE DATABASE im4;
USE im4;

DELIMITER //

DROP FUNCTION IF EXISTS hashId//

CREATE FUNCTION hashId(token VARCHAR(200)) RETURNS BINARY(16)
    DETERMINISTIC
BEGIN
    RETURN unhex(md5(lower(token)));
END //

DELIMITER ;

DROP TABLE IF EXISTS document;
CREATE TABLE document (
    dbid  BINARY(16)   NOT NULL         COMMENT 'Unique DBID generated by hashing the iri',
    data JSON NOT NULL                  COMMENT 'Original JSON document content',
    iri VARCHAR(255)                    GENERATED ALWAYS AS (`data` ->> '$."@document"') VIRTUAL NOT NULL,

    PRIMARY KEY document_id_pk (dbid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS concept;
CREATE TABLE concept (
    dbid BINARY(16) NOT NULL,
    data JSON NOT NULL,
    id VARCHAR(50)              GENERATED ALWAYS AS (`data` ->> '$."@id"') VIRTUAL NOT NULL,
    document VARCHAR(250)       GENERATED ALWAYS AS (`data` ->> '$."@document"') VIRTUAL NOT NULL,
    name VARCHAR(50)            GENERATED ALWAYS AS (`data` ->> '$."@name"') STORED NOT NULL,
    description VARCHAR(200)    GENERATED ALWAYS AS (`data` ->> '$."@description"') VIRTUAL,
    scheme VARCHAR(50)          GENERATED ALWAYS AS (`data` ->> '$."@scheme"') VIRTUAL,
    code VARCHAR(200)           GENERATED ALWAYS AS (`data` ->> '$."@code"') VIRTUAL,

    PRIMARY KEY concept_id_pk (dbid)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
