-- Ensure core code scheme exists
INSERT IGNORE INTO concept (document, id, name, description)
VALUES (1, 'CM_DiscoveryCode', 'Discovery code', 'Discovery (core) coding scheme ');

-- Get scheme id
SELECT @scm := dbid FROM concept WHERE id = 'CM_DiscoveryCode';

-- LANGUAGE PROPERTY --  https://fhir.nhs.uk/ValueSet/CareConnect-HumanLanguage-1
INSERT IGNORE INTO concept (document, id, scheme, code, name, description)
VALUES
(1, 'DM_language', @scm, 'DM_language', 'Language', 'Language');

-- FHIR VALUE SET --  https://fhir.nhs.uk/ValueSet/CareConnect-HumanLanguage-1
-- Ensure FHIR_LANG scheme exists --
INSERT IGNORE INTO concept (document, id, scheme, code, name, description)
VALUES (1, 'FHIR_LANG', @scm, 'FHIR_LANG', 'Care Connect Human Language', 'Care Connect Human Language');

-- Get scheme id
SELECT @scm := dbid FROM concept WHERE id = 'FHIR_LANG';

-- Code scheme prefix entries
INSERT IGNORE INTO concept_property_data
(`dbid`, `group`, `property`, `value`)
SELECT c.dbid, 0 AS `group`, p.dbid AS `property`, 'FHIR_LANG_' AS `value`
FROM concept c
         JOIN concept p ON p.id = 'code_prefix'
WHERE c.id = 'FHIR_LANG';

-- LANGUAGE CONCEPTS --  https://fhir.nhs.uk/ValueSet/CareConnect-HumanLanguage-1
INSERT IGNORE INTO concept (document, id, scheme, code, name, description)
VALUES
(1, 'FHIR_LANG_q1', @scm, 'q1', 'Braille', 'Braille'),
(1, 'FHIR_LANG_q2', @scm, 'q2', 'American Sign Language', 'American Sign Language'),
(1, 'FHIR_LANG_q3', @scm, 'q3', 'Australian Sign Language', 'Australian Sign Language'),
(1, 'FHIR_LANG_q4', @scm, 'q4', 'British Sign Language', 'British Sign Language'),
(1, 'FHIR_LANG_q5', @scm, 'q5', 'Makaton', 'Makaton'),
(1, 'FHIR_LANG_aa', @scm, 'aa', 'Afar', 'Afar'),
(1, 'FHIR_LANG_ab', @scm, 'ab', 'Abkhazian', 'Abkhazian'),
(1, 'FHIR_LANG_af', @scm, 'af', 'Afrikaans', 'Afrikaans'),
(1, 'FHIR_LANG_ak', @scm, 'ak', 'Akan', 'Akan'),
(1, 'FHIR_LANG_sq', @scm, 'sq', 'Albanian', 'Albanian'),
(1, 'FHIR_LANG_am', @scm, 'am', 'Amharic', 'Amharic'),
(1, 'FHIR_LANG_ar', @scm, 'ar', 'Arabic', 'Arabic'),
(1, 'FHIR_LANG_an', @scm, 'an', 'Aragonese', 'Aragonese'),
(1, 'FHIR_LANG_hy', @scm, 'hy', 'Armenian', 'Armenian'),
(1, 'FHIR_LANG_as', @scm, 'as', 'Assamese', 'Assamese'),
(1, 'FHIR_LANG_av', @scm, 'av', 'Avaric', 'Avaric'),
(1, 'FHIR_LANG_ae', @scm, 'ae', 'Avestan', 'Avestan'),
(1, 'FHIR_LANG_ay', @scm, 'ay', 'Aymara', 'Aymara'),
(1, 'FHIR_LANG_az', @scm, 'az', 'Azerbaijani', 'Azerbaijani'),
(1, 'FHIR_LANG_ba', @scm, 'ba', 'Bashkir', 'Bashkir'),
(1, 'FHIR_LANG_bm', @scm, 'bm', 'Bambara', 'Bambara'),
(1, 'FHIR_LANG_eu', @scm, 'eu', 'Basque', 'Basque'),
(1, 'FHIR_LANG_be', @scm, 'be', 'Belarusian', 'Belarusian'),
(1, 'FHIR_LANG_bn', @scm, 'bn', 'Bengali', 'Bengali'),
(1, 'FHIR_LANG_bh', @scm, 'bh', 'Bihari', 'Bihari'),
(1, 'FHIR_LANG_bi', @scm, 'bi', 'Bislama', 'Bislama'),
(1, 'FHIR_LANG_bo', @scm, 'bo', 'Tibetan', 'Tibetan'),
(1, 'FHIR_LANG_bs', @scm, 'bs', 'Bosnian', 'Bosnian'),
(1, 'FHIR_LANG_br', @scm, 'br', 'Breton', 'Breton'),
(1, 'FHIR_LANG_bg', @scm, 'bg', 'Bulgarian', 'Bulgarian'),
(1, 'FHIR_LANG_my', @scm, 'my', 'Burmese', 'Burmese'),
(1, 'FHIR_LANG_ca', @scm, 'ca', 'Catalan; Valencian', 'Catalan; Valencian'),
(1, 'FHIR_LANG_cs', @scm, 'cs', 'Czech', 'Czech'),
(1, 'FHIR_LANG_ch', @scm, 'ch', 'Chamorro', 'Chamorro'),
(1, 'FHIR_LANG_ce', @scm, 'ce', 'Chechen', 'Chechen'),
(1, 'FHIR_LANG_zh', @scm, 'zh', 'Chinese', 'Chinese'),
(1, 'FHIR_LANG_cu', @scm, 'cu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
(1, 'FHIR_LANG_cv', @scm, 'cv', 'Chuvash', 'Chuvash'),
(1, 'FHIR_LANG_kw', @scm, 'kw', 'Cornish', 'Cornish'),
(1, 'FHIR_LANG_co', @scm, 'co', 'Corsican', 'Corsican'),
(1, 'FHIR_LANG_cr', @scm, 'cr', 'Cree', 'Cree'),
(1, 'FHIR_LANG_cy', @scm, 'cy', 'Welsh', 'Welsh'),
(1, 'FHIR_LANG_da', @scm, 'da', 'Danish', 'Danish'),
(1, 'FHIR_LANG_de', @scm, 'de', 'German', 'German'),
(1, 'FHIR_LANG_dv', @scm, 'dv', 'Divehi; Dhivehi; Maldivian', 'Divehi; Dhivehi; Maldivian'),
(1, 'FHIR_LANG_nl', @scm, 'nl', 'Dutch; Flemish', 'Dutch; Flemish'),
(1, 'FHIR_LANG_dz', @scm, 'dz', 'Dzongkha', 'Dzongkha'),
(1, 'FHIR_LANG_el', @scm, 'el', 'Greek, Modern (1453-)', 'Greek, Modern (1453-)'),
(1, 'FHIR_LANG_en', @scm, 'en', 'English', 'English'),
(1, 'FHIR_LANG_eo', @scm, 'eo', 'Esperanto', 'Esperanto'),
(1, 'FHIR_LANG_et', @scm, 'et', 'Estonian', 'Estonian'),
(1, 'FHIR_LANG_ee', @scm, 'ee', 'Ewe', 'Ewe'),
(1, 'FHIR_LANG_fo', @scm, 'fo', 'Faroese', 'Faroese'),
(1, 'FHIR_LANG_fa', @scm, 'fa', 'Persian', 'Persian'),
(1, 'FHIR_LANG_fj', @scm, 'fj', 'Fijian', 'Fijian'),
(1, 'FHIR_LANG_fi', @scm, 'fi', 'Finnish', 'Finnish'),
(1, 'FHIR_LANG_fr', @scm, 'fr', 'French', 'French'),
(1, 'FHIR_LANG_fy', @scm, 'fy', 'Western Frisian', 'Western Frisian'),
(1, 'FHIR_LANG_ff', @scm, 'ff', 'Fulah', 'Fulah'),
(1, 'FHIR_LANG_ka', @scm, 'ka', 'Georgian', 'Georgian'),
(1, 'FHIR_LANG_gd', @scm, 'gd', 'Gaelic; Scottish Gaelic', 'Gaelic; Scottish Gaelic'),
(1, 'FHIR_LANG_ga', @scm, 'ga', 'Irish', 'Irish'),
(1, 'FHIR_LANG_gl', @scm, 'gl', 'Galician', 'Galician'),
(1, 'FHIR_LANG_gv', @scm, 'gv', 'Manx', 'Manx'),
(1, 'FHIR_LANG_gn', @scm, 'gn', 'Guarani', 'Guarani'),
(1, 'FHIR_LANG_gu', @scm, 'gu', 'Gujarati', 'Gujarati'),
(1, 'FHIR_LANG_ht', @scm, 'ht', 'Haitian; Haitian Creole', 'Haitian; Haitian Creole'),
(1, 'FHIR_LANG_ha', @scm, 'ha', 'Hausa', 'Hausa'),
(1, 'FHIR_LANG_he', @scm, 'he', 'Hebrew', 'Hebrew'),
(1, 'FHIR_LANG_hz', @scm, 'hz', 'Herero', 'Herero'),
(1, 'FHIR_LANG_hi', @scm, 'hi', 'Hindi', 'Hindi'),
(1, 'FHIR_LANG_ho', @scm, 'ho', 'Hiri Motu', 'Hiri Motu'),
(1, 'FHIR_LANG_hr', @scm, 'hr', 'Croatian', 'Croatian'),
(1, 'FHIR_LANG_hu', @scm, 'hu', 'Hungarian', 'Hungarian'),
(1, 'FHIR_LANG_ig', @scm, 'ig', 'Igbo', 'Igbo'),
(1, 'FHIR_LANG_is', @scm, 'is', 'Icelandic', 'Icelandic'),
(1, 'FHIR_LANG_io', @scm, 'io', 'Ido', 'Ido'),
(1, 'FHIR_LANG_ii', @scm, 'ii', 'Sichuan Yi', 'Sichuan Yi'),
(1, 'FHIR_LANG_iu', @scm, 'iu', 'Inuktitut', 'Inuktitut'),
(1, 'FHIR_LANG_ie', @scm, 'ie', 'Interlingue', 'Interlingue'),
(1, 'FHIR_LANG_ia', @scm, 'ia', 'Interlingua (International Auxiliary Language Association)', 'Interlingua (International Auxiliary Language Association)'),
(1, 'FHIR_LANG_id', @scm, 'id', 'Indonesian', 'Indonesian'),
(1, 'FHIR_LANG_ik', @scm, 'ik', 'Inupiaq', 'Inupiaq'),
(1, 'FHIR_LANG_it', @scm, 'it', 'Italian', 'Italian'),
(1, 'FHIR_LANG_jv', @scm, 'jv', 'Javanese', 'Javanese'),
(1, 'FHIR_LANG_ja', @scm, 'ja', 'Japanese', 'Japanese'),
(1, 'FHIR_LANG_kl', @scm, 'kl', 'Kalaallisut; Greenlandic', 'Kalaallisut; Greenlandic'),
(1, 'FHIR_LANG_kn', @scm, 'kn', 'Kannada', 'Kannada'),
(1, 'FHIR_LANG_ks', @scm, 'ks', 'Kashmiri', 'Kashmiri'),
(1, 'FHIR_LANG_kr', @scm, 'kr', 'Kanuri', 'Kanuri'),
(1, 'FHIR_LANG_kk', @scm, 'kk', 'Kazakh', 'Kazakh'),
(1, 'FHIR_LANG_km', @scm, 'km', 'Central Khmer', 'Central Khmer'),
(1, 'FHIR_LANG_ki', @scm, 'ki', 'Kikuyu; Gikuyu', 'Kikuyu; Gikuyu'),
(1, 'FHIR_LANG_rw', @scm, 'rw', 'Kinyarwanda', 'Kinyarwanda'),
(1, 'FHIR_LANG_ky', @scm, 'ky', 'Kirghiz; Kyrgyz', 'Kirghiz; Kyrgyz'),
(1, 'FHIR_LANG_kv', @scm, 'kv', 'Komi', 'Komi'),
(1, 'FHIR_LANG_kg', @scm, 'kg', 'Kongo', 'Kongo'),
(1, 'FHIR_LANG_ko', @scm, 'ko', 'Korean', 'Korean'),
(1, 'FHIR_LANG_kj', @scm, 'kj', 'Kuanyama; Kwanyama', 'Kuanyama; Kwanyama'),
(1, 'FHIR_LANG_ku', @scm, 'ku', 'Kurdish', 'Kurdish'),
(1, 'FHIR_LANG_lo', @scm, 'lo', 'Lao', 'Lao'),
(1, 'FHIR_LANG_la', @scm, 'la', 'Latin', 'Latin'),
(1, 'FHIR_LANG_lv', @scm, 'lv', 'Latvian', 'Latvian'),
(1, 'FHIR_LANG_li', @scm, 'li', 'Limburgan; Limburger; Limburgish', 'Limburgan; Limburger; Limburgish'),
(1, 'FHIR_LANG_ln', @scm, 'ln', 'Lingala', 'Lingala'),
(1, 'FHIR_LANG_lt', @scm, 'lt', 'Lithuanian', 'Lithuanian'),
(1, 'FHIR_LANG_lb', @scm, 'lb', 'Luxembourgish; Letzeburgesch', 'Luxembourgish; Letzeburgesch'),
(1, 'FHIR_LANG_lu', @scm, 'lu', 'Luba-Katanga', 'Luba-Katanga'),
(1, 'FHIR_LANG_lg', @scm, 'lg', 'Ganda', 'Ganda'),
(1, 'FHIR_LANG_mk', @scm, 'mk', 'Macedonian', 'Macedonian'),
(1, 'FHIR_LANG_mh', @scm, 'mh', 'Marshallese', 'Marshallese'),
(1, 'FHIR_LANG_ml', @scm, 'ml', 'Malayalam', 'Malayalam'),
(1, 'FHIR_LANG_mi', @scm, 'mi', 'Maori', 'Maori'),
(1, 'FHIR_LANG_mr', @scm, 'mr', 'Marathi', 'Marathi'),
(1, 'FHIR_LANG_ms', @scm, 'ms', 'Malay', 'Malay'),
(1, 'FHIR_LANG_mg', @scm, 'mg', 'Malagasy', 'Malagasy'),
(1, 'FHIR_LANG_mt', @scm, 'mt', 'Maltese', 'Maltese'),
(1, 'FHIR_LANG_mo', @scm, 'mo', 'Moldavian', 'Moldavian'),
(1, 'FHIR_LANG_mn', @scm, 'mn', 'Mongolian', 'Mongolian'),
(1, 'FHIR_LANG_na', @scm, 'na', 'Nauru', 'Nauru'),
(1, 'FHIR_LANG_nv', @scm, 'nv', 'Navajo; Navaho', 'Navajo; Navaho'),
(1, 'FHIR_LANG_nr', @scm, 'nr', 'Ndebele, South; South Ndebele', 'Ndebele, South; South Ndebele'),
(1, 'FHIR_LANG_nd', @scm, 'nd', 'Ndebele, North; North Ndebele', 'Ndebele, North; North Ndebele'),
(1, 'FHIR_LANG_ng', @scm, 'ng', 'Ndonga', 'Ndonga'),
(1, 'FHIR_LANG_ne', @scm, 'ne', 'Nepali', 'Nepali'),
(1, 'FHIR_LANG_nn', @scm, 'nn', 'Norwegian Nynorsk; Nynorsk, Norwegian', 'Norwegian Nynorsk; Nynorsk, Norwegian'),
(1, 'FHIR_LANG_nb', @scm, 'nb', 'Bokmal, Norwegian; Norwegian Bokmal', 'Bokmal, Norwegian; Norwegian Bokmal'),
(1, 'FHIR_LANG_no', @scm, 'no', 'Norwegian', 'Norwegian'),
(1, 'FHIR_LANG_ny', @scm, 'ny', 'Chichewa; Chewa; Nyanja', 'Chichewa; Chewa; Nyanja'),
(1, 'FHIR_LANG_oc', @scm, 'oc', 'Occitan (post1500); Provencal', 'Occitan (post1500); Provencal'),
(1, 'FHIR_LANG_oj', @scm, 'oj', 'Ojibwa', 'Ojibwa'),
(1, 'FHIR_LANG_or', @scm, 'or', 'Oriya', 'Oriya'),
(1, 'FHIR_LANG_om', @scm, 'om', 'Oromo', 'Oromo'),
(1, 'FHIR_LANG_os', @scm, 'os', 'Ossetian; Ossetic', 'Ossetian; Ossetic'),
(1, 'FHIR_LANG_pa', @scm, 'pa', 'Panjabi; Punjabi', 'Panjabi; Punjabi'),
(1, 'FHIR_LANG_pi', @scm, 'pi', 'Pali', 'Pali'),
(1, 'FHIR_LANG_pl', @scm, 'pl', 'Polish', 'Polish'),
(1, 'FHIR_LANG_pt', @scm, 'pt', 'Portuguese', 'Portuguese'),
(1, 'FHIR_LANG_ps', @scm, 'ps', 'Pushto', 'Pushto'),
(1, 'FHIR_LANG_qu', @scm, 'qu', 'Quechua', 'Quechua'),
(1, 'FHIR_LANG_rm', @scm, 'rm', 'Romansh', 'Romansh'),
(1, 'FHIR_LANG_ro', @scm, 'ro', 'Romanian', 'Romanian'),
(1, 'FHIR_LANG_rn', @scm, 'rn', 'Rundi', 'Rundi'),
(1, 'FHIR_LANG_ru', @scm, 'ru', 'Russian', 'Russian'),
(1, 'FHIR_LANG_sg', @scm, 'sg', 'Sango', 'Sango'),
(1, 'FHIR_LANG_sa', @scm, 'sa', 'Sanskrit', 'Sanskrit'),
(1, 'FHIR_LANG_sr', @scm, 'sr', 'Serbian', 'Serbian'),
(1, 'FHIR_LANG_si', @scm, 'si', 'Sinhala; Sinhalese', 'Sinhala; Sinhalese'),
(1, 'FHIR_LANG_sk', @scm, 'sk', 'Slovak', 'Slovak'),
(1, 'FHIR_LANG_sl', @scm, 'sl', 'Slovenian', 'Slovenian'),
(1, 'FHIR_LANG_se', @scm, 'se', 'Northern Sami', 'Northern Sami'),
(1, 'FHIR_LANG_sm', @scm, 'sm', 'Samoan', 'Samoan'),
(1, 'FHIR_LANG_sn', @scm, 'sn', 'Shona', 'Shona'),
(1, 'FHIR_LANG_sd', @scm, 'sd', 'Sindhi', 'Sindhi'),
(1, 'FHIR_LANG_so', @scm, 'so', 'Somali', 'Somali'),
(1, 'FHIR_LANG_st', @scm, 'st', 'Sotho, Southern', 'Sotho, Southern'),
(1, 'FHIR_LANG_es', @scm, 'es', 'Spanish; Castilian', 'Spanish; Castilian'),
(1, 'FHIR_LANG_sc', @scm, 'sc', 'Sardinian', 'Sardinian'),
(1, 'FHIR_LANG_ss', @scm, 'ss', 'Swati', 'Swati'),
(1, 'FHIR_LANG_su', @scm, 'su', 'Sundanese', 'Sundanese'),
(1, 'FHIR_LANG_sw', @scm, 'sw', 'Swahili', 'Swahili'),
(1, 'FHIR_LANG_sv', @scm, 'sv', 'Swedish', 'Swedish'),
(1, 'FHIR_LANG_ty', @scm, 'ty', 'Tahitian', 'Tahitian'),
(1, 'FHIR_LANG_ta', @scm, 'ta', 'Tamil', 'Tamil'),
(1, 'FHIR_LANG_tt', @scm, 'tt', 'Tatar', 'Tatar'),
(1, 'FHIR_LANG_te', @scm, 'te', 'Telugu', 'Telugu'),
(1, 'FHIR_LANG_tg', @scm, 'tg', 'Tajik', 'Tajik'),
(1, 'FHIR_LANG_tl', @scm, 'tl', 'Tagalog', 'Tagalog'),
(1, 'FHIR_LANG_th', @scm, 'th', 'Thai', 'Thai'),
(1, 'FHIR_LANG_ti', @scm, 'ti', 'Tigrinya', 'Tigrinya'),
(1, 'FHIR_LANG_to', @scm, 'to', 'Tonga (Tonga Islands)', 'Tonga (Tonga Islands)'),
(1, 'FHIR_LANG_tn', @scm, 'tn', 'Tswana', 'Tswana'),
(1, 'FHIR_LANG_ts', @scm, 'ts', 'Tsonga', 'Tsonga'),
(1, 'FHIR_LANG_tk', @scm, 'tk', 'Turkmen', 'Turkmen'),
(1, 'FHIR_LANG_tr', @scm, 'tr', 'Turkish', 'Turkish'),
(1, 'FHIR_LANG_tw', @scm, 'tw', 'Twi', 'Twi'),
(1, 'FHIR_LANG_ug', @scm, 'ug', 'Uighur; Uyghur', 'Uighur; Uyghur'),
(1, 'FHIR_LANG_uk', @scm, 'uk', 'Ukrainian', 'Ukrainian'),
(1, 'FHIR_LANG_ur', @scm, 'ur', 'Urdu', 'Urdu'),
(1, 'FHIR_LANG_uz', @scm, 'uz', 'Uzbek', 'Uzbek'),
(1, 'FHIR_LANG_ve', @scm, 've', 'Venda', 'Venda'),
(1, 'FHIR_LANG_vi', @scm, 'vi', 'Vietnamese', 'Vietnamese'),
(1, 'FHIR_LANG_vo', @scm, 'vo', 'Volapuk', 'Volapuk'),
(1, 'FHIR_LANG_wa', @scm, 'wa', 'Walloon', 'Walloon'),
(1, 'FHIR_LANG_wo', @scm, 'wo', 'Wolof', 'Wolof'),
(1, 'FHIR_LANG_xh', @scm, 'xh', 'Xhosa', 'Xhosa'),
(1, 'FHIR_LANG_yi', @scm, 'yi', 'Yiddish', 'Yiddish'),
(1, 'FHIR_LANG_yo', @scm, 'yo', 'Yoruba', 'Yoruba'),
(1, 'FHIR_LANG_za', @scm, 'za', 'Zhuang; Chuang', 'Zhuang; Chuang'),
(1, 'FHIR_LANG_zu', @scm, 'zu', 'Zulu', 'Zulu');
