-- Ensure core code scheme exists
INSERT IGNORE INTO concept (document, id, name, description)
VALUES (1, 'CM_DiscoveryCode', 'Discovery code', 'Discovery (core) coding scheme ');

-- Get scheme id
SELECT @scm := dbid FROM concept WHERE id = 'CM_DiscoveryCode';

-- FHIR VALUE SET --  https://en.wikipedia.org/wiki/List_of_ISO_639-2_codes
-- Ensure FHIR_LANG scheme exists --
INSERT IGNORE INTO concept (document, id, scheme, code, name, description)
VALUES (1, 'ISO639-2', @scm, 'ISO639-2', 'ISO 639-2 Language codes', 'ISO 639-2 Language codes');

-- Get scheme id
SELECT @scm := dbid FROM concept WHERE id = 'ISO639-2';

-- Code scheme prefix entries
INSERT IGNORE INTO concept_property_data
(`dbid`, `group`, `property`, `value`)
SELECT c.dbid, 0 AS `group`, p.dbid AS `property`, 'ISO639-2_' AS `value`
FROM concept c
JOIN concept p ON p.id = 'code_prefix'
WHERE c.id = 'ISO639-2';

-- LANGUAGE CONCEPTS --
INSERT IGNORE INTO concept (document, id, scheme, code, name, description)
VALUES
(1, 'ISO639-2_aar', @scm, 'aar', 'Afar', 'Afar'),
(1, 'ISO639-2_abk', @scm, 'abk', 'Abkhazian', 'Abkhazian'),
(1, 'ISO639-2_ace', @scm, 'ace', 'Achinese', 'Achinese'),
(1, 'ISO639-2_ach', @scm, 'ach', 'Acoli', 'Acoli'),
(1, 'ISO639-2_ada', @scm, 'ada', 'Adangme', 'Adangme'),
(1, 'ISO639-2_ady', @scm, 'ady', 'Adyghe; Adygei', 'Adyghe; Adygei'),
(1, 'ISO639-2_afa', @scm, 'afa', 'Afro-Asiatic languages', 'Afro-Asiatic languages'),
(1, 'ISO639-2_afh', @scm, 'afh', 'Afrihili', 'Afrihili'),
(1, 'ISO639-2_afr', @scm, 'afr', 'Afrikaans', 'Afrikaans'),
(1, 'ISO639-2_ain', @scm, 'ain', 'Ainu', 'Ainu'),
(1, 'ISO639-2_aka', @scm, 'aka', 'Akan', 'Akan'),
(1, 'ISO639-2_akk', @scm, 'akk', 'Akkadian', 'Akkadian'),
(1, 'ISO639-2_alb', @scm, 'alb', 'Albanian', 'Albanian'),
(1, 'ISO639-2_ale', @scm, 'ale', 'Aleut', 'Aleut'),
(1, 'ISO639-2_alg', @scm, 'alg', 'Algonquian languages', 'Algonquian languages'),
(1, 'ISO639-2_alt', @scm, 'alt', 'Southern Altai', 'Southern Altai'),
(1, 'ISO639-2_amh', @scm, 'amh', 'Amharic', 'Amharic'),
(1, 'ISO639-2_ang', @scm, 'ang', 'English, Old (ca.450-1100)', 'English, Old (ca.450-1100)'),
(1, 'ISO639-2_anp', @scm, 'anp', 'Angika', 'Angika'),
(1, 'ISO639-2_apa', @scm, 'apa', 'Apache languages', 'Apache languages'),
(1, 'ISO639-2_ara', @scm, 'ara', 'Arabic', 'Arabic'),
(1, 'ISO639-2_arc', @scm, 'arc', 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)', 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)'),
(1, 'ISO639-2_arg', @scm, 'arg', 'Aragonese', 'Aragonese'),
(1, 'ISO639-2_arm', @scm, 'arm', 'Armenian', 'Armenian'),
(1, 'ISO639-2_arn', @scm, 'arn', 'Mapudungun; Mapuche', 'Mapudungun; Mapuche'),
(1, 'ISO639-2_arp', @scm, 'arp', 'Arapaho', 'Arapaho'),
(1, 'ISO639-2_art', @scm, 'art', 'Artificial languages', 'Artificial languages'),
(1, 'ISO639-2_arw', @scm, 'arw', 'Arawak', 'Arawak'),
(1, 'ISO639-2_asm', @scm, 'asm', 'Assamese', 'Assamese'),
(1, 'ISO639-2_ast', @scm, 'ast', 'Asturian; Bable; Leonese; Asturleonese', 'Asturian; Bable; Leonese; Asturleonese'),
(1, 'ISO639-2_ath', @scm, 'ath', 'Athapascan languages', 'Athapascan languages'),
(1, 'ISO639-2_aus', @scm, 'aus', 'Australian languages', 'Australian languages'),
(1, 'ISO639-2_ava', @scm, 'ava', 'Avaric', 'Avaric'),
(1, 'ISO639-2_ave', @scm, 'ave', 'Avestan', 'Avestan'),
(1, 'ISO639-2_awa', @scm, 'awa', 'Awadhi', 'Awadhi'),
(1, 'ISO639-2_aym', @scm, 'aym', 'Aymara', 'Aymara'),
(1, 'ISO639-2_aze', @scm, 'aze', 'Azerbaijani', 'Azerbaijani'),
(1, 'ISO639-2_bad', @scm, 'bad', 'Banda languages', 'Banda languages'),
(1, 'ISO639-2_bai', @scm, 'bai', 'Bamileke languages', 'Bamileke languages'),
(1, 'ISO639-2_bak', @scm, 'bak', 'Bashkir', 'Bashkir'),
(1, 'ISO639-2_bal', @scm, 'bal', 'Baluchi', 'Baluchi'),
(1, 'ISO639-2_bam', @scm, 'bam', 'Bambara', 'Bambara'),
(1, 'ISO639-2_ban', @scm, 'ban', 'Balinese', 'Balinese'),
(1, 'ISO639-2_baq', @scm, 'baq', 'Basque', 'Basque'),
(1, 'ISO639-2_bas', @scm, 'bas', 'Basa', 'Basa'),
(1, 'ISO639-2_bat', @scm, 'bat', 'Baltic languages', 'Baltic languages'),
(1, 'ISO639-2_bej', @scm, 'bej', 'Beja; Bedawiyet', 'Beja; Bedawiyet'),
(1, 'ISO639-2_bel', @scm, 'bel', 'Belarusian', 'Belarusian'),
(1, 'ISO639-2_bem', @scm, 'bem', 'Bemba', 'Bemba'),
(1, 'ISO639-2_ben', @scm, 'ben', 'Bengali', 'Bengali'),
(1, 'ISO639-2_ber', @scm, 'ber', 'Berber languages', 'Berber languages'),
(1, 'ISO639-2_bho', @scm, 'bho', 'Bhojpuri', 'Bhojpuri'),
(1, 'ISO639-2_bih', @scm, 'bih', 'Bihari languages', 'Bihari languages'),
(1, 'ISO639-2_bik', @scm, 'bik', 'Bikol', 'Bikol'),
(1, 'ISO639-2_bin', @scm, 'bin', 'Bini; Edo', 'Bini; Edo'),
(1, 'ISO639-2_bis', @scm, 'bis', 'Bislama', 'Bislama'),
(1, 'ISO639-2_bla', @scm, 'bla', 'Siksika', 'Siksika'),
(1, 'ISO639-2_bnt', @scm, 'bnt', 'Bantu languages', 'Bantu languages'),
(1, 'ISO639-2_bod', @scm, 'bod', 'Tibetan', 'Tibetan'),
(1, 'ISO639-2_bos', @scm, 'bos', 'Bosnian', 'Bosnian'),
(1, 'ISO639-2_bra', @scm, 'bra', 'Braj', 'Braj'),
(1, 'ISO639-2_bre', @scm, 'bre', 'Breton', 'Breton'),
(1, 'ISO639-2_btk', @scm, 'btk', 'Batak languages', 'Batak languages'),
(1, 'ISO639-2_bua', @scm, 'bua', 'Buriat', 'Buriat'),
(1, 'ISO639-2_bug', @scm, 'bug', 'Buginese', 'Buginese'),
(1, 'ISO639-2_bul', @scm, 'bul', 'Bulgarian', 'Bulgarian'),
(1, 'ISO639-2_bur', @scm, 'bur', 'Burmese', 'Burmese'),
(1, 'ISO639-2_byn', @scm, 'byn', 'Blin; Bilin', 'Blin; Bilin'),
(1, 'ISO639-2_cad', @scm, 'cad', 'Caddo', 'Caddo'),
(1, 'ISO639-2_cai', @scm, 'cai', 'Central American Indian languages', 'Central American Indian languages'),
(1, 'ISO639-2_car', @scm, 'car', 'Galibi Carib', 'Galibi Carib'),
(1, 'ISO639-2_cat', @scm, 'cat', 'Catalan; Valencian', 'Catalan; Valencian'),
(1, 'ISO639-2_cau', @scm, 'cau', 'Caucasian languages', 'Caucasian languages'),
(1, 'ISO639-2_ceb', @scm, 'ceb', 'Cebuano', 'Cebuano'),
(1, 'ISO639-2_cel', @scm, 'cel', 'Celtic languages', 'Celtic languages'),
(1, 'ISO639-2_ces', @scm, 'ces', 'Czech', 'Czech'),
(1, 'ISO639-2_cha', @scm, 'cha', 'Chamorro', 'Chamorro'),
(1, 'ISO639-2_chb', @scm, 'chb', 'Chibcha', 'Chibcha'),
(1, 'ISO639-2_che', @scm, 'che', 'Chechen', 'Chechen'),
(1, 'ISO639-2_chg', @scm, 'chg', 'Chagatai', 'Chagatai'),
(1, 'ISO639-2_chi', @scm, 'chi', 'Chinese', 'Chinese'),
(1, 'ISO639-2_chk', @scm, 'chk', 'Chuukese', 'Chuukese'),
(1, 'ISO639-2_chm', @scm, 'chm', 'Mari', 'Mari'),
(1, 'ISO639-2_chn', @scm, 'chn', 'Chinook jargon', 'Chinook jargon'),
(1, 'ISO639-2_cho', @scm, 'cho', 'Choctaw', 'Choctaw'),
(1, 'ISO639-2_chp', @scm, 'chp', 'Chipewyan; Dene Suline', 'Chipewyan; Dene Suline'),
(1, 'ISO639-2_chr', @scm, 'chr', 'Cherokee', 'Cherokee'),
(1, 'ISO639-2_chu', @scm, 'chu', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
(1, 'ISO639-2_chv', @scm, 'chv', 'Chuvash', 'Chuvash'),
(1, 'ISO639-2_chy', @scm, 'chy', 'Cheyenne', 'Cheyenne'),
(1, 'ISO639-2_cmc', @scm, 'cmc', 'Chamic languages', 'Chamic languages'),
(1, 'ISO639-2_cnr', @scm, 'cnr', 'Montenegrin', 'Montenegrin'),
(1, 'ISO639-2_cop', @scm, 'cop', 'Coptic', 'Coptic'),
(1, 'ISO639-2_cor', @scm, 'cor', 'Cornish', 'Cornish'),
(1, 'ISO639-2_cos', @scm, 'cos', 'Corsican', 'Corsican'),
(1, 'ISO639-2_cpe', @scm, 'cpe', 'Creoles and pidgins, English based', 'Creoles and pidgins, English based'),
(1, 'ISO639-2_cpf', @scm, 'cpf', 'Creoles and pidgins, French-based', 'Creoles and pidgins, French-based'),
(1, 'ISO639-2_cpp', @scm, 'cpp', 'Creoles and pidgins, Portuguese-based', 'Creoles and pidgins, Portuguese-based'),
(1, 'ISO639-2_cre', @scm, 'cre', 'Cree', 'Cree'),
(1, 'ISO639-2_crh', @scm, 'crh', 'Crimean Tatar; Crimean Turkish', 'Crimean Tatar; Crimean Turkish'),
(1, 'ISO639-2_crp', @scm, 'crp', 'Creoles and pidgins', 'Creoles and pidgins'),
(1, 'ISO639-2_csb', @scm, 'csb', 'Kashubian', 'Kashubian'),
(1, 'ISO639-2_cus', @scm, 'cus', 'Cushitic languages', 'Cushitic languages'),
(1, 'ISO639-2_cym', @scm, 'cym', 'Welsh', 'Welsh'),
(1, 'ISO639-2_cze', @scm, 'cze', 'Czech', 'Czech'),
(1, 'ISO639-2_dak', @scm, 'dak', 'Dakota', 'Dakota'),
(1, 'ISO639-2_dan', @scm, 'dan', 'Danish', 'Danish'),
(1, 'ISO639-2_dar', @scm, 'dar', 'Dargwa', 'Dargwa'),
(1, 'ISO639-2_day', @scm, 'day', 'Land Dayak languages', 'Land Dayak languages'),
(1, 'ISO639-2_del', @scm, 'del', 'Delaware', 'Delaware'),
(1, 'ISO639-2_den', @scm, 'den', 'Slave (Athapascan)', 'Slave (Athapascan)'),
(1, 'ISO639-2_deu', @scm, 'deu', 'German', 'German'),
(1, 'ISO639-2_dgr', @scm, 'dgr', 'Dogrib', 'Dogrib'),
(1, 'ISO639-2_din', @scm, 'din', 'Dinka', 'Dinka'),
(1, 'ISO639-2_div', @scm, 'div', 'Divehi; Dhivehi; Maldivian', 'Divehi; Dhivehi; Maldivian'),
(1, 'ISO639-2_doi', @scm, 'doi', 'Dogri', 'Dogri'),
(1, 'ISO639-2_dra', @scm, 'dra', 'Dravidian languages', 'Dravidian languages'),
(1, 'ISO639-2_dsb', @scm, 'dsb', 'Lower Sorbian', 'Lower Sorbian'),
(1, 'ISO639-2_dua', @scm, 'dua', 'Duala', 'Duala'),
(1, 'ISO639-2_dum', @scm, 'dum', 'Dutch, Middle (ca.1050-1350)', 'Dutch, Middle (ca.1050-1350)'),
(1, 'ISO639-2_dut', @scm, 'dut', 'Dutch; Flemish', 'Dutch; Flemish'),
(1, 'ISO639-2_dyu', @scm, 'dyu', 'Dyula', 'Dyula'),
(1, 'ISO639-2_dzo', @scm, 'dzo', 'Dzongkha', 'Dzongkha'),
(1, 'ISO639-2_efi', @scm, 'efi', 'Efik', 'Efik'),
(1, 'ISO639-2_egy', @scm, 'egy', 'Egyptian (Ancient)', 'Egyptian (Ancient)'),
(1, 'ISO639-2_eka', @scm, 'eka', 'Ekajuk', 'Ekajuk'),
(1, 'ISO639-2_ell', @scm, 'ell', 'Greek, Modern (1453-)', 'Greek, Modern (1453-)'),
(1, 'ISO639-2_elx', @scm, 'elx', 'Elamite', 'Elamite'),
(1, 'ISO639-2_eng', @scm, 'eng', 'English', 'English'),
(1, 'ISO639-2_enm', @scm, 'enm', 'English, Middle (1100-1500)', 'English, Middle (1100-1500)'),
(1, 'ISO639-2_epo', @scm, 'epo', 'Esperanto', 'Esperanto'),
(1, 'ISO639-2_est', @scm, 'est', 'Estonian', 'Estonian'),
(1, 'ISO639-2_eus', @scm, 'eus', 'Basque', 'Basque'),
(1, 'ISO639-2_ewe', @scm, 'ewe', 'Ewe', 'Ewe'),
(1, 'ISO639-2_ewo', @scm, 'ewo', 'Ewondo', 'Ewondo'),
(1, 'ISO639-2_fan', @scm, 'fan', 'Fang', 'Fang'),
(1, 'ISO639-2_fao', @scm, 'fao', 'Faroese', 'Faroese'),
(1, 'ISO639-2_fas', @scm, 'fas', 'Persian', 'Persian'),
(1, 'ISO639-2_fat', @scm, 'fat', 'Fanti', 'Fanti'),
(1, 'ISO639-2_fij', @scm, 'fij', 'Fijian', 'Fijian'),
(1, 'ISO639-2_fil', @scm, 'fil', 'Filipino; Pilipino', 'Filipino; Pilipino'),
(1, 'ISO639-2_fin', @scm, 'fin', 'Finnish', 'Finnish'),
(1, 'ISO639-2_fiu', @scm, 'fiu', 'Finno-Ugrian languages', 'Finno-Ugrian languages'),
(1, 'ISO639-2_fon', @scm, 'fon', 'Fon', 'Fon'),
(1, 'ISO639-2_fra', @scm, 'fra', 'French', 'French'),
(1, 'ISO639-2_fre', @scm, 'fre', 'French', 'French'),
(1, 'ISO639-2_frm', @scm, 'frm', 'French, Middle (ca.1400-1600)', 'French, Middle (ca.1400-1600)'),
(1, 'ISO639-2_fro', @scm, 'fro', 'French, Old (842-ca.1400)', 'French, Old (842-ca.1400)'),
(1, 'ISO639-2_frr', @scm, 'frr', 'Northern Frisian', 'Northern Frisian'),
(1, 'ISO639-2_frs', @scm, 'frs', 'Eastern Frisian', 'Eastern Frisian'),
(1, 'ISO639-2_fry', @scm, 'fry', 'Western Frisian', 'Western Frisian'),
(1, 'ISO639-2_ful', @scm, 'ful', 'Fulah', 'Fulah'),
(1, 'ISO639-2_fur', @scm, 'fur', 'Friulian', 'Friulian'),
(1, 'ISO639-2_gaa', @scm, 'gaa', 'Ga', 'Ga'),
(1, 'ISO639-2_gay', @scm, 'gay', 'Gayo', 'Gayo'),
(1, 'ISO639-2_gba', @scm, 'gba', 'Gbaya', 'Gbaya'),
(1, 'ISO639-2_gem', @scm, 'gem', 'Germanic languages', 'Germanic languages'),
(1, 'ISO639-2_geo', @scm, 'geo', 'Georgian', 'Georgian'),
(1, 'ISO639-2_ger', @scm, 'ger', 'German', 'German'),
(1, 'ISO639-2_gez', @scm, 'gez', 'Geez', 'Geez'),
(1, 'ISO639-2_gil', @scm, 'gil', 'Gilbertese', 'Gilbertese'),
(1, 'ISO639-2_gla', @scm, 'gla', 'Gaelic; Scottish Gaelic', 'Gaelic; Scottish Gaelic'),
(1, 'ISO639-2_gle', @scm, 'gle', 'Irish', 'Irish'),
(1, 'ISO639-2_glg', @scm, 'glg', 'Galician', 'Galician'),
(1, 'ISO639-2_glv', @scm, 'glv', 'Manx', 'Manx'),
(1, 'ISO639-2_gmh', @scm, 'gmh', 'German, Middle High (ca.1050-1500)', 'German, Middle High (ca.1050-1500)'),
(1, 'ISO639-2_goh', @scm, 'goh', 'German, Old High (ca.750-1050)', 'German, Old High (ca.750-1050)'),
(1, 'ISO639-2_gon', @scm, 'gon', 'Gondi', 'Gondi'),
(1, 'ISO639-2_gor', @scm, 'gor', 'Gorontalo', 'Gorontalo'),
(1, 'ISO639-2_got', @scm, 'got', 'Gothic', 'Gothic'),
(1, 'ISO639-2_grb', @scm, 'grb', 'Grebo', 'Grebo'),
(1, 'ISO639-2_grc', @scm, 'grc', 'Greek, Ancient (to 1453)', 'Greek, Ancient (to 1453)'),
(1, 'ISO639-2_gre', @scm, 'gre', 'Greek, Modern (1453-)', 'Greek, Modern (1453-)'),
(1, 'ISO639-2_grn', @scm, 'grn', 'Guarani', 'Guarani'),
(1, 'ISO639-2_gsw', @scm, 'gsw', 'Swiss German; Alemannic; Alsatian', 'Swiss German; Alemannic; Alsatian'),
(1, 'ISO639-2_guj', @scm, 'guj', 'Gujarati', 'Gujarati'),
(1, 'ISO639-2_gwi', @scm, 'gwi', 'Gwich''in', 'Gwich''in'),
(1, 'ISO639-2_hai', @scm, 'hai', 'Haida', 'Haida'),
(1, 'ISO639-2_hat', @scm, 'hat', 'Haitian; Haitian Creole', 'Haitian; Haitian Creole'),
(1, 'ISO639-2_hau', @scm, 'hau', 'Hausa', 'Hausa'),
(1, 'ISO639-2_haw', @scm, 'haw', 'Hawaiian', 'Hawaiian'),
(1, 'ISO639-2_heb', @scm, 'heb', 'Hebrew', 'Hebrew'),
(1, 'ISO639-2_her', @scm, 'her', 'Herero', 'Herero'),
(1, 'ISO639-2_hil', @scm, 'hil', 'Hiligaynon', 'Hiligaynon'),
(1, 'ISO639-2_him', @scm, 'him', 'Himachali languages; Western Pahari languages', 'Himachali languages; Western Pahari languages'),
(1, 'ISO639-2_hin', @scm, 'hin', 'Hindi', 'Hindi'),
(1, 'ISO639-2_hit', @scm, 'hit', 'Hittite', 'Hittite'),
(1, 'ISO639-2_hmn', @scm, 'hmn', 'Hmong; Mong', 'Hmong; Mong'),
(1, 'ISO639-2_hmo', @scm, 'hmo', 'Hiri Motu', 'Hiri Motu'),
(1, 'ISO639-2_hrv', @scm, 'hrv', 'Croatian', 'Croatian'),
(1, 'ISO639-2_hsb', @scm, 'hsb', 'Upper Sorbian', 'Upper Sorbian'),
(1, 'ISO639-2_hun', @scm, 'hun', 'Hungarian', 'Hungarian'),
(1, 'ISO639-2_hup', @scm, 'hup', 'Hupa', 'Hupa'),
(1, 'ISO639-2_hye', @scm, 'hye', 'Armenian', 'Armenian'),
(1, 'ISO639-2_iba', @scm, 'iba', 'Iban', 'Iban'),
(1, 'ISO639-2_ibo', @scm, 'ibo', 'Igbo', 'Igbo'),
(1, 'ISO639-2_ice', @scm, 'ice', 'Icelandic', 'Icelandic'),
(1, 'ISO639-2_ido', @scm, 'ido', 'Ido', 'Ido'),
(1, 'ISO639-2_iii', @scm, 'iii', 'Sichuan Yi; Nuosu', 'Sichuan Yi; Nuosu'),
(1, 'ISO639-2_ijo', @scm, 'ijo', 'Ijo languages', 'Ijo languages'),
(1, 'ISO639-2_iku', @scm, 'iku', 'Inuktitut', 'Inuktitut'),
(1, 'ISO639-2_ile', @scm, 'ile', 'Interlingue; Occidental', 'Interlingue; Occidental'),
(1, 'ISO639-2_ilo', @scm, 'ilo', 'Iloko', 'Iloko'),
(1, 'ISO639-2_ina', @scm, 'ina', 'Interlingua (International Auxiliary Language Association)', 'Interlingua (International Auxiliary Language Association)'),
(1, 'ISO639-2_inc', @scm, 'inc', 'Indic languages', 'Indic languages'),
(1, 'ISO639-2_ind', @scm, 'ind', 'Indonesian', 'Indonesian'),
(1, 'ISO639-2_ine', @scm, 'ine', 'Indo-European languages', 'Indo-European languages'),
(1, 'ISO639-2_inh', @scm, 'inh', 'Ingush', 'Ingush'),
(1, 'ISO639-2_ipk', @scm, 'ipk', 'Inupiaq', 'Inupiaq'),
(1, 'ISO639-2_ira', @scm, 'ira', 'Iranian languages', 'Iranian languages'),
(1, 'ISO639-2_iro', @scm, 'iro', 'Iroquoian languages', 'Iroquoian languages'),
(1, 'ISO639-2_isl', @scm, 'isl', 'Icelandic', 'Icelandic'),
(1, 'ISO639-2_ita', @scm, 'ita', 'Italian', 'Italian'),
(1, 'ISO639-2_jav', @scm, 'jav', 'Javanese', 'Javanese'),
(1, 'ISO639-2_jbo', @scm, 'jbo', 'Lojban', 'Lojban'),
(1, 'ISO639-2_jpn', @scm, 'jpn', 'Japanese', 'Japanese'),
(1, 'ISO639-2_jpr', @scm, 'jpr', 'Judeo-Persian', 'Judeo-Persian'),
(1, 'ISO639-2_jrb', @scm, 'jrb', 'Judeo-Arabic', 'Judeo-Arabic'),
(1, 'ISO639-2_kaa', @scm, 'kaa', 'Kara-Kalpak', 'Kara-Kalpak'),
(1, 'ISO639-2_kab', @scm, 'kab', 'Kabyle', 'Kabyle'),
(1, 'ISO639-2_kac', @scm, 'kac', 'Kachin; Jingpho', 'Kachin; Jingpho'),
(1, 'ISO639-2_kal', @scm, 'kal', 'Kalaallisut; Greenlandic', 'Kalaallisut; Greenlandic'),
(1, 'ISO639-2_kam', @scm, 'kam', 'Kamba', 'Kamba'),
(1, 'ISO639-2_kan', @scm, 'kan', 'Kannada', 'Kannada'),
(1, 'ISO639-2_kar', @scm, 'kar', 'Karen languages', 'Karen languages'),
(1, 'ISO639-2_kas', @scm, 'kas', 'Kashmiri', 'Kashmiri'),
(1, 'ISO639-2_kat', @scm, 'kat', 'Georgian', 'Georgian'),
(1, 'ISO639-2_kau', @scm, 'kau', 'Kanuri', 'Kanuri'),
(1, 'ISO639-2_kaw', @scm, 'kaw', 'Kawi', 'Kawi'),
(1, 'ISO639-2_kaz', @scm, 'kaz', 'Kazakh', 'Kazakh'),
(1, 'ISO639-2_kbd', @scm, 'kbd', 'Kabardian', 'Kabardian'),
(1, 'ISO639-2_kha', @scm, 'kha', 'Khasi', 'Khasi'),
(1, 'ISO639-2_khi', @scm, 'khi', 'Khoisan languages', 'Khoisan languages'),
(1, 'ISO639-2_khm', @scm, 'khm', 'Central Khmer', 'Central Khmer'),
(1, 'ISO639-2_kho', @scm, 'kho', 'Khotanese; Sakan', 'Khotanese; Sakan'),
(1, 'ISO639-2_kik', @scm, 'kik', 'Kikuyu; Gikuyu', 'Kikuyu; Gikuyu'),
(1, 'ISO639-2_kin', @scm, 'kin', 'Kinyarwanda', 'Kinyarwanda'),
(1, 'ISO639-2_kir', @scm, 'kir', 'Kirghiz; Kyrgyz', 'Kirghiz; Kyrgyz'),
(1, 'ISO639-2_kmb', @scm, 'kmb', 'Kimbundu', 'Kimbundu'),
(1, 'ISO639-2_kok', @scm, 'kok', 'Konkani', 'Konkani'),
(1, 'ISO639-2_kom', @scm, 'kom', 'Komi', 'Komi'),
(1, 'ISO639-2_kon', @scm, 'kon', 'Kongo', 'Kongo'),
(1, 'ISO639-2_kor', @scm, 'kor', 'Korean', 'Korean'),
(1, 'ISO639-2_kos', @scm, 'kos', 'Kosraean', 'Kosraean'),
(1, 'ISO639-2_kpe', @scm, 'kpe', 'Kpelle', 'Kpelle'),
(1, 'ISO639-2_krc', @scm, 'krc', 'Karachay-Balkar', 'Karachay-Balkar'),
(1, 'ISO639-2_krl', @scm, 'krl', 'Karelian', 'Karelian'),
(1, 'ISO639-2_kro', @scm, 'kro', 'Kru languages', 'Kru languages'),
(1, 'ISO639-2_kru', @scm, 'kru', 'Kurukh', 'Kurukh'),
(1, 'ISO639-2_kua', @scm, 'kua', 'Kuanyama; Kwanyama', 'Kuanyama; Kwanyama'),
(1, 'ISO639-2_kum', @scm, 'kum', 'Kumyk', 'Kumyk'),
(1, 'ISO639-2_kur', @scm, 'kur', 'Kurdish', 'Kurdish'),
(1, 'ISO639-2_kut', @scm, 'kut', 'Kutenai', 'Kutenai'),
(1, 'ISO639-2_lad', @scm, 'lad', 'Ladino', 'Ladino'),
(1, 'ISO639-2_lah', @scm, 'lah', 'Lahnda', 'Lahnda'),
(1, 'ISO639-2_lam', @scm, 'lam', 'Lamba', 'Lamba'),
(1, 'ISO639-2_lao', @scm, 'lao', 'Lao', 'Lao'),
(1, 'ISO639-2_lat', @scm, 'lat', 'Latin', 'Latin'),
(1, 'ISO639-2_lav', @scm, 'lav', 'Latvian', 'Latvian'),
(1, 'ISO639-2_lez', @scm, 'lez', 'Lezghian', 'Lezghian'),
(1, 'ISO639-2_lim', @scm, 'lim', 'Limburgan; Limburger; Limburgish', 'Limburgan; Limburger; Limburgish'),
(1, 'ISO639-2_lin', @scm, 'lin', 'Lingala', 'Lingala'),
(1, 'ISO639-2_lit', @scm, 'lit', 'Lithuanian', 'Lithuanian'),
(1, 'ISO639-2_lol', @scm, 'lol', 'Mongo', 'Mongo'),
(1, 'ISO639-2_loz', @scm, 'loz', 'Lozi', 'Lozi'),
(1, 'ISO639-2_ltz', @scm, 'ltz', 'Luxembourgish; Letzeburgesch', 'Luxembourgish; Letzeburgesch'),
(1, 'ISO639-2_lua', @scm, 'lua', 'Luba-Lulua', 'Luba-Lulua'),
(1, 'ISO639-2_lub', @scm, 'lub', 'Luba-Katanga', 'Luba-Katanga'),
(1, 'ISO639-2_lug', @scm, 'lug', 'Ganda', 'Ganda'),
(1, 'ISO639-2_lui', @scm, 'lui', 'Luiseno', 'Luiseno'),
(1, 'ISO639-2_lun', @scm, 'lun', 'Lunda', 'Lunda'),
(1, 'ISO639-2_luo', @scm, 'luo', 'Luo (Kenya and Tanzania)', 'Luo (Kenya and Tanzania)'),
(1, 'ISO639-2_lus', @scm, 'lus', 'Lushai', 'Lushai'),
(1, 'ISO639-2_mac', @scm, 'mac', 'Macedonian', 'Macedonian'),
(1, 'ISO639-2_mad', @scm, 'mad', 'Madurese', 'Madurese'),
(1, 'ISO639-2_mag', @scm, 'mag', 'Magahi', 'Magahi'),
(1, 'ISO639-2_mah', @scm, 'mah', 'Marshallese', 'Marshallese'),
(1, 'ISO639-2_mai', @scm, 'mai', 'Maithili', 'Maithili'),
(1, 'ISO639-2_mak', @scm, 'mak', 'Makasar', 'Makasar'),
(1, 'ISO639-2_mal', @scm, 'mal', 'Malayalam', 'Malayalam'),
(1, 'ISO639-2_man', @scm, 'man', 'Mandingo', 'Mandingo'),
(1, 'ISO639-2_mao', @scm, 'mao', 'Maori', 'Maori'),
(1, 'ISO639-2_map', @scm, 'map', 'Austronesian languages', 'Austronesian languages'),
(1, 'ISO639-2_mar', @scm, 'mar', 'Marathi', 'Marathi'),
(1, 'ISO639-2_mas', @scm, 'mas', 'Masai', 'Masai'),
(1, 'ISO639-2_may', @scm, 'may', 'Malay', 'Malay'),
(1, 'ISO639-2_mdf', @scm, 'mdf', 'Moksha', 'Moksha'),
(1, 'ISO639-2_mdr', @scm, 'mdr', 'Mandar', 'Mandar'),
(1, 'ISO639-2_men', @scm, 'men', 'Mende', 'Mende'),
(1, 'ISO639-2_mga', @scm, 'mga', 'Irish, Middle (900-1200)', 'Irish, Middle (900-1200)'),
(1, 'ISO639-2_mic', @scm, 'mic', 'Mi''kmaq; Micmac', 'Mi''kmaq; Micmac'),
(1, 'ISO639-2_min', @scm, 'min', 'Minangkabau', 'Minangkabau'),
(1, 'ISO639-2_mis', @scm, 'mis', 'Uncoded languages', 'Uncoded languages'),
(1, 'ISO639-2_mkd', @scm, 'mkd', 'Macedonian', 'Macedonian'),
(1, 'ISO639-2_mkh', @scm, 'mkh', 'Mon-Khmer languages', 'Mon-Khmer languages'),
(1, 'ISO639-2_mlg', @scm, 'mlg', 'Malagasy', 'Malagasy'),
(1, 'ISO639-2_mlt', @scm, 'mlt', 'Maltese', 'Maltese'),
(1, 'ISO639-2_mnc', @scm, 'mnc', 'Manchu', 'Manchu'),
(1, 'ISO639-2_mni', @scm, 'mni', 'Manipuri', 'Manipuri'),
(1, 'ISO639-2_mno', @scm, 'mno', 'Manobo languages', 'Manobo languages'),
(1, 'ISO639-2_moh', @scm, 'moh', 'Mohawk', 'Mohawk'),
(1, 'ISO639-2_mon', @scm, 'mon', 'Mongolian', 'Mongolian'),
(1, 'ISO639-2_mos', @scm, 'mos', 'Mossi', 'Mossi'),
(1, 'ISO639-2_mri', @scm, 'mri', 'Maori', 'Maori'),
(1, 'ISO639-2_msa', @scm, 'msa', 'Malay', 'Malay'),
(1, 'ISO639-2_mul', @scm, 'mul', 'Multiple languages', 'Multiple languages'),
(1, 'ISO639-2_mun', @scm, 'mun', 'Munda languages', 'Munda languages'),
(1, 'ISO639-2_mus', @scm, 'mus', 'Creek', 'Creek'),
(1, 'ISO639-2_mwl', @scm, 'mwl', 'Mirandese', 'Mirandese'),
(1, 'ISO639-2_mwr', @scm, 'mwr', 'Marwari', 'Marwari'),
(1, 'ISO639-2_mya', @scm, 'mya', 'Burmese', 'Burmese'),
(1, 'ISO639-2_myn', @scm, 'myn', 'Mayan languages', 'Mayan languages'),
(1, 'ISO639-2_myv', @scm, 'myv', 'Erzya', 'Erzya'),
(1, 'ISO639-2_nah', @scm, 'nah', 'Nahuatl languages', 'Nahuatl languages'),
(1, 'ISO639-2_nai', @scm, 'nai', 'North American Indian languages', 'North American Indian languages'),
(1, 'ISO639-2_nap', @scm, 'nap', 'Neapolitan', 'Neapolitan'),
(1, 'ISO639-2_nau', @scm, 'nau', 'Nauru', 'Nauru'),
(1, 'ISO639-2_nav', @scm, 'nav', 'Navajo; Navaho', 'Navajo; Navaho'),
(1, 'ISO639-2_nbl', @scm, 'nbl', 'Ndebele, South; South Ndebele', 'Ndebele, South; South Ndebele'),
(1, 'ISO639-2_nde', @scm, 'nde', 'Ndebele, North; North Ndebele', 'Ndebele, North; North Ndebele'),
(1, 'ISO639-2_ndo', @scm, 'ndo', 'Ndonga', 'Ndonga'),
(1, 'ISO639-2_nds', @scm, 'nds', 'Low German; Low Saxon; German, Low; Saxon, Low', 'Low German; Low Saxon; German, Low; Saxon, Low'),
(1, 'ISO639-2_nep', @scm, 'nep', 'Nepali', 'Nepali'),
(1, 'ISO639-2_new', @scm, 'new', 'Nepal Bhasa; Newari', 'Nepal Bhasa; Newari'),
(1, 'ISO639-2_nia', @scm, 'nia', 'Nias', 'Nias'),
(1, 'ISO639-2_nic', @scm, 'nic', 'Niger-Kordofanian languages', 'Niger-Kordofanian languages'),
(1, 'ISO639-2_niu', @scm, 'niu', 'Niuean', 'Niuean'),
(1, 'ISO639-2_nld', @scm, 'nld', 'Dutch; Flemish', 'Dutch; Flemish'),
(1, 'ISO639-2_nno', @scm, 'nno', 'Norwegian Nynorsk; Nynorsk, Norwegian', 'Norwegian Nynorsk; Nynorsk, Norwegian'),
(1, 'ISO639-2_nob', @scm, 'nob', 'Bokmål, Norwegian; Norwegian Bokmål', 'Bokmål, Norwegian; Norwegian Bokmål'),
(1, 'ISO639-2_nog', @scm, 'nog', 'Nogai', 'Nogai'),
(1, 'ISO639-2_non', @scm, 'non', 'Norse, Old', 'Norse, Old'),
(1, 'ISO639-2_nor', @scm, 'nor', 'Norwegian', 'Norwegian'),
(1, 'ISO639-2_nqo', @scm, 'nqo', 'N''Ko', 'N''Ko'),
(1, 'ISO639-2_nso', @scm, 'nso', 'Pedi; Sepedi; Northern Sotho', 'Pedi; Sepedi; Northern Sotho'),
(1, 'ISO639-2_nub', @scm, 'nub', 'Nubian languages', 'Nubian languages'),
(1, 'ISO639-2_nwc', @scm, 'nwc', 'Classical Newari; Old Newari; Classical Nepal Bhasa', 'Classical Newari; Old Newari; Classical Nepal Bhasa'),
(1, 'ISO639-2_nya', @scm, 'nya', 'Chichewa; Chewa; Nyanja', 'Chichewa; Chewa; Nyanja'),
(1, 'ISO639-2_nym', @scm, 'nym', 'Nyamwezi', 'Nyamwezi'),
(1, 'ISO639-2_nyn', @scm, 'nyn', 'Nyankole', 'Nyankole'),
(1, 'ISO639-2_nyo', @scm, 'nyo', 'Nyoro', 'Nyoro'),
(1, 'ISO639-2_nzi', @scm, 'nzi', 'Nzima', 'Nzima'),
(1, 'ISO639-2_oci', @scm, 'oci', 'Occitan (post 1500)', 'Occitan (post 1500)'),
(1, 'ISO639-2_oji', @scm, 'oji', 'Ojibwa', 'Ojibwa'),
(1, 'ISO639-2_ori', @scm, 'ori', 'Oriya', 'Oriya'),
(1, 'ISO639-2_orm', @scm, 'orm', 'Oromo', 'Oromo'),
(1, 'ISO639-2_osa', @scm, 'osa', 'Osage', 'Osage'),
(1, 'ISO639-2_oss', @scm, 'oss', 'Ossetian; Ossetic', 'Ossetian; Ossetic'),
(1, 'ISO639-2_ota', @scm, 'ota', 'Turkish, Ottoman (1500-1928)', 'Turkish, Ottoman (1500-1928)'),
(1, 'ISO639-2_oto', @scm, 'oto', 'Otomian languages', 'Otomian languages'),
(1, 'ISO639-2_paa', @scm, 'paa', 'Papuan languages', 'Papuan languages'),
(1, 'ISO639-2_pag', @scm, 'pag', 'Pangasinan', 'Pangasinan'),
(1, 'ISO639-2_pal', @scm, 'pal', 'Pahlavi', 'Pahlavi'),
(1, 'ISO639-2_pam', @scm, 'pam', 'Pampanga; Kapampangan', 'Pampanga; Kapampangan'),
(1, 'ISO639-2_pan', @scm, 'pan', 'Panjabi; Punjabi', 'Panjabi; Punjabi'),
(1, 'ISO639-2_pap', @scm, 'pap', 'Papiamento', 'Papiamento'),
(1, 'ISO639-2_pau', @scm, 'pau', 'Palauan', 'Palauan'),
(1, 'ISO639-2_peo', @scm, 'peo', 'Persian, Old (ca.600-400 B.C.)', 'Persian, Old (ca.600-400 B.C.)'),
(1, 'ISO639-2_per', @scm, 'per', 'Persian', 'Persian'),
(1, 'ISO639-2_phi', @scm, 'phi', 'Philippine languages', 'Philippine languages'),
(1, 'ISO639-2_phn', @scm, 'phn', 'Phoenician', 'Phoenician'),
(1, 'ISO639-2_pli', @scm, 'pli', 'Pali', 'Pali'),
(1, 'ISO639-2_pol', @scm, 'pol', 'Polish', 'Polish'),
(1, 'ISO639-2_pon', @scm, 'pon', 'Pohnpeian', 'Pohnpeian'),
(1, 'ISO639-2_por', @scm, 'por', 'Portuguese', 'Portuguese'),
(1, 'ISO639-2_pra', @scm, 'pra', 'Prakrit languages', 'Prakrit languages'),
(1, 'ISO639-2_pro', @scm, 'pro', 'Provençal, Old (to 1500);Occitan, Old (to 1500)', 'Provençal, Old (to 1500);Occitan, Old (to 1500)'),
(1, 'ISO639-2_pus', @scm, 'pus', 'Pushto; Pashto', 'Pushto; Pashto'),
(1, 'ISO639-2_qaa', @scm, 'qaa', 'QTZ - Reserved for local use', 'QTZ - Reserved for local use'),
(1, 'ISO639-2_que', @scm, 'que', 'Quechua', 'Quechua'),
(1, 'ISO639-2_raj', @scm, 'raj', 'Rajasthani', 'Rajasthani'),
(1, 'ISO639-2_rap', @scm, 'rap', 'Rapanui', 'Rapanui'),
(1, 'ISO639-2_rar', @scm, 'rar', 'Rarotongan; Cook Islands Maori', 'Rarotongan; Cook Islands Maori'),
(1, 'ISO639-2_roa', @scm, 'roa', 'Romance languages', 'Romance languages'),
(1, 'ISO639-2_roh', @scm, 'roh', 'Romansh', 'Romansh'),
(1, 'ISO639-2_rom', @scm, 'rom', 'Romany', 'Romany'),
(1, 'ISO639-2_ron', @scm, 'ron', 'Romanian; Moldavian; Moldovan', 'Romanian; Moldavian; Moldovan'),
(1, 'ISO639-2_rum', @scm, 'rum', 'Romanian; Moldavian; Moldovan', 'Romanian; Moldavian; Moldovan'),
(1, 'ISO639-2_run', @scm, 'run', 'Rundi', 'Rundi'),
(1, 'ISO639-2_rup', @scm, 'rup', 'Aromanian; Arumanian; Macedo-Romanian', 'Aromanian; Arumanian; Macedo-Romanian'),
(1, 'ISO639-2_rus', @scm, 'rus', 'Russian', 'Russian'),
(1, 'ISO639-2_sad', @scm, 'sad', 'Sandawe', 'Sandawe'),
(1, 'ISO639-2_sag', @scm, 'sag', 'Sango', 'Sango'),
(1, 'ISO639-2_sah', @scm, 'sah', 'Yakut', 'Yakut'),
(1, 'ISO639-2_sai', @scm, 'sai', 'South American Indian languages', 'South American Indian languages'),
(1, 'ISO639-2_sal', @scm, 'sal', 'Salishan languages', 'Salishan languages'),
(1, 'ISO639-2_sam', @scm, 'sam', 'Samaritan Aramaic', 'Samaritan Aramaic'),
(1, 'ISO639-2_san', @scm, 'san', 'Sanskrit', 'Sanskrit'),
(1, 'ISO639-2_sas', @scm, 'sas', 'Sasak', 'Sasak'),
(1, 'ISO639-2_sat', @scm, 'sat', 'Santali', 'Santali'),
(1, 'ISO639-2_scn', @scm, 'scn', 'Sicilian', 'Sicilian'),
(1, 'ISO639-2_sco', @scm, 'sco', 'Scots', 'Scots'),
(1, 'ISO639-2_sel', @scm, 'sel', 'Selkup', 'Selkup'),
(1, 'ISO639-2_sem', @scm, 'sem', 'Semitic languages', 'Semitic languages'),
(1, 'ISO639-2_sga', @scm, 'sga', 'Irish, Old (to 900)', 'Irish, Old (to 900)'),
(1, 'ISO639-2_sgn', @scm, 'sgn', 'Sign Languages', 'Sign Languages'),
(1, 'ISO639-2_shn', @scm, 'shn', 'Shan', 'Shan'),
(1, 'ISO639-2_sid', @scm, 'sid', 'Sidamo', 'Sidamo'),
(1, 'ISO639-2_sin', @scm, 'sin', 'Sinhala; Sinhalese', 'Sinhala; Sinhalese'),
(1, 'ISO639-2_sio', @scm, 'sio', 'Siouan languages', 'Siouan languages'),
(1, 'ISO639-2_sit', @scm, 'sit', 'Sino-Tibetan languages', 'Sino-Tibetan languages'),
(1, 'ISO639-2_sla', @scm, 'sla', 'Slavic languages', 'Slavic languages'),
(1, 'ISO639-2_slk', @scm, 'slk', 'Slovak', 'Slovak'),
(1, 'ISO639-2_slo', @scm, 'slo', 'Slovak', 'Slovak'),
(1, 'ISO639-2_slv', @scm, 'slv', 'Slovenian', 'Slovenian'),
(1, 'ISO639-2_sma', @scm, 'sma', 'Southern Sami', 'Southern Sami'),
(1, 'ISO639-2_sme', @scm, 'sme', 'Northern Sami', 'Northern Sami'),
(1, 'ISO639-2_smi', @scm, 'smi', 'Sami languages', 'Sami languages'),
(1, 'ISO639-2_smj', @scm, 'smj', 'Lule Sami', 'Lule Sami'),
(1, 'ISO639-2_smn', @scm, 'smn', 'Inari Sami', 'Inari Sami'),
(1, 'ISO639-2_smo', @scm, 'smo', 'Samoan', 'Samoan'),
(1, 'ISO639-2_sms', @scm, 'sms', 'Skolt Sami', 'Skolt Sami'),
(1, 'ISO639-2_sna', @scm, 'sna', 'Shona', 'Shona'),
(1, 'ISO639-2_snd', @scm, 'snd', 'Sindhi', 'Sindhi'),
(1, 'ISO639-2_snk', @scm, 'snk', 'Soninke', 'Soninke'),
(1, 'ISO639-2_sog', @scm, 'sog', 'Sogdian', 'Sogdian'),
(1, 'ISO639-2_som', @scm, 'som', 'Somali', 'Somali'),
(1, 'ISO639-2_son', @scm, 'son', 'Songhai languages', 'Songhai languages'),
(1, 'ISO639-2_sot', @scm, 'sot', 'Sotho, Southern', 'Sotho, Southern'),
(1, 'ISO639-2_spa', @scm, 'spa', 'Spanish; Castilian', 'Spanish; Castilian'),
(1, 'ISO639-2_sqi', @scm, 'sqi', 'Albanian', 'Albanian'),
(1, 'ISO639-2_srd', @scm, 'srd', 'Sardinian', 'Sardinian'),
(1, 'ISO639-2_srn', @scm, 'srn', 'Sranan Tongo', 'Sranan Tongo'),
(1, 'ISO639-2_srp', @scm, 'srp', 'Serbian', 'Serbian'),
(1, 'ISO639-2_srr', @scm, 'srr', 'Serer', 'Serer'),
(1, 'ISO639-2_ssa', @scm, 'ssa', 'Nilo-Saharan languages', 'Nilo-Saharan languages'),
(1, 'ISO639-2_ssw', @scm, 'ssw', 'Swati', 'Swati'),
(1, 'ISO639-2_suk', @scm, 'suk', 'Sukuma', 'Sukuma'),
(1, 'ISO639-2_sun', @scm, 'sun', 'Sundanese', 'Sundanese'),
(1, 'ISO639-2_sus', @scm, 'sus', 'Susu', 'Susu'),
(1, 'ISO639-2_sux', @scm, 'sux', 'Sumerian', 'Sumerian'),
(1, 'ISO639-2_swa', @scm, 'swa', 'Swahili', 'Swahili'),
(1, 'ISO639-2_swe', @scm, 'swe', 'Swedish', 'Swedish'),
(1, 'ISO639-2_syc', @scm, 'syc', 'Classical Syriac', 'Classical Syriac'),
(1, 'ISO639-2_syr', @scm, 'syr', 'Syriac', 'Syriac'),
(1, 'ISO639-2_tah', @scm, 'tah', 'Tahitian', 'Tahitian'),
(1, 'ISO639-2_tai', @scm, 'tai', 'Tai languages', 'Tai languages'),
(1, 'ISO639-2_tam', @scm, 'tam', 'Tamil', 'Tamil'),
(1, 'ISO639-2_tat', @scm, 'tat', 'Tatar', 'Tatar'),
(1, 'ISO639-2_tel', @scm, 'tel', 'Telugu', 'Telugu'),
(1, 'ISO639-2_tem', @scm, 'tem', 'Timne', 'Timne'),
(1, 'ISO639-2_ter', @scm, 'ter', 'Tereno', 'Tereno'),
(1, 'ISO639-2_tet', @scm, 'tet', 'Tetum', 'Tetum'),
(1, 'ISO639-2_tgk', @scm, 'tgk', 'Tajik', 'Tajik'),
(1, 'ISO639-2_tgl', @scm, 'tgl', 'Tagalog', 'Tagalog'),
(1, 'ISO639-2_tha', @scm, 'tha', 'Thai', 'Thai'),
(1, 'ISO639-2_tib', @scm, 'tib', 'Tibetan', 'Tibetan'),
(1, 'ISO639-2_tig', @scm, 'tig', 'Tigre', 'Tigre'),
(1, 'ISO639-2_tir', @scm, 'tir', 'Tigrinya', 'Tigrinya'),
(1, 'ISO639-2_tiv', @scm, 'tiv', 'Tiv', 'Tiv'),
(1, 'ISO639-2_tkl', @scm, 'tkl', 'Tokelau', 'Tokelau'),
(1, 'ISO639-2_tlh', @scm, 'tlh', 'Klingon; tlhIngan-Hol', 'Klingon; tlhIngan-Hol'),
(1, 'ISO639-2_tli', @scm, 'tli', 'Tlingit', 'Tlingit'),
(1, 'ISO639-2_tmh', @scm, 'tmh', 'Tamashek', 'Tamashek'),
(1, 'ISO639-2_tog', @scm, 'tog', 'Tonga (Nyasa)', 'Tonga (Nyasa)'),
(1, 'ISO639-2_ton', @scm, 'ton', 'Tonga (Tonga Islands)', 'Tonga (Tonga Islands)'),
(1, 'ISO639-2_tpi', @scm, 'tpi', 'Tok Pisin', 'Tok Pisin'),
(1, 'ISO639-2_tsi', @scm, 'tsi', 'Tsimshian', 'Tsimshian'),
(1, 'ISO639-2_tsn', @scm, 'tsn', 'Tswana', 'Tswana'),
(1, 'ISO639-2_tso', @scm, 'tso', 'Tsonga', 'Tsonga'),
(1, 'ISO639-2_tuk', @scm, 'tuk', 'Turkmen', 'Turkmen'),
(1, 'ISO639-2_tum', @scm, 'tum', 'Tumbuka', 'Tumbuka'),
(1, 'ISO639-2_tup', @scm, 'tup', 'Tupi languages', 'Tupi languages'),
(1, 'ISO639-2_tur', @scm, 'tur', 'Turkish', 'Turkish'),
(1, 'ISO639-2_tut', @scm, 'tut', 'Altaic languages', 'Altaic languages'),
(1, 'ISO639-2_tvl', @scm, 'tvl', 'Tuvalu', 'Tuvalu'),
(1, 'ISO639-2_twi', @scm, 'twi', 'Twi', 'Twi'),
(1, 'ISO639-2_tyv', @scm, 'tyv', 'Tuvinian', 'Tuvinian'),
(1, 'ISO639-2_udm', @scm, 'udm', 'Udmurt', 'Udmurt'),
(1, 'ISO639-2_uga', @scm, 'uga', 'Ugaritic', 'Ugaritic'),
(1, 'ISO639-2_uig', @scm, 'uig', 'Uighur; Uyghur', 'Uighur; Uyghur'),
(1, 'ISO639-2_ukr', @scm, 'ukr', 'Ukrainian', 'Ukrainian'),
(1, 'ISO639-2_umb', @scm, 'umb', 'Umbundu', 'Umbundu'),
(1, 'ISO639-2_und', @scm, 'und', 'Undetermined', 'Undetermined'),
(1, 'ISO639-2_urd', @scm, 'urd', 'Urdu', 'Urdu'),
(1, 'ISO639-2_uzb', @scm, 'uzb', 'Uzbek', 'Uzbek'),
(1, 'ISO639-2_vai', @scm, 'vai', 'Vai', 'Vai'),
(1, 'ISO639-2_ven', @scm, 'ven', 'Venda', 'Venda'),
(1, 'ISO639-2_vie', @scm, 'vie', 'Vietnamese', 'Vietnamese'),
(1, 'ISO639-2_vol', @scm, 'vol', 'Volapük', 'Volapük'),
(1, 'ISO639-2_vot', @scm, 'vot', 'Votic', 'Votic'),
(1, 'ISO639-2_wak', @scm, 'wak', 'Wakashan languages', 'Wakashan languages'),
(1, 'ISO639-2_wal', @scm, 'wal', 'Wolaitta; Wolaytta', 'Wolaitta; Wolaytta'),
(1, 'ISO639-2_war', @scm, 'war', 'Waray', 'Waray'),
(1, 'ISO639-2_was', @scm, 'was', 'Washo', 'Washo'),
(1, 'ISO639-2_wel', @scm, 'wel', 'Welsh', 'Welsh'),
(1, 'ISO639-2_wen', @scm, 'wen', 'Sorbian languages', 'Sorbian languages'),
(1, 'ISO639-2_wln', @scm, 'wln', 'Walloon', 'Walloon'),
(1, 'ISO639-2_wol', @scm, 'wol', 'Wolof', 'Wolof'),
(1, 'ISO639-2_xal', @scm, 'xal', 'Kalmyk; Oirat', 'Kalmyk; Oirat'),
(1, 'ISO639-2_xho', @scm, 'xho', 'Xhosa', 'Xhosa'),
(1, 'ISO639-2_yao', @scm, 'yao', 'Yao', 'Yao'),
(1, 'ISO639-2_yap', @scm, 'yap', 'Yapese', 'Yapese'),
(1, 'ISO639-2_yid', @scm, 'yid', 'Yiddish', 'Yiddish'),
(1, 'ISO639-2_yor', @scm, 'yor', 'Yoruba', 'Yoruba'),
(1, 'ISO639-2_ypk', @scm, 'ypk', 'Yupik languages', 'Yupik languages'),
(1, 'ISO639-2_zap', @scm, 'zap', 'Zapotec', 'Zapotec'),
(1, 'ISO639-2_zbl', @scm, 'zbl', 'Blissymbols; Blissymbolics; Bliss', 'Blissymbols; Blissymbolics; Bliss'),
(1, 'ISO639-2_zen', @scm, 'zen', 'Zenaga', 'Zenaga'),
(1, 'ISO639-2_zgh', @scm, 'zgh', 'Standard Moroccan Tamazight', 'Standard Moroccan Tamazight'),
(1, 'ISO639-2_zha', @scm, 'zha', 'Zhuang; Chuang', 'Zhuang; Chuang'),
(1, 'ISO639-2_zho', @scm, 'zho', 'Chinese', 'Chinese'),
(1, 'ISO639-2_znd', @scm, 'znd', 'Zande languages', 'Zande languages'),
(1, 'ISO639-2_zul', @scm, 'zul', 'Zulu', 'Zulu'),
(1, 'ISO639-2_zun', @scm, 'zun', 'Zuni', 'Zuni'),
(1, 'ISO639-2_zxx', @scm, 'zxx', 'No linguistic content; Not applicable', 'No linguistic content; Not applicable'),
(1, 'ISO639-2_zza', @scm, 'zza', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki');
