-- Ensure core code scheme exists
INSERT IGNORE INTO concept (document, id, name, description)
VALUES (1, 'CM_DiscoveryCode', 'Discovery code', 'Discovery (core) coding scheme ');

-- Get scheme id
SELECT @scm := dbid FROM concept WHERE id = 'CM_DiscoveryCode';

-- Ensure NHS DD scheme exists --
INSERT IGNORE INTO concept (document, id, scheme, code, name, description)
VALUES (1, 'CM_NHS_DD', @scm, 'CM_NHS_DD', 'NHS Data Dictionary', 'NHS Data Dictionary coding scheme');

-- Code scheme prefix entries
INSERT IGNORE INTO concept_property_data
(`dbid`, `group`, `property`, `value`)
SELECT c.dbid, 0 AS `group`, p.dbid AS `property`, '' AS `value`
FROM concept c
JOIN concept p ON p.id = 'code_prefix'
WHERE c.id IN ('CM_DiscoveryCode', 'CM_NHS_DD');

-- RELIGION CONCEPTS --  https://datadictionary.nhs.uk/attributes/religious_or_other_belief_system_affiliation_code.html
INSERT IGNORE INTO concept (document, id, scheme, code, name, description)
VALUES
(1, 'DM_religion', @scm, 'DM_religion', 'Religion', 'Religion'),
(1, 'CM_ReligionD1', @scm, 'CM_ReligionD1', 'Hindu', 'Hindu'),
(1, 'CM_ReligionK20', @scm, 'CM_ReligionK20', 'Religion (other not listed)', 'Religion (other not listed)'),
(1, 'CM_ReligionI1', @scm, 'CM_ReligionI1', 'Sikh', 'Sikh'),
(1, 'CM_ReligionA1', @scm, 'CM_ReligionA1', 'Baha''i', 'Baha''i'),
(1, 'CM_ReligionB1', @scm, 'CM_ReligionB1', 'Buddhist', 'Buddhist'),
(1, 'CM_ReligionC1', @scm, 'CM_ReligionC1', 'Christian', 'Christian'),
(1, 'CM_ReligionM1', @scm, 'CM_ReligionM1', 'Religion not given – patient refused', 'Religion not given – patient refused'),
(1, 'CM_ReligionE1', @scm, 'CM_ReligionE1', 'Jain', 'Jain'),
(1, 'CM_ReligionF1', @scm, 'CM_ReligionF1', 'Jewish', 'Jewish'),
(1, 'CM_ReligionG1', @scm, 'CM_ReligionG1', 'Muslim', 'Muslim'),
(1, 'CM_ReligionL2', @scm, 'CM_ReligionL2', 'Not religious', 'Not religious'),
(1, 'CM_ReligionH1', @scm, 'CM_ReligionH1', 'Pagan', 'Pagan'),
(1, 'CM_ReligionN1', @scm, 'CM_ReligionN1', 'Patient religion unknown', 'Patient religion unknown'),
(1, 'CM_ReligionJ1', @scm, 'CM_ReligionJ1', 'Zoroastrian', 'Zoroastrian'),
(1, 'CM_ReligionB2', @scm, 'CM_ReligionB2', 'Mahayana Buddhist', 'Mahayana Buddhist'),
(1, 'CM_ReligionB3', @scm, 'CM_ReligionB3', 'New Kadampa Tradition Buddhist', 'New Kadampa Tradition Buddhist'),
(1, 'CM_ReligionB4', @scm, 'CM_ReligionB4', 'Nichiren Buddhist', 'Nichiren Buddhist'),
(1, 'CM_ReligionB5', @scm, 'CM_ReligionB5', 'Pure Land Buddhist', 'Pure Land Buddhist'),
(1, 'CM_ReligionB6', @scm, 'CM_ReligionB6', 'Theravada Buddhist', 'Theravada Buddhist'),
(1, 'CM_ReligionB7', @scm, 'CM_ReligionB7', 'Tibetan Buddhist', 'Tibetan Buddhist'),
(1, 'CM_ReligionB8', @scm, 'CM_ReligionB8', 'Zen Buddhist', 'Zen Buddhist'),
(1, 'CM_ReligionC2', @scm, 'CM_ReligionC2', 'Amish', 'Amish'),
(1, 'CM_ReligionC3', @scm, 'CM_ReligionC3', 'Anabaptist', 'Anabaptist'),
(1, 'CM_ReligionC4', @scm, 'CM_ReligionC4', 'Anglican', 'Anglican'),
(1, 'CM_ReligionC5', @scm, 'CM_ReligionC5', 'Apostolic Pentecostalist', 'Apostolic Pentecostalist'),
(1, 'CM_ReligionC6', @scm, 'CM_ReligionC6', 'Armenian Catholic', 'Armenian Catholic'),
(1, 'CM_ReligionC7', @scm, 'CM_ReligionC7', 'Armenian Orthodox', 'Armenian Orthodox'),
(1, 'CM_ReligionC8', @scm, 'CM_ReligionC8', 'Baptist', 'Baptist'),
(1, 'CM_ReligionC9', @scm, 'CM_ReligionC9', 'Brethren', 'Brethren'),
(1, 'CM_ReligionC10', @scm, 'CM_ReligionC10', 'Bulgarian Orthodox', 'Bulgarian Orthodox'),
(1, 'CM_ReligionC11', @scm, 'CM_ReligionC11', 'Calvinist', 'Calvinist'),
(1, 'CM_ReligionC12', @scm, 'CM_ReligionC12', 'Catholic: Not Roman Catholic', 'Catholic: Not Roman Catholic'),
(1, 'CM_ReligionC13', @scm, 'CM_ReligionC13', 'Celtic Christian', 'Celtic Christian'),
(1, 'CM_ReligionC14', @scm, 'CM_ReligionC14', 'Celtic Orthodox Christian', 'Celtic Orthodox Christian'),
(1, 'CM_ReligionC15', @scm, 'CM_ReligionC15', 'Chinese Evangelical Christian', 'Chinese Evangelical Christian'),
(1, 'CM_ReligionC16', @scm, 'CM_ReligionC16', 'Christadelphian', 'Christadelphian'),
(1, 'CM_ReligionC17', @scm, 'CM_ReligionC17', 'Christian Existentialist', 'Christian Existentialist'),
(1, 'CM_ReligionC18', @scm, 'CM_ReligionC18', 'Christian Humanist', 'Christian Humanist'),
(1, 'CM_ReligionC19', @scm, 'CM_ReligionC19', 'Christian Scientists', 'Christian Scientists'),
(1, 'CM_ReligionC20', @scm, 'CM_ReligionC20', 'Christian Spiritualist', 'Christian Spiritualist'),
(1, 'CM_ReligionC21', @scm, 'CM_ReligionC21', 'Church in Wales', 'Church in Wales'),
(1, 'CM_ReligionC22', @scm, 'CM_ReligionC22', 'Church of England', 'Church of England'),
(1, 'CM_ReligionC23', @scm, 'CM_ReligionC23', 'Church of God of Prophecy', 'Church of God of Prophecy'),
(1, 'CM_ReligionC24', @scm, 'CM_ReligionC24', 'Church of Ireland', 'Church of Ireland'),
(1, 'CM_ReligionC25', @scm, 'CM_ReligionC25', 'Church of Scotland', 'Church of Scotland'),
(1, 'CM_ReligionC26', @scm, 'CM_ReligionC26', 'Congregationalist', 'Congregationalist'),
(1, 'CM_ReligionC27', @scm, 'CM_ReligionC27', 'Coptic Orthodox', 'Coptic Orthodox'),
(1, 'CM_ReligionC28', @scm, 'CM_ReligionC28', 'Eastern Catholic', 'Eastern Catholic'),
(1, 'CM_ReligionC29', @scm, 'CM_ReligionC29', 'Eastern Orthodox', 'Eastern Orthodox'),
(1, 'CM_ReligionC30', @scm, 'CM_ReligionC30', 'Elim Pentecostalist', 'Elim Pentecostalist'),
(1, 'CM_ReligionC31', @scm, 'CM_ReligionC31', 'Ethiopian Orthodox', 'Ethiopian Orthodox'),
(1, 'CM_ReligionC32', @scm, 'CM_ReligionC32', 'Evangelical Christian', 'Evangelical Christian'),
(1, 'CM_ReligionC33', @scm, 'CM_ReligionC33', 'Exclusive Brethren', 'Exclusive Brethren'),
(1, 'CM_ReligionC34', @scm, 'CM_ReligionC34', 'Free Church', 'Free Church'),
(1, 'CM_ReligionC35', @scm, 'CM_ReligionC35', 'Free Church of Scotland', 'Free Church of Scotland'),
(1, 'CM_ReligionC36', @scm, 'CM_ReligionC36', 'Free Evangelical Presbyterian', 'Free Evangelical Presbyterian'),
(1, 'CM_ReligionC37', @scm, 'CM_ReligionC37', 'Free Methodist', 'Free Methodist'),
(1, 'CM_ReligionC38', @scm, 'CM_ReligionC38', 'Free Presbyterian', 'Free Presbyterian'),
(1, 'CM_ReligionC39', @scm, 'CM_ReligionC39', 'French Protestant', 'French Protestant'),
(1, 'CM_ReligionC40', @scm, 'CM_ReligionC40', 'Greek Catholic', 'Greek Catholic'),
(1, 'CM_ReligionC41', @scm, 'CM_ReligionC41', 'Greek Orthodox', 'Greek Orthodox'),
(1, 'CM_ReligionC42', @scm, 'CM_ReligionC42', 'Independent Methodist', 'Independent Methodist'),
(1, 'CM_ReligionC43', @scm, 'CM_ReligionC43', 'Indian Orthodox', 'Indian Orthodox'),
(1, 'CM_ReligionC44', @scm, 'CM_ReligionC44', 'Jehovah''s Witness', 'Jehovah''s Witness'),
(1, 'CM_ReligionC45', @scm, 'CM_ReligionC45', 'Judaic Christian', 'Judaic Christian'),
(1, 'CM_ReligionC46', @scm, 'CM_ReligionC46', 'Lutheran', 'Lutheran'),
(1, 'CM_ReligionC47', @scm, 'CM_ReligionC47', 'Mennonite', 'Mennonite'),
(1, 'CM_ReligionC48', @scm, 'CM_ReligionC48', 'Messianic Jew', 'Messianic Jew'),
(1, 'CM_ReligionC49', @scm, 'CM_ReligionC49', 'Methodist', 'Methodist'),
(1, 'CM_ReligionC50', @scm, 'CM_ReligionC50', 'Moravian', 'Moravian'),
(1, 'CM_ReligionC51', @scm, 'CM_ReligionC51', 'Mormon', 'Mormon'),
(1, 'CM_ReligionC52', @scm, 'CM_ReligionC52', 'Nazarene Church Synonym: Nazarene', 'Nazarene Church Synonym: Nazarene'),
(1, 'CM_ReligionC53', @scm, 'CM_ReligionC53', 'New Testament Pentacostalist', 'New Testament Pentacostalist'),
(1, 'CM_ReligionC54', @scm, 'CM_ReligionC54', 'Nonconformist', 'Nonconformist'),
(1, 'CM_ReligionC55', @scm, 'CM_ReligionC55', 'Old Catholic', 'Old Catholic'),
(1, 'CM_ReligionC56', @scm, 'CM_ReligionC56', 'Open Brethren', 'Open Brethren'),
(1, 'CM_ReligionC57', @scm, 'CM_ReligionC57', 'Orthodox Christian', 'Orthodox Christian'),
(1, 'CM_ReligionC58', @scm, 'CM_ReligionC58', 'Pentecostalist Synonym: Pentacostal Christian', 'Pentecostalist Synonym: Pentacostal Christian'),
(1, 'CM_ReligionC59', @scm, 'CM_ReligionC59', 'Presbyterian', 'Presbyterian'),
(1, 'CM_ReligionC60', @scm, 'CM_ReligionC60', 'Protestant', 'Protestant'),
(1, 'CM_ReligionC61', @scm, 'CM_ReligionC61', 'Plymouth Brethren', 'Plymouth Brethren'),
(1, 'CM_ReligionC62', @scm, 'CM_ReligionC62', 'Quaker', 'Quaker'),
(1, 'CM_ReligionC63', @scm, 'CM_ReligionC63', 'Rastafari', 'Rastafari'),
(1, 'CM_ReligionC64', @scm, 'CM_ReligionC64', 'Reformed Christian', 'Reformed Christian'),
(1, 'CM_ReligionC65', @scm, 'CM_ReligionC65', 'Reformed Presbyterian', 'Reformed Presbyterian'),
(1, 'CM_ReligionC66', @scm, 'CM_ReligionC66', 'Reformed Protestant', 'Reformed Protestant'),
(1, 'CM_ReligionC67', @scm, 'CM_ReligionC67', 'Roman Catholic', 'Roman Catholic'),
(1, 'CM_ReligionC68', @scm, 'CM_ReligionC68', 'Romanian Orthodox', 'Romanian Orthodox'),
(1, 'CM_ReligionC69', @scm, 'CM_ReligionC69', 'Russian Orthodox', 'Russian Orthodox'),
(1, 'CM_ReligionC70', @scm, 'CM_ReligionC70', 'Salvation Army Member', 'Salvation Army Member'),
(1, 'CM_ReligionC71', @scm, 'CM_ReligionC71', 'Scottish Episcopalian', 'Scottish Episcopalian'),
(1, 'CM_ReligionC72', @scm, 'CM_ReligionC72', 'Serbian Orthodox', 'Serbian Orthodox'),
(1, 'CM_ReligionC73', @scm, 'CM_ReligionC73', 'Seventh Day Adventist', 'Seventh Day Adventist'),
(1, 'CM_ReligionC74', @scm, 'CM_ReligionC74', 'Syrian Orthodox', 'Syrian Orthodox'),
(1, 'CM_ReligionC75', @scm, 'CM_ReligionC75', 'Ukrainian Catholic', 'Ukrainian Catholic'),
(1, 'CM_ReligionC76', @scm, 'CM_ReligionC76', 'Ukrainian Orthodox', 'Ukrainian Orthodox'),
(1, 'CM_ReligionC77', @scm, 'CM_ReligionC77', 'Uniate Catholic', 'Uniate Catholic'),
(1, 'CM_ReligionC78', @scm, 'CM_ReligionC78', 'Unitarian', 'Unitarian'),
(1, 'CM_ReligionC79', @scm, 'CM_ReligionC79', 'United Reform', 'United Reform'),
(1, 'CM_ReligionC80', @scm, 'CM_ReligionC80', 'Zwinglian', 'Zwinglian'),
(1, 'CM_ReligionD1', @scm, 'CM_ReligionD1', 'Hindu', 'Hindu'),
(1, 'CM_ReligionD2', @scm, 'CM_ReligionD2', 'Advaitin Hindu', 'Advaitin Hindu'),
(1, 'CM_ReligionD3', @scm, 'CM_ReligionD3', 'Arya Samaj Hindu', 'Arya Samaj Hindu'),
(1, 'CM_ReligionD4', @scm, 'CM_ReligionD4', 'Shakti Hindu', 'Shakti Hindu'),
(1, 'CM_ReligionD5', @scm, 'CM_ReligionD5', 'Shiva Hindu', 'Shiva Hindu'),
(1, 'CM_ReligionD6', @scm, 'CM_ReligionD6', 'Vaishnava Hindu Synonym: Hare Krishna', 'Vaishnava Hindu Synonym: Hare Krishna'),
(1, 'CM_ReligionF2', @scm, 'CM_ReligionF2', 'Ashkenazi Jew', 'Ashkenazi Jew'),
(1, 'CM_ReligionF3', @scm, 'CM_ReligionF3', 'Haredi Jew', 'Haredi Jew'),
(1, 'CM_ReligionF4', @scm, 'CM_ReligionF4', 'Hasidic Jew', 'Hasidic Jew'),
(1, 'CM_ReligionF5', @scm, 'CM_ReligionF5', 'Liberal Jew', 'Liberal Jew'),
(1, 'CM_ReligionF6', @scm, 'CM_ReligionF6', 'Masorti Jew', 'Masorti Jew'),
(1, 'CM_ReligionF7', @scm, 'CM_ReligionF7', 'Orthodox Jew', 'Orthodox Jew'),
(1, 'CM_ReligionF8', @scm, 'CM_ReligionF8', 'Reform Jew', 'Reform Jew'),
(1, 'CM_ReligionG2', @scm, 'CM_ReligionG2', 'Ahmadi', 'Ahmadi'),
(1, 'CM_ReligionG3', @scm, 'CM_ReligionG3', 'Druze', 'Druze'),
(1, 'CM_ReligionG4', @scm, 'CM_ReligionG4', 'Ismaili Muslim', 'Ismaili Muslim'),
(1, 'CM_ReligionG5', @scm, 'CM_ReligionG5', 'Shi''ite Muslim', 'Shi''ite Muslim'),
(1, 'CM_ReligionG6', @scm, 'CM_ReligionG6', 'Sunni Muslim', 'Sunni Muslim'),
(1, 'CM_ReligionH2', @scm, 'CM_ReligionH2', 'Asatruar', 'Asatruar'),
(1, 'CM_ReligionH3', @scm, 'CM_ReligionH3', 'Celtic Pagan', 'Celtic Pagan'),
(1, 'CM_ReligionH4', @scm, 'CM_ReligionH4', 'Druid', 'Druid'),
(1, 'CM_ReligionH5', @scm, 'CM_ReligionH5', 'Goddess', 'Goddess'),
(1, 'CM_ReligionH6', @scm, 'CM_ReligionH6', 'Heathen', 'Heathen'),
(1, 'CM_ReligionH7', @scm, 'CM_ReligionH7', 'Occultist', 'Occultist'),
(1, 'CM_ReligionH8', @scm, 'CM_ReligionH8', 'Shaman', 'Shaman'),
(1, 'CM_ReligionH9', @scm, 'CM_ReligionH9', 'Wiccan', 'Wiccan'),
(1, 'CM_ReligionK1', @scm, 'CM_ReligionK1', 'Agnostic', 'Agnostic'),
(1, 'CM_ReligionK2', @scm, 'CM_ReligionK2', 'Ancestral Worship', 'Ancestral Worship'),
(1, 'CM_ReligionK3', @scm, 'CM_ReligionK3', 'Animist', 'Animist'),
(1, 'CM_ReligionK4', @scm, 'CM_ReligionK4', 'Anthroposophist', 'Anthroposophist'),
(1, 'CM_ReligionK5', @scm, 'CM_ReligionK5', 'Black Magic', 'Black Magic'),
(1, 'CM_ReligionK6', @scm, 'CM_ReligionK6', 'Brahma Kumari', 'Brahma Kumari'),
(1, 'CM_ReligionK7', @scm, 'CM_ReligionK7', 'British Israelite', 'British Israelite'),
(1, 'CM_ReligionK8', @scm, 'CM_ReligionK8', 'Chondogyo', 'Chondogyo'),
(1, 'CM_ReligionK9', @scm, 'CM_ReligionK9', 'Confucianist', 'Confucianist'),
(1, 'CM_ReligionK10', @scm, 'CM_ReligionK10', 'Deist', 'Deist'),
(1, 'CM_ReligionK11', @scm, 'CM_ReligionK11', 'Humanist', 'Humanist'),
(1, 'CM_ReligionK12', @scm, 'CM_ReligionK12', 'Infinite Way', 'Infinite Way'),
(1, 'CM_ReligionK13', @scm, 'CM_ReligionK13', 'Kabbalist', 'Kabbalist'),
(1, 'CM_ReligionK14', @scm, 'CM_ReligionK14', 'Lightworker', 'Lightworker'),
(1, 'CM_ReligionK15', @scm, 'CM_ReligionK15', 'New Age Practitioner', 'New Age Practitioner'),
(1, 'CM_ReligionK16', @scm, 'CM_ReligionK16', 'Native American Religion', 'Native American Religion'),
(1, 'CM_ReligionK17', @scm, 'CM_ReligionK17', 'Pantheist', 'Pantheist'),
(1, 'CM_ReligionK18', @scm, 'CM_ReligionK18', 'Peyotist', 'Peyotist'),
(1, 'CM_ReligionK19', @scm, 'CM_ReligionK19', 'Radha Soami Synonym: Sant Mat', 'Radha Soami Synonym: Sant Mat'),
(1, 'CM_ReligionK21', @scm, 'CM_ReligionK21', 'Santeri', 'Santeri'),
(1, 'CM_ReligionK22', @scm, 'CM_ReligionK22', 'Satanist', 'Satanist'),
(1, 'CM_ReligionK23', @scm, 'CM_ReligionK23', 'Scientologist', 'Scientologist'),
(1, 'CM_ReligionK24', @scm, 'CM_ReligionK24', 'Secularist', 'Secularist'),
(1, 'CM_ReligionK25', @scm, 'CM_ReligionK25', 'Shumei', 'Shumei'),
(1, 'CM_ReligionK26', @scm, 'CM_ReligionK26', 'Shinto', 'Shinto'),
(1, 'CM_ReligionK27', @scm, 'CM_ReligionK27', 'Spiritualist', 'Spiritualist'),
(1, 'CM_ReligionK28', @scm, 'CM_ReligionK28', 'Swedenborgian Synonym: Neo-Christian', 'Swedenborgian Synonym: Neo-Christian'),
(1, 'CM_ReligionK29', @scm, 'CM_ReligionK29', 'Taoist', 'Taoist'),
(1, 'CM_ReligionK30', @scm, 'CM_ReligionK30', 'Unitarian-Universalist', 'Unitarian-Universalist'),
(1, 'CM_ReligionK31', @scm, 'CM_ReligionK31', 'Universalist', 'Universalist'),
(1, 'CM_ReligionK32', @scm, 'CM_ReligionK32', 'Vodun', 'Vodun'),
(1, 'CM_ReligionK33', @scm, 'CM_ReligionK33', 'Yoruba', 'Yoruba'),
(1, 'CM_ReligionL1', @scm, 'CM_ReligionL1', 'Atheist', 'Atheist');
