-- Ensure core code scheme exists
INSERT IGNORE INTO concept (document, id, name, description)
VALUES (1, 'CM_DiscoveryCode', 'Discovery code', 'Discovery (core) coding scheme ');

-- Get scheme id
SELECT @scm := dbid FROM concept WHERE id = 'CM_DiscoveryCode';

-- Ensure NHS DD scheme exists --
INSERT IGNORE INTO concept (document, id, scheme, code, name, description)
VALUES (1, 'CM_NHS_DD', @scm, 'CM_NHS_DD', 'NHS Data Dictionary', 'NHS Data Dictionary coding scheme');

-- Code scheme prefix entries
INSERT IGNORE INTO concept_property_data
(`dbid`, `group`, `property`, `value`)
SELECT c.dbid, 0 AS `group`, p.dbid AS `property`, '' AS `value`
FROM concept c
JOIN concept p ON p.id = 'code_prefix'
WHERE c.id IN ('CM_DiscoveryCode', 'CM_NHS_DD');

-- TREATMENT FUNCTION -- https://datadictionary.nhs.uk/attributes/treatment_function_code.html
-- MAIN SPECIALTY    -- https://www.datadictionary.nhs.uk/supporting_information/main_specialty_and_treatment_function_codes_table.html
INSERT IGNORE INTO concept (document, id, scheme, code, name, description)
VALUES
(1, 'DM_treatmentFunctionAdmit', @scm, 'DM_treatmentFunctionAdmit', 'Treatment function', 'Treatment function code'),
(1, 'CM_TrtmntFnc100', @scm, 'CM_TrtmntFnc100', 'General Surgery Service', 'General Surgery Service'),
(1, 'CM_TrtmntFnc101', @scm, 'CM_TrtmntFnc101', 'Urology Service', 'Urology Service'),
(1, 'CM_TrtmntFnc102', @scm, 'CM_TrtmntFnc102', 'Transplant Surgery Service', 'Transplant Surgery Service'),
(1, 'CM_TrtmntFnc103', @scm, 'CM_TrtmntFnc103', 'Breast Surgery Service', 'Breast Surgery Service'),
(1, 'CM_TrtmntFnc104', @scm, 'CM_TrtmntFnc104', 'Colorectal Surgery Service', 'Colorectal Surgery Service'),
(1, 'CM_TrtmntFnc105', @scm, 'CM_TrtmntFnc105', 'Hepatobiliary and Pancreatic Surgery Service', 'Hepatobiliary and Pancreatic Surgery Service'),
(1, 'CM_TrtmntFnc106', @scm, 'CM_TrtmntFnc106', 'Upper Gastrointestinal Surgery Service', 'Upper Gastrointestinal Surgery Service'),
(1, 'CM_TrtmntFnc107', @scm, 'CM_TrtmntFnc107', 'Vascular Surgery Service', 'Vascular Surgery Service'),
(1, 'CM_TrtmntFnc108', @scm, 'CM_TrtmntFnc108', 'Spinal Surgery Service', 'Spinal Surgery Service'),
(1, 'CM_TrtmntFnc109', @scm, 'CM_TrtmntFnc109', 'Bariatric Surgery Service', 'Bariatric Surgery Service'),
(1, 'CM_TrtmntFnc110', @scm, 'CM_TrtmntFnc110', 'Trauma and Orthopaedic Service', 'Trauma and Orthopaedic Service'),
(1, 'CM_TrtmntFnc111', @scm, 'CM_TrtmntFnc111', 'Orthopaedic Service', 'Orthopaedic Service'),
(1, 'CM_TrtmntFnc113', @scm, 'CM_TrtmntFnc113', 'Endocrine Surgery Service', 'Endocrine Surgery Service'),
(1, 'CM_TrtmntFnc115', @scm, 'CM_TrtmntFnc115', 'Trauma Surgery Service', 'Trauma Surgery Service'),
(1, 'CM_TrtmntFnc120', @scm, 'CM_TrtmntFnc120', 'Ear Nose and Throat Service', 'Ear Nose and Throat Service'),
(1, 'CM_TrtmntFnc130', @scm, 'CM_TrtmntFnc130', 'Ophthalmology Service', 'Ophthalmology Service'),
(1, 'CM_TrtmntFnc140', @scm, 'CM_TrtmntFnc140', 'Oral Surgery Service', 'Oral Surgery Service'),
(1, 'CM_TrtmntFnc141', @scm, 'CM_TrtmntFnc141', 'Restorative Dentistry Service', 'Restorative Dentistry Service'),
(1, 'CM_TrtmntFnc143', @scm, 'CM_TrtmntFnc143', 'Orthodontic Service', 'Orthodontic Service'),
(1, 'CM_TrtmntFnc144', @scm, 'CM_TrtmntFnc144', 'Maxillofacial Surgery Service', 'Maxillofacial Surgery Service'),
(1, 'CM_TrtmntFnc145', @scm, 'CM_TrtmntFnc145', 'Oral and Maxillofacial Surgery Service', 'Oral and Maxillofacial Surgery Service'),
(1, 'CM_TrtmntFnc150', @scm, 'CM_TrtmntFnc150', 'Neurosurgical Service', 'Neurosurgical Service'),
(1, 'CM_TrtmntFnc160', @scm, 'CM_TrtmntFnc160', 'Plastic Surgery Service', 'Plastic Surgery Service'),
(1, 'CM_TrtmntFnc161', @scm, 'CM_TrtmntFnc161', 'Burns Care Service', 'Burns Care Service'),
(1, 'CM_TrtmntFnc170', @scm, 'CM_TrtmntFnc170', 'Cardiothoracic Surgery Service', 'Cardiothoracic Surgery Service'),
(1, 'CM_TrtmntFnc172', @scm, 'CM_TrtmntFnc172', 'Cardiac Surgery Service', 'Cardiac Surgery Service'),
(1, 'CM_TrtmntFnc173', @scm, 'CM_TrtmntFnc173', 'Thoracic Surgery Service', 'Thoracic Surgery Service'),
(1, 'CM_TrtmntFnc174', @scm, 'CM_TrtmntFnc174', 'Cardiothoracic Transplantation Service', 'Cardiothoracic Transplantation Service'),
(1, 'CM_TrtmntFnc191', @scm, 'CM_TrtmntFnc191', 'Pain Management Service', 'Pain Management Service'),
(1, 'CM_TrtmntFnc142', @scm, 'CM_TrtmntFnc142', 'Paediatric Dentistry Service', 'Paediatric Dentistry Service'),
(1, 'CM_TrtmntFnc171', @scm, 'CM_TrtmntFnc171', 'Paediatric Surgery Service', 'Paediatric Surgery Service'),
(1, 'CM_TrtmntFnc211', @scm, 'CM_TrtmntFnc211', 'Paediatric Urology Service', 'Paediatric Urology Service'),
(1, 'CM_TrtmntFnc212', @scm, 'CM_TrtmntFnc212', 'Paediatric Transplantation Surgery Service', 'Paediatric Transplantation Surgery Service'),
(1, 'CM_TrtmntFnc213', @scm, 'CM_TrtmntFnc213', 'Paediatric Gastrointestinal Surgery Service', 'Paediatric Gastrointestinal Surgery Service'),
(1, 'CM_TrtmntFnc214', @scm, 'CM_TrtmntFnc214', 'Paediatric Trauma and Orthopaedic Service', 'Paediatric Trauma and Orthopaedic Service'),
(1, 'CM_TrtmntFnc215', @scm, 'CM_TrtmntFnc215', 'Paediatric Ear Nose and Throat Service', 'Paediatric Ear Nose and Throat Service'),
(1, 'CM_TrtmntFnc216', @scm, 'CM_TrtmntFnc216', 'Paediatric Ophthalmology Service', 'Paediatric Ophthalmology Service'),
(1, 'CM_TrtmntFnc217', @scm, 'CM_TrtmntFnc217', 'Paediatric Oral and Maxillofacial Surgery Service', 'Paediatric Oral and Maxillofacial Surgery Service'),
(1, 'CM_TrtmntFnc218', @scm, 'CM_TrtmntFnc218', 'Paediatric Neurosurgery Service', 'Paediatric Neurosurgery Service'),
(1, 'CM_TrtmntFnc219', @scm, 'CM_TrtmntFnc219', 'Paediatric Plastic Surgery Service', 'Paediatric Plastic Surgery Service'),
(1, 'CM_TrtmntFnc220', @scm, 'CM_TrtmntFnc220', 'Paediatric Burns Care Service', 'Paediatric Burns Care Service'),
(1, 'CM_TrtmntFnc221', @scm, 'CM_TrtmntFnc221', 'Paediatric Cardiac Surgery Service', 'Paediatric Cardiac Surgery Service'),
(1, 'CM_TrtmntFnc222', @scm, 'CM_TrtmntFnc222', 'Paediatric Thoracic Surgery Service', 'Paediatric Thoracic Surgery Service'),
(1, 'CM_TrtmntFnc223', @scm, 'CM_TrtmntFnc223', 'Paediatric Epilepsy Service', 'Paediatric Epilepsy Service'),
(1, 'CM_TrtmntFnc230', @scm, 'CM_TrtmntFnc230', 'Paediatric Clinical Pharmacology Service', 'Paediatric Clinical Pharmacology Service'),
(1, 'CM_TrtmntFnc240', @scm, 'CM_TrtmntFnc240', 'Paediatric Palliative Medicine Service', 'Paediatric Palliative Medicine Service'),
(1, 'CM_TrtmntFnc241', @scm, 'CM_TrtmntFnc241', 'Paediatric Pain Management Service', 'Paediatric Pain Management Service'),
(1, 'CM_TrtmntFnc242', @scm, 'CM_TrtmntFnc242', 'Paediatric Intensive Care Service', 'Paediatric Intensive Care Service'),
(1, 'CM_TrtmntFnc250', @scm, 'CM_TrtmntFnc250', 'Paediatric Hepatology Service', 'Paediatric Hepatology Service'),
(1, 'CM_TrtmntFnc251', @scm, 'CM_TrtmntFnc251', 'Paediatric Gastroenterology Service', 'Paediatric Gastroenterology Service'),
(1, 'CM_TrtmntFnc252', @scm, 'CM_TrtmntFnc252', 'Paediatric Endocrinology Service', 'Paediatric Endocrinology Service'),
(1, 'CM_TrtmntFnc253', @scm, 'CM_TrtmntFnc253', 'Paediatric Clinical Haematology Service', 'Paediatric Clinical Haematology Service'),
(1, 'CM_TrtmntFnc254', @scm, 'CM_TrtmntFnc254', 'Paediatric Audio Vestibular Medicine Service', 'Paediatric Audio Vestibular Medicine Service'),
(1, 'CM_TrtmntFnc255', @scm, 'CM_TrtmntFnc255', 'Paediatric Clinical Immunology and Allergy Service', 'Paediatric Clinical Immunology and Allergy Service'),
(1, 'CM_TrtmntFnc256', @scm, 'CM_TrtmntFnc256', 'Paediatric Infectious Diseases Service', 'Paediatric Infectious Diseases Service'),
(1, 'CM_TrtmntFnc257', @scm, 'CM_TrtmntFnc257', 'Paediatric Dermatology Service', 'Paediatric Dermatology Service'),
(1, 'CM_TrtmntFnc258', @scm, 'CM_TrtmntFnc258', 'Paediatric Respiratory Medicine Service', 'Paediatric Respiratory Medicine Service'),
(1, 'CM_TrtmntFnc259', @scm, 'CM_TrtmntFnc259', 'Paediatric Nephrology Service', 'Paediatric Nephrology Service'),
(1, 'CM_TrtmntFnc260', @scm, 'CM_TrtmntFnc260', 'Paediatric Medical Oncology Service', 'Paediatric Medical Oncology Service'),
(1, 'CM_TrtmntFnc261', @scm, 'CM_TrtmntFnc261', 'Paediatric Inherited Metabolic Medicine Service', 'Paediatric Inherited Metabolic Medicine Service'),
(1, 'CM_TrtmntFnc262', @scm, 'CM_TrtmntFnc262', 'Paediatric Rheumatology Service', 'Paediatric Rheumatology Service'),
(1, 'CM_TrtmntFnc263', @scm, 'CM_TrtmntFnc263', 'Paediatric Diabetes Service', 'Paediatric Diabetes Service'),
(1, 'CM_TrtmntFnc264', @scm, 'CM_TrtmntFnc264', 'Paediatric Cystic Fibrosis Service', 'Paediatric Cystic Fibrosis Service'),
(1, 'CM_TrtmntFnc270', @scm, 'CM_TrtmntFnc270', 'Paediatric Emergency Medicine Service', 'Paediatric Emergency Medicine Service'),
(1, 'CM_TrtmntFnc280', @scm, 'CM_TrtmntFnc280', 'Paediatric Interventional Radiology Service', 'Paediatric Interventional Radiology Service'),
(1, 'CM_TrtmntFnc290', @scm, 'CM_TrtmntFnc290', 'Community Paediatric Service', 'Community Paediatric Service'),
(1, 'CM_TrtmntFnc291', @scm, 'CM_TrtmntFnc291', 'Paediatric Neurodisability Service', 'Paediatric Neurodisability Service'),
(1, 'CM_TrtmntFnc321', @scm, 'CM_TrtmntFnc321', 'Paediatric Cardiology Service', 'Paediatric Cardiology Service'),
(1, 'CM_TrtmntFnc421', @scm, 'CM_TrtmntFnc421', 'Paediatric Neurology Service', 'Paediatric Neurology Service'),
(1, 'CM_TrtmntFnc180', @scm, 'CM_TrtmntFnc180', 'Emergency Medicine Service', 'Emergency Medicine Service'),
(1, 'CM_TrtmntFnc190', @scm, 'CM_TrtmntFnc190', 'Anaesthetic Service', 'Anaesthetic Service'),
(1, 'CM_TrtmntFnc192', @scm, 'CM_TrtmntFnc192', 'Intensive Care Medicine Service', 'Intensive Care Medicine Service'),
(1, 'CM_TrtmntFnc200', @scm, 'CM_TrtmntFnc200', 'Aviation and Space Medicine Service', 'Aviation and Space Medicine Service'),
(1, 'CM_TrtmntFnc300', @scm, 'CM_TrtmntFnc300', 'General Internal Medicine Service', 'General Internal Medicine Service'),
(1, 'CM_TrtmntFnc301', @scm, 'CM_TrtmntFnc301', 'Gastroenterology Service', 'Gastroenterology Service'),
(1, 'CM_TrtmntFnc302', @scm, 'CM_TrtmntFnc302', 'Endocrinology Service', 'Endocrinology Service'),
(1, 'CM_TrtmntFnc303', @scm, 'CM_TrtmntFnc303', 'Clinical Haematology Service', 'Clinical Haematology Service'),
(1, 'CM_TrtmntFnc304', @scm, 'CM_TrtmntFnc304', 'Clinical Physiology Service', 'Clinical Physiology Service'),
(1, 'CM_TrtmntFnc305', @scm, 'CM_TrtmntFnc305', 'Clinical Pharmacology Service', 'Clinical Pharmacology Service'),
(1, 'CM_TrtmntFnc306', @scm, 'CM_TrtmntFnc306', 'Hepatology Service', 'Hepatology Service'),
(1, 'CM_TrtmntFnc307', @scm, 'CM_TrtmntFnc307', 'Diabetes Service', 'Diabetes Service'),
(1, 'CM_TrtmntFnc308', @scm, 'CM_TrtmntFnc308', 'Blood and Marrow Transplantation Service', 'Blood and Marrow Transplantation Service'),
(1, 'CM_TrtmntFnc309', @scm, 'CM_TrtmntFnc309', 'Haemophilia Service', 'Haemophilia Service'),
(1, 'CM_TrtmntFnc310', @scm, 'CM_TrtmntFnc310', 'Audio Vestibular Medicine Service', 'Audio Vestibular Medicine Service'),
(1, 'CM_TrtmntFnc311', @scm, 'CM_TrtmntFnc311', 'Clinical Genetics Service', 'Clinical Genetics Service'),
(1, 'CM_TrtmntFnc313', @scm, 'CM_TrtmntFnc313', 'Clinical Immunology and Allergy Service', 'Clinical Immunology and Allergy Service'),
(1, 'CM_TrtmntFnc314', @scm, 'CM_TrtmntFnc314', 'Rehabilitation Medicine Service', 'Rehabilitation Medicine Service'),
(1, 'CM_TrtmntFnc315', @scm, 'CM_TrtmntFnc315', 'Palliative Medicine Service', 'Palliative Medicine Service'),
(1, 'CM_TrtmntFnc316', @scm, 'CM_TrtmntFnc316', 'Clinical Immunology Service', 'Clinical Immunology Service'),
(1, 'CM_TrtmntFnc317', @scm, 'CM_TrtmntFnc317', 'Allergy Service', 'Allergy Service'),
(1, 'CM_TrtmntFnc318', @scm, 'CM_TrtmntFnc318', 'Intermediate Care Service', 'Intermediate Care Service'),
(1, 'CM_TrtmntFnc319', @scm, 'CM_TrtmntFnc319', 'Respite Care Service', 'Respite Care Service'),
(1, 'CM_TrtmntFnc320', @scm, 'CM_TrtmntFnc320', 'Cardiology Service', 'Cardiology Service'),
(1, 'CM_TrtmntFnc322', @scm, 'CM_TrtmntFnc322', 'Clinical Microbiology Service', 'Clinical Microbiology Service'),
(1, 'CM_TrtmntFnc323', @scm, 'CM_TrtmntFnc323', 'Spinal Injuries Service', 'Spinal Injuries Service'),
(1, 'CM_TrtmntFnc324', @scm, 'CM_TrtmntFnc324', 'Anticoagulant Service', 'Anticoagulant Service'),
(1, 'CM_TrtmntFnc325', @scm, 'CM_TrtmntFnc325', 'Sport and Exercise Medicine Service', 'Sport and Exercise Medicine Service'),
(1, 'CM_TrtmntFnc326', @scm, 'CM_TrtmntFnc326', 'Acute Internal Medicine Service', 'Acute Internal Medicine Service'),
(1, 'CM_TrtmntFnc327', @scm, 'CM_TrtmntFnc327', 'Cardiac Rehabilitation Service', 'Cardiac Rehabilitation Service'),
(1, 'CM_TrtmntFnc328', @scm, 'CM_TrtmntFnc328', 'Stroke Medicine Service', 'Stroke Medicine Service'),
(1, 'CM_TrtmntFnc329', @scm, 'CM_TrtmntFnc329', 'Transient Ischaemic Attack Service', 'Transient Ischaemic Attack Service'),
(1, 'CM_TrtmntFnc330', @scm, 'CM_TrtmntFnc330', 'Dermatology Service', 'Dermatology Service'),
(1, 'CM_TrtmntFnc331', @scm, 'CM_TrtmntFnc331', 'Congenital Heart Disease Service', 'Congenital Heart Disease Service'),
(1, 'CM_TrtmntFnc333', @scm, 'CM_TrtmntFnc333', 'Rare Disease Service', 'Rare Disease Service'),
(1, 'CM_TrtmntFnc335', @scm, 'CM_TrtmntFnc335', 'Inherited Metabolic Medicine Service', 'Inherited Metabolic Medicine Service'),
(1, 'CM_TrtmntFnc340', @scm, 'CM_TrtmntFnc340', 'Respiratory Medicine Service', 'Respiratory Medicine Service'),
(1, 'CM_TrtmntFnc341', @scm, 'CM_TrtmntFnc341', 'Respiratory Physiology Service', 'Respiratory Physiology Service'),
(1, 'CM_TrtmntFnc342', @scm, 'CM_TrtmntFnc342', 'Pulmonary Rehabilitation Service', 'Pulmonary Rehabilitation Service'),
(1, 'CM_TrtmntFnc343', @scm, 'CM_TrtmntFnc343', 'Adult Cystic Fibrosis Service', 'Adult Cystic Fibrosis Service'),
(1, 'CM_TrtmntFnc344', @scm, 'CM_TrtmntFnc344', 'Complex Specialised Rehabilitation Service', 'Complex Specialised Rehabilitation Service'),
(1, 'CM_TrtmntFnc345', @scm, 'CM_TrtmntFnc345', 'Specialist Rehabilitation Service', 'Specialist Rehabilitation Service'),
(1, 'CM_TrtmntFnc346', @scm, 'CM_TrtmntFnc346', 'Local Specialist Rehabilitation Service', 'Local Specialist Rehabilitation Service'),
(1, 'CM_TrtmntFnc347', @scm, 'CM_TrtmntFnc347', 'Sleep Medicine Service', 'Sleep Medicine Service'),
(1, 'CM_TrtmntFnc348', @scm, 'CM_TrtmntFnc348', 'Post-COVID-19 Syndrome Service', 'Post-COVID-19 Syndrome Service'),
(1, 'CM_TrtmntFnc350', @scm, 'CM_TrtmntFnc350', 'Infectious Diseases Service', 'Infectious Diseases Service'),
(1, 'CM_TrtmntFnc352', @scm, 'CM_TrtmntFnc352', 'Tropical Medicine Service', 'Tropical Medicine Service'),
(1, 'CM_TrtmntFnc360', @scm, 'CM_TrtmntFnc360', 'Genitourinary Medicine Service', 'Genitourinary Medicine Service'),
(1, 'CM_TrtmntFnc361', @scm, 'CM_TrtmntFnc361', 'Renal Medicine Service', 'Renal Medicine Service'),
(1, 'CM_TrtmntFnc370', @scm, 'CM_TrtmntFnc370', 'Medical Oncology Service', 'Medical Oncology Service'),
(1, 'CM_TrtmntFnc371', @scm, 'CM_TrtmntFnc371', 'Nuclear Medicine Service', 'Nuclear Medicine Service'),
(1, 'CM_TrtmntFnc400', @scm, 'CM_TrtmntFnc400', 'Neurology Service', 'Neurology Service'),
(1, 'CM_TrtmntFnc401', @scm, 'CM_TrtmntFnc401', 'Clinical Neurophysiology Service', 'Clinical Neurophysiology Service'),
(1, 'CM_TrtmntFnc410', @scm, 'CM_TrtmntFnc410', 'Rheumatology Service', 'Rheumatology Service'),
(1, 'CM_TrtmntFnc420', @scm, 'CM_TrtmntFnc420', 'Paediatric Service', 'Paediatric Service'),
(1, 'CM_TrtmntFnc422', @scm, 'CM_TrtmntFnc422', 'Neonatal Critical Care Service', 'Neonatal Critical Care Service'),
(1, 'CM_TrtmntFnc424', @scm, 'CM_TrtmntFnc424', 'Well Baby Service', 'Well Baby Service'),
(1, 'CM_TrtmntFnc430', @scm, 'CM_TrtmntFnc430', 'Elderly Medicine Service', 'Elderly Medicine Service'),
(1, 'CM_TrtmntFnc431', @scm, 'CM_TrtmntFnc431', 'Orthogeriatric Medicine Service', 'Orthogeriatric Medicine Service'),
(1, 'CM_TrtmntFnc450', @scm, 'CM_TrtmntFnc450', 'Dental Medicine Service', 'Dental Medicine Service'),
(1, 'CM_TrtmntFnc451', @scm, 'CM_TrtmntFnc451', 'Special Care Dentistry Service', 'Special Care Dentistry Service'),
(1, 'CM_TrtmntFnc460', @scm, 'CM_TrtmntFnc460', 'Medical Ophthalmology Service', 'Medical Ophthalmology Service'),
(1, 'CM_TrtmntFnc461', @scm, 'CM_TrtmntFnc461', 'Ophthalmic and Vision Science Service', 'Ophthalmic and Vision Science Service'),
(1, 'CM_TrtmntFnc501', @scm, 'CM_TrtmntFnc501', 'Obstetrics Service', 'Obstetrics Service'),
(1, 'CM_TrtmntFnc502', @scm, 'CM_TrtmntFnc502', 'Gynaecology Service', 'Gynaecology Service'),
(1, 'CM_TrtmntFnc503', @scm, 'CM_TrtmntFnc503', 'Gynaecological Oncology Service', 'Gynaecological Oncology Service'),
(1, 'CM_TrtmntFnc504', @scm, 'CM_TrtmntFnc504', 'Community Sexual and Reproductive Health Service', 'Community Sexual and Reproductive Health Service'),
(1, 'CM_TrtmntFnc505', @scm, 'CM_TrtmntFnc505', 'Fetal Medicine Service', 'Fetal Medicine Service'),
(1, 'CM_TrtmntFnc510', @scm, 'CM_TrtmntFnc510', 'Retired but retained for historical purposes', 'Retired but retained for historical purposes'),
(1, 'CM_TrtmntFnc520', @scm, 'CM_TrtmntFnc520', 'Retired but retained for historical purposes', 'Retired but retained for historical purposes'),
(1, 'CM_TrtmntFnc560', @scm, 'CM_TrtmntFnc560', 'Midwifery Service', 'Midwifery Service'),
(1, 'CM_TrtmntFnc610', @scm, 'CM_TrtmntFnc610', 'Retired but retained for historical purposes', 'Retired but retained for historical purposes'),
(1, 'CM_TrtmntFnc620', @scm, 'CM_TrtmntFnc620', 'Retired but retained for historical purposes', 'Retired but retained for historical purposes'),
(1, 'CM_TrtmntFnc656', @scm, 'CM_TrtmntFnc656', 'Clinical Psychology Service', 'Clinical Psychology Service'),
(1, 'CM_TrtmntFnc700', @scm, 'CM_TrtmntFnc700', 'Learning Disability Service', 'Learning Disability Service'),
(1, 'CM_TrtmntFnc710', @scm, 'CM_TrtmntFnc710', 'Adult Mental Health Service', 'Adult Mental Health Service'),
(1, 'CM_TrtmntFnc711', @scm, 'CM_TrtmntFnc711', 'Child and Adolescent Psychiatry Service', 'Child and Adolescent Psychiatry Service'),
(1, 'CM_TrtmntFnc712', @scm, 'CM_TrtmntFnc712', 'Forensic Psychiatry Service', 'Forensic Psychiatry Service'),
(1, 'CM_TrtmntFnc713', @scm, 'CM_TrtmntFnc713', 'Medical Psychotherapy Service', 'Medical Psychotherapy Service'),
(1, 'CM_TrtmntFnc715', @scm, 'CM_TrtmntFnc715', 'Old Age Psychiatry Service', 'Old Age Psychiatry Service'),
(1, 'CM_TrtmntFnc720', @scm, 'CM_TrtmntFnc720', 'Eating Disorders Service', 'Eating Disorders Service'),
(1, 'CM_TrtmntFnc721', @scm, 'CM_TrtmntFnc721', 'Addiction Service', 'Addiction Service'),
(1, 'CM_TrtmntFnc722', @scm, 'CM_TrtmntFnc722', 'Liaison Psychiatry Service', 'Liaison Psychiatry Service'),
(1, 'CM_TrtmntFnc723', @scm, 'CM_TrtmntFnc723', 'Psychiatric Intensive Care Service', 'Psychiatric Intensive Care Service'),
(1, 'CM_TrtmntFnc724', @scm, 'CM_TrtmntFnc724', 'Perinatal Mental Health Service', 'Perinatal Mental Health Service'),
(1, 'CM_TrtmntFnc725', @scm, 'CM_TrtmntFnc725', 'Mental Health Recovery and Rehabilitation Service', 'Mental Health Recovery and Rehabilitation Service'),
(1, 'CM_TrtmntFnc726', @scm, 'CM_TrtmntFnc726', 'Mental Health Dual Diagnosis Service', 'Mental Health Dual Diagnosis Service'),
(1, 'CM_TrtmntFnc727', @scm, 'CM_TrtmntFnc727', 'Dementia Assessment Service', 'Dementia Assessment Service'),
(1, 'CM_TrtmntFnc730', @scm, 'CM_TrtmntFnc730', 'Neuropsychiatry Service', 'Neuropsychiatry Service'),
(1, 'CM_TrtmntFnc800', @scm, 'CM_TrtmntFnc800', 'Clinical Oncology Service', 'Clinical Oncology Service'),
(1, 'CM_TrtmntFnc811', @scm, 'CM_TrtmntFnc811', 'Interventional Radiology Service', 'Interventional Radiology Service'),
(1, 'CM_TrtmntFnc812', @scm, 'CM_TrtmntFnc812', 'Diagnostic Imaging Service', 'Diagnostic Imaging Service'),
(1, 'CM_TrtmntFnc822', @scm, 'CM_TrtmntFnc822', 'Chemical Pathology Service', 'Chemical Pathology Service'),
(1, 'CM_TrtmntFnc832', @scm, 'CM_TrtmntFnc832', 'Retired but retained for historical purposes', 'Retired but retained for historical purposes'),
(1, 'CM_TrtmntFnc834', @scm, 'CM_TrtmntFnc834', 'Medical Virology Service', 'Medical Virology Service'),
(1, 'CM_TrtmntFnc650', @scm, 'CM_TrtmntFnc650', 'Physiotherapy Service', 'Physiotherapy Service'),
(1, 'CM_TrtmntFnc651', @scm, 'CM_TrtmntFnc651', 'Occupational Therapy Service', 'Occupational Therapy Service'),
(1, 'CM_TrtmntFnc652', @scm, 'CM_TrtmntFnc652', 'Speech and Language Therapy Service', 'Speech and Language Therapy Service'),
(1, 'CM_TrtmntFnc653', @scm, 'CM_TrtmntFnc653', 'Podiatry Service', 'Podiatry Service'),
(1, 'CM_TrtmntFnc654', @scm, 'CM_TrtmntFnc654', 'Dietetics Service', 'Dietetics Service'),
(1, 'CM_TrtmntFnc655', @scm, 'CM_TrtmntFnc655', 'Orthoptics Service', 'Orthoptics Service'),
(1, 'CM_TrtmntFnc657', @scm, 'CM_TrtmntFnc657', 'Prosthetics Service', 'Prosthetics Service'),
(1, 'CM_TrtmntFnc658', @scm, 'CM_TrtmntFnc658', 'Orthotics Service', 'Orthotics Service'),
(1, 'CM_TrtmntFnc659', @scm, 'CM_TrtmntFnc659', 'Dramatherapy Service', 'Dramatherapy Service'),
(1, 'CM_TrtmntFnc660', @scm, 'CM_TrtmntFnc660', 'Art Therapy Service', 'Art Therapy Service'),
(1, 'CM_TrtmntFnc661', @scm, 'CM_TrtmntFnc661', 'Music Therapy Service', 'Music Therapy Service'),
(1, 'CM_TrtmntFnc662', @scm, 'CM_TrtmntFnc662', 'Optometry Service', 'Optometry Service'),
(1, 'CM_TrtmntFnc663', @scm, 'CM_TrtmntFnc663', 'Podiatric Surgery Service', 'Podiatric Surgery Service'),
(1, 'CM_TrtmntFnc670', @scm, 'CM_TrtmntFnc670', 'Urological Physiology Service', 'Urological Physiology Service'),
(1, 'CM_TrtmntFnc673', @scm, 'CM_TrtmntFnc673', 'Vascular Physiology Service', 'Vascular Physiology Service'),
(1, 'CM_TrtmntFnc675', @scm, 'CM_TrtmntFnc675', 'Cardiac Physiology Service', 'Cardiac Physiology Service'),
(1, 'CM_TrtmntFnc677', @scm, 'CM_TrtmntFnc677', 'Gastrointestinal Physiology Service', 'Gastrointestinal Physiology Service'),
(1, 'CM_TrtmntFnc840', @scm, 'CM_TrtmntFnc840', 'Audiology Service', 'Audiology Service'),
(1, 'CM_TrtmntFnc920', @scm, 'CM_TrtmntFnc920', 'Diabetic Education Service', 'Diabetic Education Service'),
(1, 'CM_TrtmntFnc990', @scm, 'CM_TrtmntFnc990', 'Retired but retained for historical purposes', 'Retired but retained for historical purposes'),
(1, 'CM_TrtmntFnc147', @scm, 'CM_TrtmntFnc147', 'Periodontics', 'Periodontics'),
(1, 'CM_TrtmntFnc820', @scm, 'CM_TrtmntFnc820', 'General Pathology', 'General Pathology'),
(1, 'CM_TrtmntFnc821', @scm, 'CM_TrtmntFnc821', 'Blood Transfusion', 'Blood Transfusion'),
(1, 'CM_TrtmntFnc823', @scm, 'CM_TrtmntFnc823', 'Haematology', 'Haematology'),
(1, 'CM_TrtmntFnc824', @scm, 'CM_TrtmntFnc824', 'Histopathology', 'Histopathology'),
(1, 'CM_TrtmntFnc830', @scm, 'CM_TrtmntFnc830', 'Immunopathology', 'Immunopathology'),
(1, 'CM_TrtmntFnc831', @scm, 'CM_TrtmntFnc831', 'Medical Microbiology and Virology', 'Medical Microbiology and Virology'),
(1, 'CM_TrtmntFnc833', @scm, 'CM_TrtmntFnc833', 'Medical Microbiology', 'Medical Microbiology'),
(1, 'CM_TrtmntFnc900', @scm, 'CM_TrtmntFnc900', 'Community Medicine', 'Community Medicine'),
(1, 'CM_TrtmntFnc901', @scm, 'CM_TrtmntFnc901', 'Occupational Medicine', 'Occupational Medicine'),
(1, 'CM_TrtmntFnc902', @scm, 'CM_TrtmntFnc902', 'Community Health Services Dental', 'Community Health Services Dental'),
(1, 'CM_TrtmntFnc903', @scm, 'CM_TrtmntFnc903', 'Public Health Medicine', 'Public Health Medicine'),
(1, 'CM_TrtmntFnc950', @scm, 'CM_TrtmntFnc950', 'Nursing', 'Nursing'),
(1, 'CM_TrtmntFnc960', @scm, 'CM_TrtmntFnc960', 'Allied Health Professional', 'Allied Health Professional'),
(1, 'CM_TrtmntFnc990', @scm, 'CM_TrtmntFnc990', 'Joint Consultant Clinics', 'Joint Consultant Clinics'),
-- Added 17 Jul 2022
(1, 'CM_TrtmntFnc600', @scm, 'CM_TrtmntFnc600', 'General Medical Practice', 'General Medical Practice'),
(1, 'CM_TrtmntFnc810', @scm, 'CM_TrtmntFnc810', 'Radiology', 'Radiology');



    -- Node maps
INSERT INTO map_node_meta
(node, concept)
VALUES
('/CDS/INPTNT/MN_SPCLTY',             'DM_treatmentFunctionAdmit');

-- Value maps
INSERT INTO map_node_value_meta
(node, value, scheme, concept)
VALUES
('/CDS/INPTNT/MN_SPCLTY', '100', 'CM_NHS_DD', 'CM_TrtmntFnc100'),
('/CDS/INPTNT/MN_SPCLTY', '101', 'CM_NHS_DD', 'CM_TrtmntFnc101'),
('/CDS/INPTNT/MN_SPCLTY', '102', 'CM_NHS_DD', 'CM_TrtmntFnc102'),
('/CDS/INPTNT/MN_SPCLTY', '103', 'CM_NHS_DD', 'CM_TrtmntFnc103'),
('/CDS/INPTNT/MN_SPCLTY', '104', 'CM_NHS_DD', 'CM_TrtmntFnc104'),
('/CDS/INPTNT/MN_SPCLTY', '105', 'CM_NHS_DD', 'CM_TrtmntFnc105'),
('/CDS/INPTNT/MN_SPCLTY', '106', 'CM_NHS_DD', 'CM_TrtmntFnc106'),
('/CDS/INPTNT/MN_SPCLTY', '107', 'CM_NHS_DD', 'CM_TrtmntFnc107'),
('/CDS/INPTNT/MN_SPCLTY', '108', 'CM_NHS_DD', 'CM_TrtmntFnc108'),
('/CDS/INPTNT/MN_SPCLTY', '109', 'CM_NHS_DD', 'CM_TrtmntFnc109'),
('/CDS/INPTNT/MN_SPCLTY', '110', 'CM_NHS_DD', 'CM_TrtmntFnc110'),
('/CDS/INPTNT/MN_SPCLTY', '111', 'CM_NHS_DD', 'CM_TrtmntFnc111'),
('/CDS/INPTNT/MN_SPCLTY', '113', 'CM_NHS_DD', 'CM_TrtmntFnc113'),
('/CDS/INPTNT/MN_SPCLTY', '115', 'CM_NHS_DD', 'CM_TrtmntFnc115'),
('/CDS/INPTNT/MN_SPCLTY', '120', 'CM_NHS_DD', 'CM_TrtmntFnc120'),
('/CDS/INPTNT/MN_SPCLTY', '130', 'CM_NHS_DD', 'CM_TrtmntFnc130'),
('/CDS/INPTNT/MN_SPCLTY', '140', 'CM_NHS_DD', 'CM_TrtmntFnc140'),
('/CDS/INPTNT/MN_SPCLTY', '141', 'CM_NHS_DD', 'CM_TrtmntFnc141'),
('/CDS/INPTNT/MN_SPCLTY', '143', 'CM_NHS_DD', 'CM_TrtmntFnc143'),
('/CDS/INPTNT/MN_SPCLTY', '144', 'CM_NHS_DD', 'CM_TrtmntFnc144'),
('/CDS/INPTNT/MN_SPCLTY', '145', 'CM_NHS_DD', 'CM_TrtmntFnc145'),
('/CDS/INPTNT/MN_SPCLTY', '150', 'CM_NHS_DD', 'CM_TrtmntFnc150'),
('/CDS/INPTNT/MN_SPCLTY', '160', 'CM_NHS_DD', 'CM_TrtmntFnc160'),
('/CDS/INPTNT/MN_SPCLTY', '161', 'CM_NHS_DD', 'CM_TrtmntFnc161'),
('/CDS/INPTNT/MN_SPCLTY', '170', 'CM_NHS_DD', 'CM_TrtmntFnc170'),
('/CDS/INPTNT/MN_SPCLTY', '172', 'CM_NHS_DD', 'CM_TrtmntFnc172'),
('/CDS/INPTNT/MN_SPCLTY', '173', 'CM_NHS_DD', 'CM_TrtmntFnc173'),
('/CDS/INPTNT/MN_SPCLTY', '174', 'CM_NHS_DD', 'CM_TrtmntFnc174'),
('/CDS/INPTNT/MN_SPCLTY', '191', 'CM_NHS_DD', 'CM_TrtmntFnc191'),
('/CDS/INPTNT/MN_SPCLTY', '142', 'CM_NHS_DD', 'CM_TrtmntFnc142'),
('/CDS/INPTNT/MN_SPCLTY', '171', 'CM_NHS_DD', 'CM_TrtmntFnc171'),
('/CDS/INPTNT/MN_SPCLTY', '211', 'CM_NHS_DD', 'CM_TrtmntFnc211'),
('/CDS/INPTNT/MN_SPCLTY', '212', 'CM_NHS_DD', 'CM_TrtmntFnc212'),
('/CDS/INPTNT/MN_SPCLTY', '213', 'CM_NHS_DD', 'CM_TrtmntFnc213'),
('/CDS/INPTNT/MN_SPCLTY', '214', 'CM_NHS_DD', 'CM_TrtmntFnc214'),
('/CDS/INPTNT/MN_SPCLTY', '215', 'CM_NHS_DD', 'CM_TrtmntFnc215'),
('/CDS/INPTNT/MN_SPCLTY', '216', 'CM_NHS_DD', 'CM_TrtmntFnc216'),
('/CDS/INPTNT/MN_SPCLTY', '217', 'CM_NHS_DD', 'CM_TrtmntFnc217'),
('/CDS/INPTNT/MN_SPCLTY', '218', 'CM_NHS_DD', 'CM_TrtmntFnc218'),
('/CDS/INPTNT/MN_SPCLTY', '219', 'CM_NHS_DD', 'CM_TrtmntFnc219'),
('/CDS/INPTNT/MN_SPCLTY', '220', 'CM_NHS_DD', 'CM_TrtmntFnc220'),
('/CDS/INPTNT/MN_SPCLTY', '221', 'CM_NHS_DD', 'CM_TrtmntFnc221'),
('/CDS/INPTNT/MN_SPCLTY', '222', 'CM_NHS_DD', 'CM_TrtmntFnc222'),
('/CDS/INPTNT/MN_SPCLTY', '223', 'CM_NHS_DD', 'CM_TrtmntFnc223'),
('/CDS/INPTNT/MN_SPCLTY', '230', 'CM_NHS_DD', 'CM_TrtmntFnc230'),
('/CDS/INPTNT/MN_SPCLTY', '240', 'CM_NHS_DD', 'CM_TrtmntFnc240'),
('/CDS/INPTNT/MN_SPCLTY', '241', 'CM_NHS_DD', 'CM_TrtmntFnc241'),
('/CDS/INPTNT/MN_SPCLTY', '242', 'CM_NHS_DD', 'CM_TrtmntFnc242'),
('/CDS/INPTNT/MN_SPCLTY', '250', 'CM_NHS_DD', 'CM_TrtmntFnc250'),
('/CDS/INPTNT/MN_SPCLTY', '251', 'CM_NHS_DD', 'CM_TrtmntFnc251'),
('/CDS/INPTNT/MN_SPCLTY', '252', 'CM_NHS_DD', 'CM_TrtmntFnc252'),
('/CDS/INPTNT/MN_SPCLTY', '253', 'CM_NHS_DD', 'CM_TrtmntFnc253'),
('/CDS/INPTNT/MN_SPCLTY', '254', 'CM_NHS_DD', 'CM_TrtmntFnc254'),
('/CDS/INPTNT/MN_SPCLTY', '255', 'CM_NHS_DD', 'CM_TrtmntFnc255'),
('/CDS/INPTNT/MN_SPCLTY', '256', 'CM_NHS_DD', 'CM_TrtmntFnc256'),
('/CDS/INPTNT/MN_SPCLTY', '257', 'CM_NHS_DD', 'CM_TrtmntFnc257'),
('/CDS/INPTNT/MN_SPCLTY', '258', 'CM_NHS_DD', 'CM_TrtmntFnc258'),
('/CDS/INPTNT/MN_SPCLTY', '259', 'CM_NHS_DD', 'CM_TrtmntFnc259'),
('/CDS/INPTNT/MN_SPCLTY', '260', 'CM_NHS_DD', 'CM_TrtmntFnc260'),
('/CDS/INPTNT/MN_SPCLTY', '261', 'CM_NHS_DD', 'CM_TrtmntFnc261'),
('/CDS/INPTNT/MN_SPCLTY', '262', 'CM_NHS_DD', 'CM_TrtmntFnc262'),
('/CDS/INPTNT/MN_SPCLTY', '263', 'CM_NHS_DD', 'CM_TrtmntFnc263'),
('/CDS/INPTNT/MN_SPCLTY', '264', 'CM_NHS_DD', 'CM_TrtmntFnc264'),
('/CDS/INPTNT/MN_SPCLTY', '270', 'CM_NHS_DD', 'CM_TrtmntFnc270'),
('/CDS/INPTNT/MN_SPCLTY', '280', 'CM_NHS_DD', 'CM_TrtmntFnc280'),
('/CDS/INPTNT/MN_SPCLTY', '290', 'CM_NHS_DD', 'CM_TrtmntFnc290'),
('/CDS/INPTNT/MN_SPCLTY', '291', 'CM_NHS_DD', 'CM_TrtmntFnc291'),
('/CDS/INPTNT/MN_SPCLTY', '321', 'CM_NHS_DD', 'CM_TrtmntFnc321'),
('/CDS/INPTNT/MN_SPCLTY', '421', 'CM_NHS_DD', 'CM_TrtmntFnc421'),
('/CDS/INPTNT/MN_SPCLTY', '180', 'CM_NHS_DD', 'CM_TrtmntFnc180'),
('/CDS/INPTNT/MN_SPCLTY', '190', 'CM_NHS_DD', 'CM_TrtmntFnc190'),
('/CDS/INPTNT/MN_SPCLTY', '192', 'CM_NHS_DD', 'CM_TrtmntFnc192'),
('/CDS/INPTNT/MN_SPCLTY', '200', 'CM_NHS_DD', 'CM_TrtmntFnc200'),
('/CDS/INPTNT/MN_SPCLTY', '300', 'CM_NHS_DD', 'CM_TrtmntFnc300'),
('/CDS/INPTNT/MN_SPCLTY', '301', 'CM_NHS_DD', 'CM_TrtmntFnc301'),
('/CDS/INPTNT/MN_SPCLTY', '302', 'CM_NHS_DD', 'CM_TrtmntFnc302'),
('/CDS/INPTNT/MN_SPCLTY', '303', 'CM_NHS_DD', 'CM_TrtmntFnc303'),
('/CDS/INPTNT/MN_SPCLTY', '304', 'CM_NHS_DD', 'CM_TrtmntFnc304'),
('/CDS/INPTNT/MN_SPCLTY', '305', 'CM_NHS_DD', 'CM_TrtmntFnc305'),
('/CDS/INPTNT/MN_SPCLTY', '306', 'CM_NHS_DD', 'CM_TrtmntFnc306'),
('/CDS/INPTNT/MN_SPCLTY', '307', 'CM_NHS_DD', 'CM_TrtmntFnc307'),
('/CDS/INPTNT/MN_SPCLTY', '308', 'CM_NHS_DD', 'CM_TrtmntFnc308'),
('/CDS/INPTNT/MN_SPCLTY', '309', 'CM_NHS_DD', 'CM_TrtmntFnc309'),
('/CDS/INPTNT/MN_SPCLTY', '310', 'CM_NHS_DD', 'CM_TrtmntFnc310'),
('/CDS/INPTNT/MN_SPCLTY', '311', 'CM_NHS_DD', 'CM_TrtmntFnc311'),
('/CDS/INPTNT/MN_SPCLTY', '313', 'CM_NHS_DD', 'CM_TrtmntFnc313'),
('/CDS/INPTNT/MN_SPCLTY', '314', 'CM_NHS_DD', 'CM_TrtmntFnc314'),
('/CDS/INPTNT/MN_SPCLTY', '315', 'CM_NHS_DD', 'CM_TrtmntFnc315'),
('/CDS/INPTNT/MN_SPCLTY', '316', 'CM_NHS_DD', 'CM_TrtmntFnc316'),
('/CDS/INPTNT/MN_SPCLTY', '317', 'CM_NHS_DD', 'CM_TrtmntFnc317'),
('/CDS/INPTNT/MN_SPCLTY', '318', 'CM_NHS_DD', 'CM_TrtmntFnc318'),
('/CDS/INPTNT/MN_SPCLTY', '319', 'CM_NHS_DD', 'CM_TrtmntFnc319'),
('/CDS/INPTNT/MN_SPCLTY', '320', 'CM_NHS_DD', 'CM_TrtmntFnc320'),
('/CDS/INPTNT/MN_SPCLTY', '322', 'CM_NHS_DD', 'CM_TrtmntFnc322'),
('/CDS/INPTNT/MN_SPCLTY', '323', 'CM_NHS_DD', 'CM_TrtmntFnc323'),
('/CDS/INPTNT/MN_SPCLTY', '324', 'CM_NHS_DD', 'CM_TrtmntFnc324'),
('/CDS/INPTNT/MN_SPCLTY', '325', 'CM_NHS_DD', 'CM_TrtmntFnc325'),
('/CDS/INPTNT/MN_SPCLTY', '326', 'CM_NHS_DD', 'CM_TrtmntFnc326'),
('/CDS/INPTNT/MN_SPCLTY', '327', 'CM_NHS_DD', 'CM_TrtmntFnc327'),
('/CDS/INPTNT/MN_SPCLTY', '328', 'CM_NHS_DD', 'CM_TrtmntFnc328'),
('/CDS/INPTNT/MN_SPCLTY', '329', 'CM_NHS_DD', 'CM_TrtmntFnc329'),
('/CDS/INPTNT/MN_SPCLTY', '330', 'CM_NHS_DD', 'CM_TrtmntFnc330'),
('/CDS/INPTNT/MN_SPCLTY', '331', 'CM_NHS_DD', 'CM_TrtmntFnc331'),
('/CDS/INPTNT/MN_SPCLTY', '333', 'CM_NHS_DD', 'CM_TrtmntFnc333'),
('/CDS/INPTNT/MN_SPCLTY', '335', 'CM_NHS_DD', 'CM_TrtmntFnc335'),
('/CDS/INPTNT/MN_SPCLTY', '340', 'CM_NHS_DD', 'CM_TrtmntFnc340'),
('/CDS/INPTNT/MN_SPCLTY', '341', 'CM_NHS_DD', 'CM_TrtmntFnc341'),
('/CDS/INPTNT/MN_SPCLTY', '342', 'CM_NHS_DD', 'CM_TrtmntFnc342'),
('/CDS/INPTNT/MN_SPCLTY', '343', 'CM_NHS_DD', 'CM_TrtmntFnc343'),
('/CDS/INPTNT/MN_SPCLTY', '344', 'CM_NHS_DD', 'CM_TrtmntFnc344'),
('/CDS/INPTNT/MN_SPCLTY', '345', 'CM_NHS_DD', 'CM_TrtmntFnc345'),
('/CDS/INPTNT/MN_SPCLTY', '346', 'CM_NHS_DD', 'CM_TrtmntFnc346'),
('/CDS/INPTNT/MN_SPCLTY', '347', 'CM_NHS_DD', 'CM_TrtmntFnc347'),
('/CDS/INPTNT/MN_SPCLTY', '348', 'CM_NHS_DD', 'CM_TrtmntFnc348'),
('/CDS/INPTNT/MN_SPCLTY', '350', 'CM_NHS_DD', 'CM_TrtmntFnc350'),
('/CDS/INPTNT/MN_SPCLTY', '352', 'CM_NHS_DD', 'CM_TrtmntFnc352'),
('/CDS/INPTNT/MN_SPCLTY', '360', 'CM_NHS_DD', 'CM_TrtmntFnc360'),
('/CDS/INPTNT/MN_SPCLTY', '361', 'CM_NHS_DD', 'CM_TrtmntFnc361'),
('/CDS/INPTNT/MN_SPCLTY', '370', 'CM_NHS_DD', 'CM_TrtmntFnc370'),
('/CDS/INPTNT/MN_SPCLTY', '371', 'CM_NHS_DD', 'CM_TrtmntFnc371'),
('/CDS/INPTNT/MN_SPCLTY', '400', 'CM_NHS_DD', 'CM_TrtmntFnc400'),
('/CDS/INPTNT/MN_SPCLTY', '401', 'CM_NHS_DD', 'CM_TrtmntFnc401'),
('/CDS/INPTNT/MN_SPCLTY', '410', 'CM_NHS_DD', 'CM_TrtmntFnc410'),
('/CDS/INPTNT/MN_SPCLTY', '420', 'CM_NHS_DD', 'CM_TrtmntFnc420'),
('/CDS/INPTNT/MN_SPCLTY', '422', 'CM_NHS_DD', 'CM_TrtmntFnc422'),
('/CDS/INPTNT/MN_SPCLTY', '424', 'CM_NHS_DD', 'CM_TrtmntFnc424'),
('/CDS/INPTNT/MN_SPCLTY', '430', 'CM_NHS_DD', 'CM_TrtmntFnc430'),
('/CDS/INPTNT/MN_SPCLTY', '431', 'CM_NHS_DD', 'CM_TrtmntFnc431'),
('/CDS/INPTNT/MN_SPCLTY', '450', 'CM_NHS_DD', 'CM_TrtmntFnc450'),
('/CDS/INPTNT/MN_SPCLTY', '451', 'CM_NHS_DD', 'CM_TrtmntFnc451'),
('/CDS/INPTNT/MN_SPCLTY', '460', 'CM_NHS_DD', 'CM_TrtmntFnc460'),
('/CDS/INPTNT/MN_SPCLTY', '461', 'CM_NHS_DD', 'CM_TrtmntFnc461'),
('/CDS/INPTNT/MN_SPCLTY', '501', 'CM_NHS_DD', 'CM_TrtmntFnc501'),
('/CDS/INPTNT/MN_SPCLTY', '502', 'CM_NHS_DD', 'CM_TrtmntFnc502'),
('/CDS/INPTNT/MN_SPCLTY', '503', 'CM_NHS_DD', 'CM_TrtmntFnc503'),
('/CDS/INPTNT/MN_SPCLTY', '504', 'CM_NHS_DD', 'CM_TrtmntFnc504'),
('/CDS/INPTNT/MN_SPCLTY', '505', 'CM_NHS_DD', 'CM_TrtmntFnc505'),
('/CDS/INPTNT/MN_SPCLTY', '510', 'CM_NHS_DD', 'CM_TrtmntFnc510'),
('/CDS/INPTNT/MN_SPCLTY', '520', 'CM_NHS_DD', 'CM_TrtmntFnc520'),
('/CDS/INPTNT/MN_SPCLTY', '560', 'CM_NHS_DD', 'CM_TrtmntFnc560'),
('/CDS/INPTNT/MN_SPCLTY', '610', 'CM_NHS_DD', 'CM_TrtmntFnc610'),
('/CDS/INPTNT/MN_SPCLTY', '620', 'CM_NHS_DD', 'CM_TrtmntFnc620'),
('/CDS/INPTNT/MN_SPCLTY', '656', 'CM_NHS_DD', 'CM_TrtmntFnc656'),
('/CDS/INPTNT/MN_SPCLTY', '700', 'CM_NHS_DD', 'CM_TrtmntFnc700'),
('/CDS/INPTNT/MN_SPCLTY', '710', 'CM_NHS_DD', 'CM_TrtmntFnc710'),
('/CDS/INPTNT/MN_SPCLTY', '711', 'CM_NHS_DD', 'CM_TrtmntFnc711'),
('/CDS/INPTNT/MN_SPCLTY', '712', 'CM_NHS_DD', 'CM_TrtmntFnc712'),
('/CDS/INPTNT/MN_SPCLTY', '713', 'CM_NHS_DD', 'CM_TrtmntFnc713'),
('/CDS/INPTNT/MN_SPCLTY', '715', 'CM_NHS_DD', 'CM_TrtmntFnc715'),
('/CDS/INPTNT/MN_SPCLTY', '720', 'CM_NHS_DD', 'CM_TrtmntFnc720'),
('/CDS/INPTNT/MN_SPCLTY', '721', 'CM_NHS_DD', 'CM_TrtmntFnc721'),
('/CDS/INPTNT/MN_SPCLTY', '722', 'CM_NHS_DD', 'CM_TrtmntFnc722'),
('/CDS/INPTNT/MN_SPCLTY', '723', 'CM_NHS_DD', 'CM_TrtmntFnc723'),
('/CDS/INPTNT/MN_SPCLTY', '724', 'CM_NHS_DD', 'CM_TrtmntFnc724'),
('/CDS/INPTNT/MN_SPCLTY', '725', 'CM_NHS_DD', 'CM_TrtmntFnc725'),
('/CDS/INPTNT/MN_SPCLTY', '726', 'CM_NHS_DD', 'CM_TrtmntFnc726'),
('/CDS/INPTNT/MN_SPCLTY', '727', 'CM_NHS_DD', 'CM_TrtmntFnc727'),
('/CDS/INPTNT/MN_SPCLTY', '730', 'CM_NHS_DD', 'CM_TrtmntFnc730'),
('/CDS/INPTNT/MN_SPCLTY', '800', 'CM_NHS_DD', 'CM_TrtmntFnc800'),
('/CDS/INPTNT/MN_SPCLTY', '811', 'CM_NHS_DD', 'CM_TrtmntFnc811'),
('/CDS/INPTNT/MN_SPCLTY', '812', 'CM_NHS_DD', 'CM_TrtmntFnc812'),
('/CDS/INPTNT/MN_SPCLTY', '822', 'CM_NHS_DD', 'CM_TrtmntFnc822'),
('/CDS/INPTNT/MN_SPCLTY', '832', 'CM_NHS_DD', 'CM_TrtmntFnc832'),
('/CDS/INPTNT/MN_SPCLTY', '834', 'CM_NHS_DD', 'CM_TrtmntFnc834'),
('/CDS/INPTNT/MN_SPCLTY', '650', 'CM_NHS_DD', 'CM_TrtmntFnc650'),
('/CDS/INPTNT/MN_SPCLTY', '651', 'CM_NHS_DD', 'CM_TrtmntFnc651'),
('/CDS/INPTNT/MN_SPCLTY', '652', 'CM_NHS_DD', 'CM_TrtmntFnc652'),
('/CDS/INPTNT/MN_SPCLTY', '653', 'CM_NHS_DD', 'CM_TrtmntFnc653'),
('/CDS/INPTNT/MN_SPCLTY', '654', 'CM_NHS_DD', 'CM_TrtmntFnc654'),
('/CDS/INPTNT/MN_SPCLTY', '655', 'CM_NHS_DD', 'CM_TrtmntFnc655'),
('/CDS/INPTNT/MN_SPCLTY', '657', 'CM_NHS_DD', 'CM_TrtmntFnc657'),
('/CDS/INPTNT/MN_SPCLTY', '658', 'CM_NHS_DD', 'CM_TrtmntFnc658'),
('/CDS/INPTNT/MN_SPCLTY', '659', 'CM_NHS_DD', 'CM_TrtmntFnc659'),
('/CDS/INPTNT/MN_SPCLTY', '660', 'CM_NHS_DD', 'CM_TrtmntFnc660'),
('/CDS/INPTNT/MN_SPCLTY', '661', 'CM_NHS_DD', 'CM_TrtmntFnc661'),
('/CDS/INPTNT/MN_SPCLTY', '662', 'CM_NHS_DD', 'CM_TrtmntFnc662'),
('/CDS/INPTNT/MN_SPCLTY', '663', 'CM_NHS_DD', 'CM_TrtmntFnc663'),
('/CDS/INPTNT/MN_SPCLTY', '670', 'CM_NHS_DD', 'CM_TrtmntFnc670'),
('/CDS/INPTNT/MN_SPCLTY', '673', 'CM_NHS_DD', 'CM_TrtmntFnc673'),
('/CDS/INPTNT/MN_SPCLTY', '675', 'CM_NHS_DD', 'CM_TrtmntFnc675'),
('/CDS/INPTNT/MN_SPCLTY', '677', 'CM_NHS_DD', 'CM_TrtmntFnc677'),
('/CDS/INPTNT/MN_SPCLTY', '840', 'CM_NHS_DD', 'CM_TrtmntFnc840'),
('/CDS/INPTNT/MN_SPCLTY', '920', 'CM_NHS_DD', 'CM_TrtmntFnc920'),
('/CDS/INPTNT/MN_SPCLTY', '990', 'CM_NHS_DD', 'CM_TrtmntFnc990'),
('/CDS/INPTNT/MN_SPCLTY', '147', 'CM_NHS_DD', 'CM_TrtmntFnc147'),
('/CDS/INPTNT/MN_SPCLTY', '820', 'CM_NHS_DD', 'CM_TrtmntFnc820'),
('/CDS/INPTNT/MN_SPCLTY', '821', 'CM_NHS_DD', 'CM_TrtmntFnc821'),
('/CDS/INPTNT/MN_SPCLTY', '823', 'CM_NHS_DD', 'CM_TrtmntFnc823'),
('/CDS/INPTNT/MN_SPCLTY', '824', 'CM_NHS_DD', 'CM_TrtmntFnc824'),
('/CDS/INPTNT/MN_SPCLTY', '830', 'CM_NHS_DD', 'CM_TrtmntFnc830'),
('/CDS/INPTNT/MN_SPCLTY', '831', 'CM_NHS_DD', 'CM_TrtmntFnc831'),
('/CDS/INPTNT/MN_SPCLTY', '833', 'CM_NHS_DD', 'CM_TrtmntFnc833'),
('/CDS/INPTNT/MN_SPCLTY', '900', 'CM_NHS_DD', 'CM_TrtmntFnc900'),
('/CDS/INPTNT/MN_SPCLTY', '901', 'CM_NHS_DD', 'CM_TrtmntFnc901'),
('/CDS/INPTNT/MN_SPCLTY', '902', 'CM_NHS_DD', 'CM_TrtmntFnc902'),
('/CDS/INPTNT/MN_SPCLTY', '903', 'CM_NHS_DD', 'CM_TrtmntFnc903'),
('/CDS/INPTNT/MN_SPCLTY', '950', 'CM_NHS_DD', 'CM_TrtmntFnc950'),
('/CDS/INPTNT/MN_SPCLTY', '960', 'CM_NHS_DD', 'CM_TrtmntFnc960'),
('/CDS/INPTNT/MN_SPCLTY', '990', 'CM_NHS_DD', 'CM_TrtmntFnc990'),
('/CDS/INPTNT/MN_SPCLTY', '600', 'CM_NHS_DD', 'CM_TrtmntFnc600'),
('/CDS/INPTNT/MN_SPCLTY', '810', 'CM_NHS_DD', 'CM_TrtmntFnc810');
