-- Ensure core code scheme exists
INSERT IGNORE INTO concept (document, id, name, description)
VALUES (1, 'CM_DiscoveryCode', 'Discovery code', 'Discovery (core) coding scheme ');

-- Get scheme id
SELECT @scm := dbid FROM concept WHERE id = 'CM_DiscoveryCode';

-- Ensure NHS DD scheme exists --
INSERT IGNORE INTO concept (document, id, scheme, code, name, description)
VALUES (1, 'CM_NHS_DD', @scm, 'CM_NHS_DD', 'NHS Data Dictionary', 'NHS Data Dictionary coding scheme');

-- Code scheme prefix entries
INSERT IGNORE INTO concept_property_data
(`dbid`, `group`, `property`, `value`)
SELECT c.dbid, 0 AS `group`, p.dbid AS `property`, '' AS `value`
FROM concept c
JOIN concept p ON p.id = 'code_prefix'
WHERE c.id IN ('CM_DiscoveryCode', 'CM_NHS_DD');

-- TREATMENT FUNCTION -- https://datadictionary.nhs.uk/attributes/treatment_function_code.html
-- MAIN SPECIALITY    -- https://www.datadictionary.nhs.uk/supporting_information/main_specialty_and_treatment_function_codes_table.html
INSERT IGNORE INTO concept (document, id, scheme, code, name, description)
VALUES
(1, 'DM_treatmentFunctionAdmit', @scm, 'DM_treatmentFunctionAdmit', 'Treatment function', 'Treatment function code'),
(1, 'CM_TrtmntFnc100', @scm, 'CM_TrtmntFnc100', 'General Surgery Service', 'General Surgery Service'),
(1, 'CM_TrtmntFnc101', @scm, 'CM_TrtmntFnc101', 'Urology Service', 'Urology Service'),
(1, 'CM_TrtmntFnc102', @scm, 'CM_TrtmntFnc102', 'Transplant Surgery Service', 'Transplant Surgery Service'),
(1, 'CM_TrtmntFnc103', @scm, 'CM_TrtmntFnc103', 'Breast Surgery Service', 'Breast Surgery Service'),
(1, 'CM_TrtmntFnc104', @scm, 'CM_TrtmntFnc104', 'Colorectal Surgery Service', 'Colorectal Surgery Service'),
(1, 'CM_TrtmntFnc105', @scm, 'CM_TrtmntFnc105', 'Hepatobiliary and Pancreatic Surgery Service', 'Hepatobiliary and Pancreatic Surgery Service'),
(1, 'CM_TrtmntFnc106', @scm, 'CM_TrtmntFnc106', 'Upper Gastrointestinal Surgery Service', 'Upper Gastrointestinal Surgery Service'),
(1, 'CM_TrtmntFnc107', @scm, 'CM_TrtmntFnc107', 'Vascular Surgery Service', 'Vascular Surgery Service'),
(1, 'CM_TrtmntFnc108', @scm, 'CM_TrtmntFnc108', 'Spinal Surgery Service', 'Spinal Surgery Service'),
(1, 'CM_TrtmntFnc109', @scm, 'CM_TrtmntFnc109', 'Bariatric Surgery Service', 'Bariatric Surgery Service'),
(1, 'CM_TrtmntFnc110', @scm, 'CM_TrtmntFnc110', 'Trauma and Orthopaedic Service', 'Trauma and Orthopaedic Service'),
(1, 'CM_TrtmntFnc111', @scm, 'CM_TrtmntFnc111', 'Orthopaedic Service', 'Orthopaedic Service'),
(1, 'CM_TrtmntFnc113', @scm, 'CM_TrtmntFnc113', 'Endocrine Surgery Service', 'Endocrine Surgery Service'),
(1, 'CM_TrtmntFnc115', @scm, 'CM_TrtmntFnc115', 'Trauma Surgery Service', 'Trauma Surgery Service'),
(1, 'CM_TrtmntFnc120', @scm, 'CM_TrtmntFnc120', 'Ear Nose and Throat Service', 'Ear Nose and Throat Service'),
(1, 'CM_TrtmntFnc130', @scm, 'CM_TrtmntFnc130', 'Ophthalmology Service', 'Ophthalmology Service'),
(1, 'CM_TrtmntFnc140', @scm, 'CM_TrtmntFnc140', 'Oral Surgery Service', 'Oral Surgery Service'),
(1, 'CM_TrtmntFnc141', @scm, 'CM_TrtmntFnc141', 'Restorative Dentistry Service', 'Restorative Dentistry Service'),
(1, 'CM_TrtmntFnc143', @scm, 'CM_TrtmntFnc143', 'Orthodontic Service', 'Orthodontic Service'),
(1, 'CM_TrtmntFnc144', @scm, 'CM_TrtmntFnc144', 'Maxillofacial Surgery Service', 'Maxillofacial Surgery Service'),
(1, 'CM_TrtmntFnc145', @scm, 'CM_TrtmntFnc145', 'Oral and Maxillofacial Surgery Service', 'Oral and Maxillofacial Surgery Service'),
(1, 'CM_TrtmntFnc150', @scm, 'CM_TrtmntFnc150', 'Neurosurgical Service', 'Neurosurgical Service'),
(1, 'CM_TrtmntFnc160', @scm, 'CM_TrtmntFnc160', 'Plastic Surgery Service', 'Plastic Surgery Service'),
(1, 'CM_TrtmntFnc161', @scm, 'CM_TrtmntFnc161', 'Burns Care Service', 'Burns Care Service'),
(1, 'CM_TrtmntFnc170', @scm, 'CM_TrtmntFnc170', 'Cardiothoracic Surgery Service', 'Cardiothoracic Surgery Service'),
(1, 'CM_TrtmntFnc172', @scm, 'CM_TrtmntFnc172', 'Cardiac Surgery Service', 'Cardiac Surgery Service'),
(1, 'CM_TrtmntFnc173', @scm, 'CM_TrtmntFnc173', 'Thoracic Surgery Service', 'Thoracic Surgery Service'),
(1, 'CM_TrtmntFnc174', @scm, 'CM_TrtmntFnc174', 'Cardiothoracic Transplantation Service', 'Cardiothoracic Transplantation Service'),
(1, 'CM_TrtmntFnc191', @scm, 'CM_TrtmntFnc191', 'Pain Management Service', 'Pain Management Service'),
(1, 'CM_TrtmntFnc142', @scm, 'CM_TrtmntFnc142', 'Paediatric Dentistry Service', 'Paediatric Dentistry Service'),
(1, 'CM_TrtmntFnc171', @scm, 'CM_TrtmntFnc171', 'Paediatric Surgery Service', 'Paediatric Surgery Service'),
(1, 'CM_TrtmntFnc211', @scm, 'CM_TrtmntFnc211', 'Paediatric Urology Service', 'Paediatric Urology Service'),
(1, 'CM_TrtmntFnc212', @scm, 'CM_TrtmntFnc212', 'Paediatric Transplantation Surgery Service', 'Paediatric Transplantation Surgery Service'),
(1, 'CM_TrtmntFnc213', @scm, 'CM_TrtmntFnc213', 'Paediatric Gastrointestinal Surgery Service', 'Paediatric Gastrointestinal Surgery Service'),
(1, 'CM_TrtmntFnc214', @scm, 'CM_TrtmntFnc214', 'Paediatric Trauma and Orthopaedic Service', 'Paediatric Trauma and Orthopaedic Service'),
(1, 'CM_TrtmntFnc215', @scm, 'CM_TrtmntFnc215', 'Paediatric Ear Nose and Throat Service', 'Paediatric Ear Nose and Throat Service'),
(1, 'CM_TrtmntFnc216', @scm, 'CM_TrtmntFnc216', 'Paediatric Ophthalmology Service', 'Paediatric Ophthalmology Service'),
(1, 'CM_TrtmntFnc217', @scm, 'CM_TrtmntFnc217', 'Paediatric Oral and Maxillofacial Surgery Service', 'Paediatric Oral and Maxillofacial Surgery Service'),
(1, 'CM_TrtmntFnc218', @scm, 'CM_TrtmntFnc218', 'Paediatric Neurosurgery Service', 'Paediatric Neurosurgery Service'),
(1, 'CM_TrtmntFnc219', @scm, 'CM_TrtmntFnc219', 'Paediatric Plastic Surgery Service', 'Paediatric Plastic Surgery Service'),
(1, 'CM_TrtmntFnc220', @scm, 'CM_TrtmntFnc220', 'Paediatric Burns Care Service', 'Paediatric Burns Care Service'),
(1, 'CM_TrtmntFnc221', @scm, 'CM_TrtmntFnc221', 'Paediatric Cardiac Surgery Service', 'Paediatric Cardiac Surgery Service'),
(1, 'CM_TrtmntFnc222', @scm, 'CM_TrtmntFnc222', 'Paediatric Thoracic Surgery Service', 'Paediatric Thoracic Surgery Service'),
(1, 'CM_TrtmntFnc223', @scm, 'CM_TrtmntFnc223', 'Paediatric Epilepsy Service', 'Paediatric Epilepsy Service'),
(1, 'CM_TrtmntFnc230', @scm, 'CM_TrtmntFnc230', 'Paediatric Clinical Pharmacology Service', 'Paediatric Clinical Pharmacology Service'),
(1, 'CM_TrtmntFnc240', @scm, 'CM_TrtmntFnc240', 'Paediatric Palliative Medicine Service', 'Paediatric Palliative Medicine Service'),
(1, 'CM_TrtmntFnc241', @scm, 'CM_TrtmntFnc241', 'Paediatric Pain Management Service', 'Paediatric Pain Management Service'),
(1, 'CM_TrtmntFnc242', @scm, 'CM_TrtmntFnc242', 'Paediatric Intensive Care Service', 'Paediatric Intensive Care Service'),
(1, 'CM_TrtmntFnc250', @scm, 'CM_TrtmntFnc250', 'Paediatric Hepatology Service', 'Paediatric Hepatology Service'),
(1, 'CM_TrtmntFnc251', @scm, 'CM_TrtmntFnc251', 'Paediatric Gastroenterology Service', 'Paediatric Gastroenterology Service'),
(1, 'CM_TrtmntFnc252', @scm, 'CM_TrtmntFnc252', 'Paediatric Endocrinology Service', 'Paediatric Endocrinology Service'),
(1, 'CM_TrtmntFnc253', @scm, 'CM_TrtmntFnc253', 'Paediatric Clinical Haematology Service', 'Paediatric Clinical Haematology Service'),
(1, 'CM_TrtmntFnc254', @scm, 'CM_TrtmntFnc254', 'Paediatric Audio Vestibular Medicine Service', 'Paediatric Audio Vestibular Medicine Service'),
(1, 'CM_TrtmntFnc255', @scm, 'CM_TrtmntFnc255', 'Paediatric Clinical Immunology and Allergy Service', 'Paediatric Clinical Immunology and Allergy Service'),
(1, 'CM_TrtmntFnc256', @scm, 'CM_TrtmntFnc256', 'Paediatric Infectious Diseases Service', 'Paediatric Infectious Diseases Service'),
(1, 'CM_TrtmntFnc257', @scm, 'CM_TrtmntFnc257', 'Paediatric Dermatology Service', 'Paediatric Dermatology Service'),
(1, 'CM_TrtmntFnc258', @scm, 'CM_TrtmntFnc258', 'Paediatric Respiratory Medicine Service', 'Paediatric Respiratory Medicine Service'),
(1, 'CM_TrtmntFnc259', @scm, 'CM_TrtmntFnc259', 'Paediatric Nephrology Service', 'Paediatric Nephrology Service'),
(1, 'CM_TrtmntFnc260', @scm, 'CM_TrtmntFnc260', 'Paediatric Medical Oncology Service', 'Paediatric Medical Oncology Service'),
(1, 'CM_TrtmntFnc261', @scm, 'CM_TrtmntFnc261', 'Paediatric Inherited Metabolic Medicine Service', 'Paediatric Inherited Metabolic Medicine Service'),
(1, 'CM_TrtmntFnc262', @scm, 'CM_TrtmntFnc262', 'Paediatric Rheumatology Service', 'Paediatric Rheumatology Service'),
(1, 'CM_TrtmntFnc263', @scm, 'CM_TrtmntFnc263', 'Paediatric Diabetes Service', 'Paediatric Diabetes Service'),
(1, 'CM_TrtmntFnc264', @scm, 'CM_TrtmntFnc264', 'Paediatric Cystic Fibrosis Service', 'Paediatric Cystic Fibrosis Service'),
(1, 'CM_TrtmntFnc270', @scm, 'CM_TrtmntFnc270', 'Paediatric Emergency Medicine Service', 'Paediatric Emergency Medicine Service'),
(1, 'CM_TrtmntFnc280', @scm, 'CM_TrtmntFnc280', 'Paediatric Interventional Radiology Service', 'Paediatric Interventional Radiology Service'),
(1, 'CM_TrtmntFnc290', @scm, 'CM_TrtmntFnc290', 'Community Paediatric Service', 'Community Paediatric Service'),
(1, 'CM_TrtmntFnc291', @scm, 'CM_TrtmntFnc291', 'Paediatric Neurodisability Service', 'Paediatric Neurodisability Service'),
(1, 'CM_TrtmntFnc321', @scm, 'CM_TrtmntFnc321', 'Paediatric Cardiology Service', 'Paediatric Cardiology Service'),
(1, 'CM_TrtmntFnc421', @scm, 'CM_TrtmntFnc421', 'Paediatric Neurology Service', 'Paediatric Neurology Service'),
(1, 'CM_TrtmntFnc180', @scm, 'CM_TrtmntFnc180', 'Emergency Medicine Service', 'Emergency Medicine Service'),
(1, 'CM_TrtmntFnc190', @scm, 'CM_TrtmntFnc190', 'Anaesthetic Service', 'Anaesthetic Service'),
(1, 'CM_TrtmntFnc192', @scm, 'CM_TrtmntFnc192', 'Intensive Care Medicine Service', 'Intensive Care Medicine Service'),
(1, 'CM_TrtmntFnc200', @scm, 'CM_TrtmntFnc200', 'Aviation and Space Medicine Service', 'Aviation and Space Medicine Service'),
(1, 'CM_TrtmntFnc300', @scm, 'CM_TrtmntFnc300', 'General Internal Medicine Service', 'General Internal Medicine Service'),
(1, 'CM_TrtmntFnc301', @scm, 'CM_TrtmntFnc301', 'Gastroenterology Service', 'Gastroenterology Service'),
(1, 'CM_TrtmntFnc302', @scm, 'CM_TrtmntFnc302', 'Endocrinology Service', 'Endocrinology Service'),
(1, 'CM_TrtmntFnc303', @scm, 'CM_TrtmntFnc303', 'Clinical Haematology Service', 'Clinical Haematology Service'),
(1, 'CM_TrtmntFnc304', @scm, 'CM_TrtmntFnc304', 'Clinical Physiology Service', 'Clinical Physiology Service'),
(1, 'CM_TrtmntFnc305', @scm, 'CM_TrtmntFnc305', 'Clinical Pharmacology Service', 'Clinical Pharmacology Service'),
(1, 'CM_TrtmntFnc306', @scm, 'CM_TrtmntFnc306', 'Hepatology Service', 'Hepatology Service'),
(1, 'CM_TrtmntFnc307', @scm, 'CM_TrtmntFnc307', 'Diabetes Service', 'Diabetes Service'),
(1, 'CM_TrtmntFnc308', @scm, 'CM_TrtmntFnc308', 'Blood and Marrow Transplantation Service', 'Blood and Marrow Transplantation Service'),
(1, 'CM_TrtmntFnc309', @scm, 'CM_TrtmntFnc309', 'Haemophilia Service', 'Haemophilia Service'),
(1, 'CM_TrtmntFnc310', @scm, 'CM_TrtmntFnc310', 'Audio Vestibular Medicine Service', 'Audio Vestibular Medicine Service'),
(1, 'CM_TrtmntFnc311', @scm, 'CM_TrtmntFnc311', 'Clinical Genetics Service', 'Clinical Genetics Service'),
(1, 'CM_TrtmntFnc313', @scm, 'CM_TrtmntFnc313', 'Clinical Immunology and Allergy Service', 'Clinical Immunology and Allergy Service'),
(1, 'CM_TrtmntFnc314', @scm, 'CM_TrtmntFnc314', 'Rehabilitation Medicine Service', 'Rehabilitation Medicine Service'),
(1, 'CM_TrtmntFnc315', @scm, 'CM_TrtmntFnc315', 'Palliative Medicine Service', 'Palliative Medicine Service'),
(1, 'CM_TrtmntFnc316', @scm, 'CM_TrtmntFnc316', 'Clinical Immunology Service', 'Clinical Immunology Service'),
(1, 'CM_TrtmntFnc317', @scm, 'CM_TrtmntFnc317', 'Allergy Service', 'Allergy Service'),
(1, 'CM_TrtmntFnc318', @scm, 'CM_TrtmntFnc318', 'Intermediate Care Service', 'Intermediate Care Service'),
(1, 'CM_TrtmntFnc319', @scm, 'CM_TrtmntFnc319', 'Respite Care Service', 'Respite Care Service'),
(1, 'CM_TrtmntFnc320', @scm, 'CM_TrtmntFnc320', 'Cardiology Service', 'Cardiology Service'),
(1, 'CM_TrtmntFnc322', @scm, 'CM_TrtmntFnc322', 'Clinical Microbiology Service', 'Clinical Microbiology Service'),
(1, 'CM_TrtmntFnc323', @scm, 'CM_TrtmntFnc323', 'Spinal Injuries Service', 'Spinal Injuries Service'),
(1, 'CM_TrtmntFnc324', @scm, 'CM_TrtmntFnc324', 'Anticoagulant Service', 'Anticoagulant Service'),
(1, 'CM_TrtmntFnc325', @scm, 'CM_TrtmntFnc325', 'Sport and Exercise Medicine Service', 'Sport and Exercise Medicine Service'),
(1, 'CM_TrtmntFnc326', @scm, 'CM_TrtmntFnc326', 'Acute Internal Medicine Service', 'Acute Internal Medicine Service'),
(1, 'CM_TrtmntFnc327', @scm, 'CM_TrtmntFnc327', 'Cardiac Rehabilitation Service', 'Cardiac Rehabilitation Service'),
(1, 'CM_TrtmntFnc328', @scm, 'CM_TrtmntFnc328', 'Stroke Medicine Service', 'Stroke Medicine Service'),
(1, 'CM_TrtmntFnc329', @scm, 'CM_TrtmntFnc329', 'Transient Ischaemic Attack Service', 'Transient Ischaemic Attack Service'),
(1, 'CM_TrtmntFnc330', @scm, 'CM_TrtmntFnc330', 'Dermatology Service', 'Dermatology Service'),
(1, 'CM_TrtmntFnc331', @scm, 'CM_TrtmntFnc331', 'Congenital Heart Disease Service', 'Congenital Heart Disease Service'),
(1, 'CM_TrtmntFnc333', @scm, 'CM_TrtmntFnc333', 'Rare Disease Service', 'Rare Disease Service'),
(1, 'CM_TrtmntFnc335', @scm, 'CM_TrtmntFnc335', 'Inherited Metabolic Medicine Service', 'Inherited Metabolic Medicine Service'),
(1, 'CM_TrtmntFnc340', @scm, 'CM_TrtmntFnc340', 'Respiratory Medicine Service', 'Respiratory Medicine Service'),
(1, 'CM_TrtmntFnc341', @scm, 'CM_TrtmntFnc341', 'Respiratory Physiology Service', 'Respiratory Physiology Service'),
(1, 'CM_TrtmntFnc342', @scm, 'CM_TrtmntFnc342', 'Pulmonary Rehabilitation Service', 'Pulmonary Rehabilitation Service'),
(1, 'CM_TrtmntFnc343', @scm, 'CM_TrtmntFnc343', 'Adult Cystic Fibrosis Service', 'Adult Cystic Fibrosis Service'),
(1, 'CM_TrtmntFnc344', @scm, 'CM_TrtmntFnc344', 'Complex Specialised Rehabilitation Service', 'Complex Specialised Rehabilitation Service'),
(1, 'CM_TrtmntFnc345', @scm, 'CM_TrtmntFnc345', 'Specialist Rehabilitation Service', 'Specialist Rehabilitation Service'),
(1, 'CM_TrtmntFnc346', @scm, 'CM_TrtmntFnc346', 'Local Specialist Rehabilitation Service', 'Local Specialist Rehabilitation Service'),
(1, 'CM_TrtmntFnc347', @scm, 'CM_TrtmntFnc347', 'Sleep Medicine Service', 'Sleep Medicine Service'),
(1, 'CM_TrtmntFnc348', @scm, 'CM_TrtmntFnc348', 'Post-COVID-19 Syndrome Service', 'Post-COVID-19 Syndrome Service'),
(1, 'CM_TrtmntFnc350', @scm, 'CM_TrtmntFnc350', 'Infectious Diseases Service', 'Infectious Diseases Service'),
(1, 'CM_TrtmntFnc352', @scm, 'CM_TrtmntFnc352', 'Tropical Medicine Service', 'Tropical Medicine Service'),
(1, 'CM_TrtmntFnc360', @scm, 'CM_TrtmntFnc360', 'Genitourinary Medicine Service', 'Genitourinary Medicine Service'),
(1, 'CM_TrtmntFnc361', @scm, 'CM_TrtmntFnc361', 'Renal Medicine Service', 'Renal Medicine Service'),
(1, 'CM_TrtmntFnc370', @scm, 'CM_TrtmntFnc370', 'Medical Oncology Service', 'Medical Oncology Service'),
(1, 'CM_TrtmntFnc371', @scm, 'CM_TrtmntFnc371', 'Nuclear Medicine Service', 'Nuclear Medicine Service'),
(1, 'CM_TrtmntFnc400', @scm, 'CM_TrtmntFnc400', 'Neurology Service', 'Neurology Service'),
(1, 'CM_TrtmntFnc401', @scm, 'CM_TrtmntFnc401', 'Clinical Neurophysiology Service', 'Clinical Neurophysiology Service'),
(1, 'CM_TrtmntFnc410', @scm, 'CM_TrtmntFnc410', 'Rheumatology Service', 'Rheumatology Service'),
(1, 'CM_TrtmntFnc420', @scm, 'CM_TrtmntFnc420', 'Paediatric Service', 'Paediatric Service'),
(1, 'CM_TrtmntFnc422', @scm, 'CM_TrtmntFnc422', 'Neonatal Critical Care Service', 'Neonatal Critical Care Service'),
(1, 'CM_TrtmntFnc424', @scm, 'CM_TrtmntFnc424', 'Well Baby Service', 'Well Baby Service'),
(1, 'CM_TrtmntFnc430', @scm, 'CM_TrtmntFnc430', 'Elderly Medicine Service', 'Elderly Medicine Service'),
(1, 'CM_TrtmntFnc431', @scm, 'CM_TrtmntFnc431', 'Orthogeriatric Medicine Service', 'Orthogeriatric Medicine Service'),
(1, 'CM_TrtmntFnc450', @scm, 'CM_TrtmntFnc450', 'Dental Medicine Service', 'Dental Medicine Service'),
(1, 'CM_TrtmntFnc451', @scm, 'CM_TrtmntFnc451', 'Special Care Dentistry Service', 'Special Care Dentistry Service'),
(1, 'CM_TrtmntFnc460', @scm, 'CM_TrtmntFnc460', 'Medical Ophthalmology Service', 'Medical Ophthalmology Service'),
(1, 'CM_TrtmntFnc461', @scm, 'CM_TrtmntFnc461', 'Ophthalmic and Vision Science Service', 'Ophthalmic and Vision Science Service'),
(1, 'CM_TrtmntFnc501', @scm, 'CM_TrtmntFnc501', 'Obstetrics Service', 'Obstetrics Service'),
(1, 'CM_TrtmntFnc502', @scm, 'CM_TrtmntFnc502', 'Gynaecology Service', 'Gynaecology Service'),
(1, 'CM_TrtmntFnc503', @scm, 'CM_TrtmntFnc503', 'Gynaecological Oncology Service', 'Gynaecological Oncology Service'),
(1, 'CM_TrtmntFnc504', @scm, 'CM_TrtmntFnc504', 'Community Sexual and Reproductive Health Service', 'Community Sexual and Reproductive Health Service'),
(1, 'CM_TrtmntFnc505', @scm, 'CM_TrtmntFnc505', 'Fetal Medicine Service', 'Fetal Medicine Service'),
(1, 'CM_TrtmntFnc510', @scm, 'CM_TrtmntFnc510', 'Retired but retained for historical purposes', 'Retired but retained for historical purposes'),
(1, 'CM_TrtmntFnc520', @scm, 'CM_TrtmntFnc520', 'Retired but retained for historical purposes', 'Retired but retained for historical purposes'),
(1, 'CM_TrtmntFnc560', @scm, 'CM_TrtmntFnc560', 'Midwifery Service', 'Midwifery Service'),
(1, 'CM_TrtmntFnc610', @scm, 'CM_TrtmntFnc610', 'Retired but retained for historical purposes', 'Retired but retained for historical purposes'),
(1, 'CM_TrtmntFnc620', @scm, 'CM_TrtmntFnc620', 'Retired but retained for historical purposes', 'Retired but retained for historical purposes'),
(1, 'CM_TrtmntFnc656', @scm, 'CM_TrtmntFnc656', 'Clinical Psychology Service', 'Clinical Psychology Service'),
(1, 'CM_TrtmntFnc700', @scm, 'CM_TrtmntFnc700', 'Learning Disability Service', 'Learning Disability Service'),
(1, 'CM_TrtmntFnc710', @scm, 'CM_TrtmntFnc710', 'Adult Mental Health Service', 'Adult Mental Health Service'),
(1, 'CM_TrtmntFnc711', @scm, 'CM_TrtmntFnc711', 'Child and Adolescent Psychiatry Service', 'Child and Adolescent Psychiatry Service'),
(1, 'CM_TrtmntFnc712', @scm, 'CM_TrtmntFnc712', 'Forensic Psychiatry Service', 'Forensic Psychiatry Service'),
(1, 'CM_TrtmntFnc713', @scm, 'CM_TrtmntFnc713', 'Medical Psychotherapy Service', 'Medical Psychotherapy Service'),
(1, 'CM_TrtmntFnc715', @scm, 'CM_TrtmntFnc715', 'Old Age Psychiatry Service', 'Old Age Psychiatry Service'),
(1, 'CM_TrtmntFnc720', @scm, 'CM_TrtmntFnc720', 'Eating Disorders Service', 'Eating Disorders Service'),
(1, 'CM_TrtmntFnc721', @scm, 'CM_TrtmntFnc721', 'Addiction Service', 'Addiction Service'),
(1, 'CM_TrtmntFnc722', @scm, 'CM_TrtmntFnc722', 'Liaison Psychiatry Service', 'Liaison Psychiatry Service'),
(1, 'CM_TrtmntFnc723', @scm, 'CM_TrtmntFnc723', 'Psychiatric Intensive Care Service', 'Psychiatric Intensive Care Service'),
(1, 'CM_TrtmntFnc724', @scm, 'CM_TrtmntFnc724', 'Perinatal Mental Health Service', 'Perinatal Mental Health Service'),
(1, 'CM_TrtmntFnc725', @scm, 'CM_TrtmntFnc725', 'Mental Health Recovery and Rehabilitation Service', 'Mental Health Recovery and Rehabilitation Service'),
(1, 'CM_TrtmntFnc726', @scm, 'CM_TrtmntFnc726', 'Mental Health Dual Diagnosis Service', 'Mental Health Dual Diagnosis Service'),
(1, 'CM_TrtmntFnc727', @scm, 'CM_TrtmntFnc727', 'Dementia Assessment Service', 'Dementia Assessment Service'),
(1, 'CM_TrtmntFnc730', @scm, 'CM_TrtmntFnc730', 'Neuropsychiatry Service', 'Neuropsychiatry Service'),
(1, 'CM_TrtmntFnc800', @scm, 'CM_TrtmntFnc800', 'Clinical Oncology Service', 'Clinical Oncology Service'),
(1, 'CM_TrtmntFnc811', @scm, 'CM_TrtmntFnc811', 'Interventional Radiology Service', 'Interventional Radiology Service'),
(1, 'CM_TrtmntFnc812', @scm, 'CM_TrtmntFnc812', 'Diagnostic Imaging Service', 'Diagnostic Imaging Service'),
(1, 'CM_TrtmntFnc822', @scm, 'CM_TrtmntFnc822', 'Chemical Pathology Service', 'Chemical Pathology Service'),
(1, 'CM_TrtmntFnc832', @scm, 'CM_TrtmntFnc832', 'Retired but retained for historical purposes', 'Retired but retained for historical purposes'),
(1, 'CM_TrtmntFnc834', @scm, 'CM_TrtmntFnc834', 'Medical Virology Service', 'Medical Virology Service'),
(1, 'CM_TrtmntFnc650', @scm, 'CM_TrtmntFnc650', 'Physiotherapy Service', 'Physiotherapy Service'),
(1, 'CM_TrtmntFnc651', @scm, 'CM_TrtmntFnc651', 'Occupational Therapy Service', 'Occupational Therapy Service'),
(1, 'CM_TrtmntFnc652', @scm, 'CM_TrtmntFnc652', 'Speech and Language Therapy Service', 'Speech and Language Therapy Service'),
(1, 'CM_TrtmntFnc653', @scm, 'CM_TrtmntFnc653', 'Podiatry Service', 'Podiatry Service'),
(1, 'CM_TrtmntFnc654', @scm, 'CM_TrtmntFnc654', 'Dietetics Service', 'Dietetics Service'),
(1, 'CM_TrtmntFnc655', @scm, 'CM_TrtmntFnc655', 'Orthoptics Service', 'Orthoptics Service'),
(1, 'CM_TrtmntFnc657', @scm, 'CM_TrtmntFnc657', 'Prosthetics Service', 'Prosthetics Service'),
(1, 'CM_TrtmntFnc658', @scm, 'CM_TrtmntFnc658', 'Orthotics Service', 'Orthotics Service'),
(1, 'CM_TrtmntFnc659', @scm, 'CM_TrtmntFnc659', 'Dramatherapy Service', 'Dramatherapy Service'),
(1, 'CM_TrtmntFnc660', @scm, 'CM_TrtmntFnc660', 'Art Therapy Service', 'Art Therapy Service'),
(1, 'CM_TrtmntFnc661', @scm, 'CM_TrtmntFnc661', 'Music Therapy Service', 'Music Therapy Service'),
(1, 'CM_TrtmntFnc662', @scm, 'CM_TrtmntFnc662', 'Optometry Service', 'Optometry Service'),
(1, 'CM_TrtmntFnc663', @scm, 'CM_TrtmntFnc663', 'Podiatric Surgery Service', 'Podiatric Surgery Service'),
(1, 'CM_TrtmntFnc670', @scm, 'CM_TrtmntFnc670', 'Urological Physiology Service', 'Urological Physiology Service'),
(1, 'CM_TrtmntFnc673', @scm, 'CM_TrtmntFnc673', 'Vascular Physiology Service', 'Vascular Physiology Service'),
(1, 'CM_TrtmntFnc675', @scm, 'CM_TrtmntFnc675', 'Cardiac Physiology Service', 'Cardiac Physiology Service'),
(1, 'CM_TrtmntFnc677', @scm, 'CM_TrtmntFnc677', 'Gastrointestinal Physiology Service', 'Gastrointestinal Physiology Service'),
(1, 'CM_TrtmntFnc840', @scm, 'CM_TrtmntFnc840', 'Audiology Service', 'Audiology Service'),
(1, 'CM_TrtmntFnc920', @scm, 'CM_TrtmntFnc920', 'Diabetic Education Service', 'Diabetic Education Service'),
(1, 'CM_TrtmntFnc990', @scm, 'CM_TrtmntFnc990', 'Retired but retained for historical purposes', 'Retired but retained for historical purposes'),
(1, 'CM_TrtmntFnc147', @scm, 'CM_TrtmntFnc147', 'Periodontics', 'Periodontics'),
(1, 'CM_TrtmntFnc820', @scm, 'CM_TrtmntFnc820', 'General Pathology', 'General Pathology'),
(1, 'CM_TrtmntFnc821', @scm, 'CM_TrtmntFnc821', 'Blood Transfusion', 'Blood Transfusion'),
(1, 'CM_TrtmntFnc823', @scm, 'CM_TrtmntFnc823', 'Haematology', 'Haematology'),
(1, 'CM_TrtmntFnc824', @scm, 'CM_TrtmntFnc824', 'Histopathology', 'Histopathology'),
(1, 'CM_TrtmntFnc830', @scm, 'CM_TrtmntFnc830', 'Immunopathology', 'Immunopathology'),
(1, 'CM_TrtmntFnc831', @scm, 'CM_TrtmntFnc831', 'Medical Microbiology and Virology', 'Medical Microbiology and Virology'),
(1, 'CM_TrtmntFnc833', @scm, 'CM_TrtmntFnc833', 'Medical Microbiology', 'Medical Microbiology'),
(1, 'CM_TrtmntFnc900', @scm, 'CM_TrtmntFnc900', 'Community Medicine', 'Community Medicine'),
(1, 'CM_TrtmntFnc901', @scm, 'CM_TrtmntFnc901', 'Occupational Medicine', 'Occupational Medicine'),
(1, 'CM_TrtmntFnc902', @scm, 'CM_TrtmntFnc902', 'Community Health Services Dental', 'Community Health Services Dental'),
(1, 'CM_TrtmntFnc903', @scm, 'CM_TrtmntFnc903', 'Public Health Medicine', 'Public Health Medicine'),
(1, 'CM_TrtmntFnc950', @scm, 'CM_TrtmntFnc950', 'Nursing', 'Nursing'),
(1, 'CM_TrtmntFnc960', @scm, 'CM_TrtmntFnc960', 'Allied Health Professional', 'Allied Health Professional'),
(1, 'CM_TrtmntFnc990', @scm, 'CM_TrtmntFnc990', 'Joint Consultant Clinics', 'Joint Consultant Clinics'),
-- Added 17 Jul 2022
(1, 'CM_TrtmntFnc600', @scm, 'CM_TrtmntFnc600', 'General Medical Practice', 'General Medical Practice'),
(1, 'CM_TrtmntFnc810', @scm, 'CM_TrtmntFnc810', 'Radiology', 'Radiology');
