-- ****************************************************
-- ** REQUIRES
-- ****************************************************

-- Get scheme id
SELECT @scm := dbid FROM concept WHERE id = 'CM_DiscoveryCode';

-- Code scheme prefix entries
INSERT IGNORE INTO concept
(document, id, scheme, code, name, description)
VALUES
-- GENERAL/GLOBAL --
(1, 'CM_Org_Kings', @scm, 'CM_Org_Kings', 'Kings College', 'Kings College Hospital, London'),
(1, 'CM_Sys_PIMS', @scm, 'CM_Sys_PIMS', 'PIMS', 'PIMS system'),
(1, 'KingsPIMS', @scm, 'KingsPIMS', 'Kings Local Codes', 'Kings PIMS local code scheme');

INSERT IGNORE INTO concept_property_data
(`dbid`, `group`, `property`, `value`)
SELECT c.dbid, 0 AS `group`, p.dbid AS `property`, 'KC_' AS `value`
FROM concept c
         JOIN concept p ON p.id = 'code_prefix'
WHERE c.id = 'KingsPIMS';

-- ******************** Gender ********************

-- Context
INSERT INTO map_context_meta (provider, `system`, `schema`, `table`, `column`, node)
VALUES ('CM_Org_Kings', 'CM_Sys_PIMS', null, null, 'gender', '/KINGS/PIMS/GNDR');    -- Local

-- Property
INSERT INTO map_node_meta (node, concept)
VALUES ('/KINGS/PIMS/GNDR', 'DM_gender');

-- Value maps
INSERT INTO map_node_value_meta
(node, value, scheme, concept)
VALUES
('/KINGS/PIMS/GNDR', 'F', 'KingsPIMS', 'FHIR_AG_female'),
('/KINGS/PIMS/GNDR', 'M', 'KingsPIMS', 'FHIR_AG_male'),
('/KINGS/PIMS/GNDR', 'U', 'KingsPIMS', 'FHIR_AG_unknown'),
('/KINGS/PIMS/GNDR', 'I', 'KingsPIMS', 'FHIR_AG_other');

-- ******************** Religion ********************

-- Context
INSERT INTO map_context_meta (provider, `system`, `schema`, `table`, `column`, node)
VALUES ('CM_Org_Kings', 'CM_Sys_PIMS', null, null, 'religion', '/KINGS/PIMS/RLGN');    -- Local

-- Property
INSERT INTO map_node_meta (node, concept)
VALUES ('/KINGS/PIMS/RLGN', 'DM_religion');

-- Value maps
INSERT INTO map_node_value_meta
(node, value, scheme, concept)
VALUES
    ('/KINGS/PIMS/RLGN', 'A1',  'KingsPIMS', 'CM_ReligionA1'),
    ('/KINGS/PIMS/RLGN', 'B1',  'KingsPIMS', 'CM_ReligionB1'),
    ('/KINGS/PIMS/RLGN', 'C1',  'KingsPIMS', 'CM_ReligionC1'),
    ('/KINGS/PIMS/RLGN', 'C12', 'KingsPIMS', 'CM_ReligionC12'),
    ('/KINGS/PIMS/RLGN', 'C16', 'KingsPIMS', 'CM_ReligionC16'),
    ('/KINGS/PIMS/RLGN', 'C19', 'KingsPIMS', 'CM_ReligionC19'),
    ('/KINGS/PIMS/RLGN', 'C21', 'KingsPIMS', 'CM_ReligionC21'),
    ('/KINGS/PIMS/RLGN', 'C22', 'KingsPIMS', 'CM_ReligionC22'),
    ('/KINGS/PIMS/RLGN', 'C23', 'KingsPIMS', 'CM_ReligionC23'),
    ('/KINGS/PIMS/RLGN', 'C24', 'KingsPIMS', 'CM_ReligionC24'),
    ('/KINGS/PIMS/RLGN', 'C25', 'KingsPIMS', 'CM_ReligionC25'),
    ('/KINGS/PIMS/RLGN', 'C26', 'KingsPIMS', 'CM_ReligionC26'),
    ('/KINGS/PIMS/RLGN', 'C34', 'KingsPIMS', 'CM_ReligionC34'),
    ('/KINGS/PIMS/RLGN', 'C4',  'KingsPIMS', 'CM_ReligionC4'),
    ('/KINGS/PIMS/RLGN', 'C41', 'KingsPIMS', 'CM_ReligionC41'),
    ('/KINGS/PIMS/RLGN', 'C44', 'KingsPIMS', 'CM_ReligionC44'),
    ('/KINGS/PIMS/RLGN', 'C46', 'KingsPIMS', 'CM_ReligionC46'),
    ('/KINGS/PIMS/RLGN', 'C49', 'KingsPIMS', 'CM_ReligionC49'),
    ('/KINGS/PIMS/RLGN', 'C51', 'KingsPIMS', 'CM_ReligionC51'),
    ('/KINGS/PIMS/RLGN', 'C54', 'KingsPIMS', 'CM_ReligionC54'),
    ('/KINGS/PIMS/RLGN', 'C58', 'KingsPIMS', 'CM_ReligionC58'),
    ('/KINGS/PIMS/RLGN', 'C59', 'KingsPIMS', 'CM_ReligionC59'),
    ('/KINGS/PIMS/RLGN', 'C6',  'KingsPIMS', 'CM_ReligionC6'),
    ('/KINGS/PIMS/RLGN', 'C61', 'KingsPIMS', 'CM_ReligionC61'),
    ('/KINGS/PIMS/RLGN', 'C62', 'KingsPIMS', 'CM_ReligionC62'),
    ('/KINGS/PIMS/RLGN', 'C63', 'KingsPIMS', 'CM_ReligionC63'),
    ('/KINGS/PIMS/RLGN', 'C67', 'KingsPIMS', 'CM_ReligionC67'),
    ('/KINGS/PIMS/RLGN', 'C70', 'KingsPIMS', 'CM_ReligionC70'),
    ('/KINGS/PIMS/RLGN', 'C73', 'KingsPIMS', 'CM_ReligionC73'),
    ('/KINGS/PIMS/RLGN', 'C78', 'KingsPIMS', 'CM_ReligionC78'),
    ('/KINGS/PIMS/RLGN', 'C79', 'KingsPIMS', 'CM_ReligionC79'),
    ('/KINGS/PIMS/RLGN', 'C8',  'KingsPIMS', 'CM_ReligionC8'),
    ('/KINGS/PIMS/RLGN', 'D1',  'KingsPIMS', 'CM_ReligionD1'),
    ('/KINGS/PIMS/RLGN', 'F1',  'KingsPIMS', 'CM_ReligionF1'),
    ('/KINGS/PIMS/RLGN', 'F5',  'KingsPIMS', 'CM_ReligionF5'),
    ('/KINGS/PIMS/RLGN', 'F7',  'KingsPIMS', 'CM_ReligionF7'),
    ('/KINGS/PIMS/RLGN', 'F8',  'KingsPIMS', 'CM_ReligionF8'),
    ('/KINGS/PIMS/RLGN', 'G1',  'KingsPIMS', 'CM_ReligionG1'),
    ('/KINGS/PIMS/RLGN', 'H1',  'KingsPIMS', 'CM_ReligionH1'),
    ('/KINGS/PIMS/RLGN', 'I1',  'KingsPIMS', 'CM_ReligionI1'),
    ('/KINGS/PIMS/RLGN', 'K27', 'KingsPIMS', 'CM_ReligionK27'),
    ('/KINGS/PIMS/RLGN', 'L1',  'KingsPIMS', 'CM_ReligionL1'),
    ('/KINGS/PIMS/RLGN', 'L2',  'KingsPIMS', 'CM_ReligionL2'),
    ('/KINGS/PIMS/RLGN', 'M1',  'KingsPIMS', 'CM_ReligionM1'),
    ('/KINGS/PIMS/RLGN', 'N1',  'KingsPIMS', 'CM_ReligionN1');


-- ******************** Patient Class ********************          No longer being done - Will has workaround (Andy Thomas - 14/01/2022)

-- CONFLICT WITH ENCOUNTER CLASS/PATIENT CLASSIFICATION????

-- Concepts
/*SELECT @scm := dbid FROM concept WHERE id = 'KingsPIMS';

INSERT IGNORE INTO concept
(document, id, scheme, code, name, description)
VALUES
    (1, 'KC_Enc_Inpatient', @scm,  'KC_Enc_Inpatient',  'Inpatient', 'Inpatient'),
    (1, 'KC_Enc_Emergency', @scm,  'KC_Enc_Emergency',  'Emergency department', 'Emergency department'),
    (1, 'KC_Enc_Outpatient', @scm, 'KC_Enc_Outpatient', 'Outpatient', 'Outpatient');

-- Context
INSERT INTO map_context_meta (provider, `system`, `schema`, `table`, `column`, node)
VALUES ('CM_Org_Kings', 'CM_Sys_PIMS', null, null, 'patient_class', '/KINGS/PIMS/PTNT_CLSS');    -- Local

-- Property
INSERT INTO map_node_meta (node, concept)
VALUES ('/KINGS/PIMS/PTNT_CLSS', 'DM_admissionPatientClassification');

-- Value maps
INSERT INTO map_node_value_meta
(node, value, scheme, concept)
VALUES
    ('/KINGS/PIMS/PTNT_CLSS', 'I', 'KingsPIMS', 'KC_Enc_Inpatient'),
    ('/KINGS/PIMS/PTNT_CLSS', 'E', 'KingsPIMS', 'KC_Enc_Emergency'),
    ('/KINGS/PIMS/PTNT_CLSS', 'O', 'KingsPIMS', 'KC_Enc_Outpatient');*/

-- ******************** Admission Type (Method) ********************

-- Context
INSERT INTO map_context_meta (provider, `system`, `schema`, `table`, `column`, node)
VALUES ('CM_Org_Kings', 'CM_Sys_PIMS', null, null, 'admission_method_code', '/KINGS/PIMS/ADMSSN_MTHD');    -- Local

-- Property
INSERT INTO map_node_meta (node, concept)
VALUES ('/KINGS/PIMS/ADMSSN_MTHD', 'DM_methodOfAdmssion');

-- Value maps
INSERT INTO map_node_value_meta
(node, value, scheme, concept)
VALUES
    ('/KINGS/PIMS/ADMSSN_MTHD', '11', 'KingsPIMS', 'CM_AdmMethWa'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '12', 'KingsPIMS', 'CM_AdmMetBooked'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '13', 'KingsPIMS', 'CM_AdmMetPlanned'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '21', 'KingsPIMS', 'CM_AdmMetCasSame'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '22', 'KingsPIMS', 'CM_AdmMetGpDirect'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '23', 'KingsPIMS', 'CM_AdmMetBedBureau'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '24', 'KingsPIMS', 'CM_AdmMetConClin'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '25', 'KingsPIMS', 'CM_AdmMetMheCrisis'),
    -- ('/KINGS/PIMS/ADMSSN_MTHD', '28', 'KingsPIMS', 'CM_AdmMetEMore'),           -- 2D replaces 28 in "Method of admission" - Confirmed by Jack 14/1/22
    ('/KINGS/PIMS/ADMSSN_MTHD', '2A', 'KingsPIMS', 'CM_AdmMetCasElsewhere'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '2B', 'KingsPIMS', 'CM_AdmMetHosTran'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '2C', 'KingsPIMS', 'CM_AdmMetBBhok'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '2D', 'KingsPIMS', 'CM_AdmMetEMore'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '31', 'KingsPIMS', 'CM_AdmMetMatAP'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '32', 'KingsPIMS', 'CM_AdmMetMatPP'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '81', 'KingsPIMS', 'CM_AdmNonETransfer'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '82', 'KingsPIMS', 'CM_AdmMetBirthHere'),
    ('/KINGS/PIMS/ADMSSN_MTHD', '83', 'KingsPIMS', 'CM_AdmMetBirthOut');

-- ******************** Ethnicity ********************

-- Context
INSERT INTO map_context_meta (provider, `system`, `schema`, `table`, `column`, node)
VALUES ('CM_Org_Kings', 'CM_Sys_PIMS', null, null, 'ethnicity', '/KINGS/PIMS/ETHNC_CTGRY');    -- Local

-- Property
INSERT INTO map_node_meta (node, concept)
VALUES ('/KINGS/PIMS/ETHNC_CTGRY', 'DM_ethnicity');

-- Value maps
INSERT INTO map_node_value_meta
(node, value, scheme, concept)
VALUES
    ('/KINGS/PIMS/ETHNC_CTGRY', 'A', 'KingsPIMS', 'CM_EthnicityA'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'B', 'KingsPIMS', 'CM_EthnicityB'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'C', 'KingsPIMS', 'CM_EthnicityC'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'D', 'KingsPIMS', 'CM_EthnicityD'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'E', 'KingsPIMS', 'CM_EthnicityE'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'F', 'KingsPIMS', 'CM_EthnicityF'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'G', 'KingsPIMS', 'CM_EthnicityG'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'H', 'KingsPIMS', 'CM_EthnicityH'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'J', 'KingsPIMS', 'CM_EthnicityJ'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'K', 'KingsPIMS', 'CM_EthnicityK'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'L', 'KingsPIMS', 'CM_EthnicityL'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'M', 'KingsPIMS', 'CM_EthnicityM'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'N', 'KingsPIMS', 'CM_EthnicityN'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'P', 'KingsPIMS', 'CM_EthnicityP'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'R', 'KingsPIMS', 'CM_EthnicityR'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'S', 'KingsPIMS', 'CM_EthnicityS'),
    ('/KINGS/PIMS/ETHNC_CTGRY', 'Z', 'KingsPIMS', 'CM_EthnicityZ'),
    ('/KINGS/PIMS/ETHNC_CTGRY', '99', 'KingsPIMS', 'CM_Ethnicity99');

-- ******************** Admission Source ********************

-- Context
INSERT INTO map_context_meta (provider, `system`, `schema`, `table`, `column`, node)
VALUES ('CM_Org_Kings', 'CM_Sys_PIMS', null, null, 'admission_source_code', '/KINGS/PIMS/ADMSSN_SRC');    -- Local

-- Property
INSERT INTO map_node_meta (node, concept)
VALUES ('/KINGS/PIMS/ADMSSN_SRC', 'DM_sourceOfAdmission');

-- Value maps
INSERT INTO map_node_value_meta
(node, value, scheme, concept)
VALUES
    ('/KINGS/PIMS/ADMSSN_SRC', '19', 'KingsPIMS', 'CM_SrcAdmUsual'),
    ('/KINGS/PIMS/ADMSSN_SRC', '29', 'KingsPIMS', 'CM_SrcAdmTempR'),
    ('/KINGS/PIMS/ADMSSN_SRC', '39', 'KingsPIMS', 'CM_SrcAdmPePoCo'),
    ('/KINGS/PIMS/ADMSSN_SRC', '49', 'KingsPIMS', 'CM_SrcAdmPSyHosp'),
    ('/KINGS/PIMS/ADMSSN_SRC', '51', 'KingsPIMS', 'CM_SrcAdmA1'),
    ('/KINGS/PIMS/ADMSSN_SRC', '52', 'KingsPIMS', 'CM_SrcAdmA2'),
    ('/KINGS/PIMS/ADMSSN_SRC', '53', 'KingsPIMS', 'CM_SrcAdmA3'),
    ('/KINGS/PIMS/ADMSSN_SRC', '54', 'KingsPIMS', 'CM_SrcAdmA4'),
    ('/KINGS/PIMS/ADMSSN_SRC', '65', 'KingsPIMS', 'CM_SrcAdmA5'),
    ('/KINGS/PIMS/ADMSSN_SRC', '66', 'KingsPIMS', 'CM_SrcAdmA6'),
    ('/KINGS/PIMS/ADMSSN_SRC', '79', 'KingsPIMS', 'CM_SrcAdmA7'),
    ('/KINGS/PIMS/ADMSSN_SRC', '85', 'KingsPIMS', 'CM_SrcAdmA8'),
    -- ('/KINGS/PIMS/ADMSSN_SRC', '86', 'KingsPIMS', 'CM_SrcAdmA8'),    -- NO 86 National Code - Should be 85 (above) - Confirmed Jack Barker 14/1/22
    ('/KINGS/PIMS/ADMSSN_SRC', '87', 'KingsPIMS', 'CM_SrcAdmA9'),
    ('/KINGS/PIMS/ADMSSN_SRC', '88', 'KingsPIMS', 'CM_SrcAsmA10');


-- ******************** Encounter Class ********************

-- Context
INSERT INTO map_context_meta (provider, `system`, `schema`, `table`, `column`, node)
VALUES ('CM_Org_Kings', 'CM_Sys_PIMS', null, null, 'encounter_type', '/KINGS/PIMS/ENCNTR_TYP');    -- Local

-- Property
INSERT INTO map_node_meta (node, concept)
VALUES ('/KINGS/PIMS/ENCNTR_TYP', 'DM_admissionPatientClassification');

-- Value maps
INSERT INTO map_node_value_meta
(node, value, scheme, concept)
VALUES
    ('/KINGS/PIMS/ENCNTR_TYP', '1', 'KingsPIMS', 'CM_AdmClassOrdinary'),
    ('/KINGS/PIMS/ENCNTR_TYP', '2', 'KingsPIMS', 'CM_AdmClassDayCase'),
    ('/KINGS/PIMS/ENCNTR_TYP', '3', 'KingsPIMS', 'CM_AdmClassRegularDay'),
    ('/KINGS/PIMS/ENCNTR_TYP', '4', 'KingsPIMS', 'CM_AdmClassRegularNight');
    -- ('/KINGS/PIMS/ENCNTR_TYP', '5/99', 'KingsPIMS', 'CM_AdmClassMotherBabyDelivery/?????????????????'); -- Replaced by 1 in TIE - Jack Barker 14/1/22

-- ******************** Discharge Disposition ********************

-- Context
INSERT INTO map_context_meta (provider, `system`, `schema`, `table`, `column`, node)
VALUES ('CM_Org_Kings', 'CM_Sys_PIMS', null, null, 'discharge_method', '/KINGS/PIMS/DSCHRG_MTHD');    -- Local

-- Property
INSERT INTO map_node_meta (node, concept)
VALUES ('/KINGS/PIMS/DSCHRG_MTHD', 'DM_hasDischargeMethod');

-- Value maps
INSERT INTO map_node_value_meta
(node, value, scheme, concept)
VALUES
    ('/KINGS/PIMS/DSCHRG_MTHD', '1', 'KingsPIMS', 'CM_DisMethod1'),
    ('/KINGS/PIMS/DSCHRG_MTHD', '2', 'KingsPIMS', 'CM_DisMethod2'),
    ('/KINGS/PIMS/DSCHRG_MTHD', '3', 'KingsPIMS', 'CM_DisMethod3'),
    ('/KINGS/PIMS/DSCHRG_MTHD', '4', 'KingsPIMS', 'CM_DisMethod4'),
    ('/KINGS/PIMS/DSCHRG_MTHD', '5', 'KingsPIMS', 'CM_DisMethod5');
    -- ('/KINGS/PIMS/DSCHRG_MTHD', '99', 'KingsPIMS', '??????????????????');   -- Replaced by 1 in TIE - Jack Barker 14/1/22


-- ******************** Discharge Destination ********************

-- Context
INSERT INTO map_context_meta (provider, `system`, `schema`, `table`, `column`, node)
VALUES ('CM_Org_Kings', 'CM_Sys_PIMS', null, null, 'discharge_destination_code', '/KINGS/PIMS/DSCHRG_DSTNTN');    -- Local

-- Property
INSERT INTO map_node_meta (node, concept)
VALUES ('/KINGS/PIMS/DSCHRG_DSTNTN', 'DM_hasDischargeDestination');

-- Value maps
INSERT INTO map_node_value_meta
(node, value, scheme, concept)
VALUES
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '19', 'KingsPIMS', 'CM_SrcAdmUsual'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '29', 'KingsPIMS', 'CM_SrcAdmTempR'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '30', 'KingsPIMS', 'CM_DisDest30'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '37', 'KingsPIMS', 'CM_SrcAdmCo'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '38', 'KingsPIMS', 'CM_DisDest38'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '48', 'KingsPIMS', 'CM_DisDest48'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '49', 'KingsPIMS', 'CM_DisDest49'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '50', 'KingsPIMS', 'CM_DisDest50'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '51', 'KingsPIMS', 'CM_DisDest51'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '52', 'KingsPIMS', 'CM_SrcAdmA2'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '53', 'KingsPIMS', 'CM_SrcAdmA3'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '54', 'KingsPIMS', 'CM_SrcAdmA4'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '65', 'KingsPIMS', 'CM_SrcAdmA5'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '66', 'KingsPIMS', 'CM_SrcAdmA6'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '79', 'KingsPIMS', 'CM_DisDest79'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '84', 'KingsPIMS', 'CM_DisDest84'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '85', 'KingsPIMS', 'CM_SrcAdmA8'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '87', 'KingsPIMS', 'CM_SrcAdmA9'),
    ('/KINGS/PIMS/DSCHRG_DSTNTN', '88', 'KingsPIMS', 'CM_SrcAsmA10');

-- ******************** Treatment Function ********************

-- Context
INSERT INTO map_context_meta (provider, `system`, `schema`, `table`, `column`, node)
VALUES ('CM_Org_Kings', 'CM_Sys_PIMS', null, null, 'treatment_function_code', '/KINGS/PIMS/TRTMNT_FNCTN');    -- Local

-- Property
INSERT INTO map_node_meta (node, concept)
VALUES ('/KINGS/PIMS/TRTMNT_FNCTN', 'DM_treatmentFunctionAdmit');

-- Value maps
INSERT INTO map_node_value_meta
(node, value, scheme, concept)
VALUES
    ('/KINGS/PIMS/TRTMNT_FNCTN', '100', 'KingsPIMS', 'CM_TrtmntFnc100'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '101', 'KingsPIMS', 'CM_TrtmntFnc101'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '102', 'KingsPIMS', 'CM_TrtmntFnc102'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '103', 'KingsPIMS', 'CM_TrtmntFnc103'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '104', 'KingsPIMS', 'CM_TrtmntFnc104'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '105', 'KingsPIMS', 'CM_TrtmntFnc105'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '106', 'KingsPIMS', 'CM_TrtmntFnc106'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '107', 'KingsPIMS', 'CM_TrtmntFnc107'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '109', 'KingsPIMS', 'CM_TrtmntFnc109'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '110', 'KingsPIMS', 'CM_TrtmntFnc110'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '111', 'KingsPIMS', 'CM_TrtmntFnc111'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '113', 'KingsPIMS', 'CM_TrtmntFnc113'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '120', 'KingsPIMS', 'CM_TrtmntFnc120'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '130', 'KingsPIMS', 'CM_TrtmntFnc130'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '140', 'KingsPIMS', 'CM_TrtmntFnc140'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '141', 'KingsPIMS', 'CM_TrtmntFnc141'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '650', 'KingsPIMS', 'CM_TrtmntFnc650'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '142', 'KingsPIMS', 'CM_TrtmntFnc142'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '143', 'KingsPIMS', 'CM_TrtmntFnc143'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '144', 'KingsPIMS', 'CM_TrtmntFnc144'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '145', 'KingsPIMS', 'CM_TrtmntFnc145'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '150', 'KingsPIMS', 'CM_TrtmntFnc150'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '253', 'KingsPIMS', 'CM_TrtmntFnc253'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '160', 'KingsPIMS', 'CM_TrtmntFnc160'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '170', 'KingsPIMS', 'CM_TrtmntFnc170'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '171', 'KingsPIMS', 'CM_TrtmntFnc171'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '180', 'KingsPIMS', 'CM_TrtmntFnc180'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '190', 'KingsPIMS', 'CM_TrtmntFnc190'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '192', 'KingsPIMS', 'CM_TrtmntFnc192'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '211', 'KingsPIMS', 'CM_TrtmntFnc211'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '213', 'KingsPIMS', 'CM_TrtmntFnc213'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '212', 'KingsPIMS', 'CM_TrtmntFnc212'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '214', 'KingsPIMS', 'CM_TrtmntFnc214'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '216', 'KingsPIMS', 'CM_TrtmntFnc216'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '218', 'KingsPIMS', 'CM_TrtmntFnc218'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '219', 'KingsPIMS', 'CM_TrtmntFnc219'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '223', 'KingsPIMS', 'CM_TrtmntFnc223'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '250', 'KingsPIMS', 'CM_TrtmntFnc250'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '251', 'KingsPIMS', 'CM_TrtmntFnc251'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '252', 'KingsPIMS', 'CM_TrtmntFnc252'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '303', 'KingsPIMS', 'CM_TrtmntFnc303'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '255', 'KingsPIMS', 'CM_TrtmntFnc255'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '256', 'KingsPIMS', 'CM_TrtmntFnc256'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '257', 'KingsPIMS', 'CM_TrtmntFnc257'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '258', 'KingsPIMS', 'CM_TrtmntFnc258'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '260', 'KingsPIMS', 'CM_TrtmntFnc260'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '261', 'KingsPIMS', 'CM_TrtmntFnc261'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '262', 'KingsPIMS', 'CM_TrtmntFnc262'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '263', 'KingsPIMS', 'CM_TrtmntFnc263'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '264', 'KingsPIMS', 'CM_TrtmntFnc264'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '270', 'KingsPIMS', 'CM_TrtmntFnc270'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '280', 'KingsPIMS', 'CM_TrtmntFnc280'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '291', 'KingsPIMS', 'CM_TrtmntFnc291'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '301', 'KingsPIMS', 'CM_TrtmntFnc301'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '300', 'KingsPIMS', 'CM_TrtmntFnc300'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '302', 'KingsPIMS', 'CM_TrtmntFnc302'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '306', 'KingsPIMS', 'CM_TrtmntFnc306'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '307', 'KingsPIMS', 'CM_TrtmntFnc307'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '308', 'KingsPIMS', 'CM_TrtmntFnc308'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '310', 'KingsPIMS', 'CM_TrtmntFnc310'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '311', 'KingsPIMS', 'CM_TrtmntFnc311'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '314', 'KingsPIMS', 'CM_TrtmntFnc314'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '315', 'KingsPIMS', 'CM_TrtmntFnc315'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '316', 'KingsPIMS', 'CM_TrtmntFnc316'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '317', 'KingsPIMS', 'CM_TrtmntFnc317'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '320', 'KingsPIMS', 'CM_TrtmntFnc320'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '321', 'KingsPIMS', 'CM_TrtmntFnc321'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '322', 'KingsPIMS', 'CM_TrtmntFnc322'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '324', 'KingsPIMS', 'CM_TrtmntFnc324'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '326', 'KingsPIMS', 'CM_TrtmntFnc326'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '328', 'KingsPIMS', 'CM_TrtmntFnc328'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '329', 'KingsPIMS', 'CM_TrtmntFnc329'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '330', 'KingsPIMS', 'CM_TrtmntFnc330'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '340', 'KingsPIMS', 'CM_TrtmntFnc340'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '343', 'KingsPIMS', 'CM_TrtmntFnc343'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '348', 'KingsPIMS', 'CM_TrtmntFnc348'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '350', 'KingsPIMS', 'CM_TrtmntFnc350'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '360', 'KingsPIMS', 'CM_TrtmntFnc360'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '361', 'KingsPIMS', 'CM_TrtmntFnc361'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '370', 'KingsPIMS', 'CM_TrtmntFnc370'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '371', 'KingsPIMS', 'CM_TrtmntFnc371'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '400', 'KingsPIMS', 'CM_TrtmntFnc400'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '401', 'KingsPIMS', 'CM_TrtmntFnc401'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '410', 'KingsPIMS', 'CM_TrtmntFnc410'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '420', 'KingsPIMS', 'CM_TrtmntFnc420'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '421', 'KingsPIMS', 'CM_TrtmntFnc421'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '422', 'KingsPIMS', 'CM_TrtmntFnc422'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '424', 'KingsPIMS', 'CM_TrtmntFnc424'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '430', 'KingsPIMS', 'CM_TrtmntFnc430'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '431', 'KingsPIMS', 'CM_TrtmntFnc431'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '450', 'KingsPIMS', 'CM_TrtmntFnc450'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '451', 'KingsPIMS', 'CM_TrtmntFnc451'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '461', 'KingsPIMS', 'CM_TrtmntFnc461'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '503', 'KingsPIMS', 'CM_TrtmntFnc503'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '502', 'KingsPIMS', 'CM_TrtmntFnc502'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '501', 'KingsPIMS', 'CM_TrtmntFnc501'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '505', 'KingsPIMS', 'CM_TrtmntFnc505'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '560', 'KingsPIMS', 'CM_TrtmntFnc560'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '651', 'KingsPIMS', 'CM_TrtmntFnc651'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '652', 'KingsPIMS', 'CM_TrtmntFnc652'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '812', 'KingsPIMS', 'CM_TrtmntFnc812'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '653', 'KingsPIMS', 'CM_TrtmntFnc653'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '654', 'KingsPIMS', 'CM_TrtmntFnc654'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '655', 'KingsPIMS', 'CM_TrtmntFnc655'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '730', 'KingsPIMS', 'CM_TrtmntFnc730'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '658', 'KingsPIMS', 'CM_TrtmntFnc658'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '670', 'KingsPIMS', 'CM_TrtmntFnc670'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '673', 'KingsPIMS', 'CM_TrtmntFnc673'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '675', 'KingsPIMS', 'CM_TrtmntFnc675'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '677', 'KingsPIMS', 'CM_TrtmntFnc677'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '710', 'KingsPIMS', 'CM_TrtmntFnc710'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '711', 'KingsPIMS', 'CM_TrtmntFnc711'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '712', 'KingsPIMS', 'CM_TrtmntFnc712'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '713', 'KingsPIMS', 'CM_TrtmntFnc713'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '724', 'KingsPIMS', 'CM_TrtmntFnc724'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '727', 'KingsPIMS', 'CM_TrtmntFnc727'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '800', 'KingsPIMS', 'CM_TrtmntFnc800'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '811', 'KingsPIMS', 'CM_TrtmntFnc811'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '822', 'KingsPIMS', 'CM_TrtmntFnc822'),
    ('/KINGS/PIMS/TRTMNT_FNCTN', '840', 'KingsPIMS', 'CM_TrtmntFnc840');

-- ******************** Language ********************

-- Concepts
SELECT @scm := dbid FROM concept WHERE id = 'KingsPIMS';

INSERT IGNORE INTO concept
(document, id, scheme, code, name, description)
VALUES
(1, 'KC_Lang_AAR', @scm, 'KC_Lang_AAR', 'Afar', 'Afar'),
(1, 'KC_Lang_ABK', @scm, 'KC_Lang_ABK', 'Abkhazian', 'Abkhazian'),
(1, 'KC_Lang_ACE', @scm, 'KC_Lang_ACE', 'Achinese', 'Achinese'),
(1, 'KC_Lang_ACH', @scm, 'KC_Lang_ACH', 'Acoli', 'Acoli'),
(1, 'KC_Lang_ADA', @scm, 'KC_Lang_ADA', 'Adangme', 'Adangme'),
(1, 'KC_Lang_ADY', @scm, 'KC_Lang_ADY', 'Adyghe; Adygei', 'Adyghe; Adygei'),
(1, 'KC_Lang_AFA', @scm, 'KC_Lang_AFA', 'Afro-Asiatic languages', 'Afro-Asiatic languages'),
(1, 'KC_Lang_AFH', @scm, 'KC_Lang_AFH', 'Afrihili', 'Afrihili'),
(1, 'KC_Lang_AFR', @scm, 'KC_Lang_AFR', 'Afrikaans', 'Afrikaans'),
(1, 'KC_Lang_AIN', @scm, 'KC_Lang_AIN', 'Ainu', 'Ainu'),
(1, 'KC_Lang_AKA', @scm, 'KC_Lang_AKA', 'Akan', 'Akan'),
(1, 'KC_Lang_AKK', @scm, 'KC_Lang_AKK', 'Akkadian', 'Akkadian'),
(1, 'KC_Lang_ALB', @scm, 'KC_Lang_ALB', 'Albanian', 'Albanian'),
(1, 'KC_Lang_ALE', @scm, 'KC_Lang_ALE', 'Aleut', 'Aleut'),
(1, 'KC_Lang_ALG', @scm, 'KC_Lang_ALG', 'Algonquian languages', 'Algonquian languages'),
(1, 'KC_Lang_ALT', @scm, 'KC_Lang_ALT', 'Southern Altai', 'Southern Altai'),
(1, 'KC_Lang_AMH', @scm, 'KC_Lang_AMH', 'Amharic', 'Amharic'),
(1, 'KC_Lang_ANG', @scm, 'KC_Lang_ANG', 'English, Old (ca.450-1100)', 'English, Old (ca.450-1100)'),
(1, 'KC_Lang_ANP', @scm, 'KC_Lang_ANP', 'Angika', 'Angika'),
(1, 'KC_Lang_APA', @scm, 'KC_Lang_APA', 'Apache languages', 'Apache languages'),
(1, 'KC_Lang_ARA', @scm, 'KC_Lang_ARA', 'Arabic', 'Arabic'),
(1, 'KC_Lang_ARC', @scm, 'KC_Lang_ARC', 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)', 'Official Aramaic (700-300 BCE); Imperial Aramaic (700-300 BCE)'),
(1, 'KC_Lang_ARG', @scm, 'KC_Lang_ARG', 'Aragonese', 'Aragonese'),
(1, 'KC_Lang_ARM', @scm, 'KC_Lang_ARM', 'Armenian', 'Armenian'),
(1, 'KC_Lang_ARN', @scm, 'KC_Lang_ARN', 'Mapudungun; Mapuche', 'Mapudungun; Mapuche'),
(1, 'KC_Lang_ARP', @scm, 'KC_Lang_ARP', 'Arapaho', 'Arapaho'),
(1, 'KC_Lang_ART', @scm, 'KC_Lang_ART', 'Artificial languages', 'Artificial languages'),
(1, 'KC_Lang_ARW', @scm, 'KC_Lang_ARW', 'Arawak', 'Arawak'),
(1, 'KC_Lang_ASM', @scm, 'KC_Lang_ASM', 'Assamese', 'Assamese'),
(1, 'KC_Lang_AST', @scm, 'KC_Lang_AST', 'Asturian; Bable; Leonese; Asturleonese', 'Asturian; Bable; Leonese; Asturleonese'),
(1, 'KC_Lang_ATH', @scm, 'KC_Lang_ATH', 'Athapascan languages', 'Athapascan languages'),
(1, 'KC_Lang_AUS', @scm, 'KC_Lang_AUS', 'Australian languages', 'Australian languages'),
(1, 'KC_Lang_AVA', @scm, 'KC_Lang_AVA', 'Avaric', 'Avaric'),
(1, 'KC_Lang_AVE', @scm, 'KC_Lang_AVE', 'Avestan', 'Avestan'),
(1, 'KC_Lang_AWA', @scm, 'KC_Lang_AWA', 'Awadhi', 'Awadhi'),
(1, 'KC_Lang_AYM', @scm, 'KC_Lang_AYM', 'Aymara', 'Aymara'),
(1, 'KC_Lang_AZE', @scm, 'KC_Lang_AZE', 'Azerbaijani', 'Azerbaijani'),
(1, 'KC_Lang_BAD', @scm, 'KC_Lang_BAD', 'Banda languages', 'Banda languages'),
(1, 'KC_Lang_BAI', @scm, 'KC_Lang_BAI', 'Bamileke languages', 'Bamileke languages'),
(1, 'KC_Lang_BAK', @scm, 'KC_Lang_BAK', 'Bashkir', 'Bashkir'),
(1, 'KC_Lang_BAL', @scm, 'KC_Lang_BAL', 'Baluchi', 'Baluchi'),
(1, 'KC_Lang_BAM', @scm, 'KC_Lang_BAM', 'Bambara', 'Bambara'),
(1, 'KC_Lang_BAN', @scm, 'KC_Lang_BAN', 'Balinese', 'Balinese'),
(1, 'KC_Lang_BAQ', @scm, 'KC_Lang_BAQ', 'Basque', 'Basque'),
(1, 'KC_Lang_BAS', @scm, 'KC_Lang_BAS', 'Basa', 'Basa'),
(1, 'KC_Lang_BAT', @scm, 'KC_Lang_BAT', 'Baltic languages', 'Baltic languages'),
(1, 'KC_Lang_BEJ', @scm, 'KC_Lang_BEJ', 'Beja; Bedawiyet', 'Beja; Bedawiyet'),
(1, 'KC_Lang_BEL', @scm, 'KC_Lang_BEL', 'Belarusian', 'Belarusian'),
(1, 'KC_Lang_BEM', @scm, 'KC_Lang_BEM', 'Bemba', 'Bemba'),
(1, 'KC_Lang_BEN', @scm, 'KC_Lang_BEN', 'Bengali', 'Bengali'),
(1, 'KC_Lang_BER', @scm, 'KC_Lang_BER', 'Berber languages', 'Berber languages'),
(1, 'KC_Lang_BHO', @scm, 'KC_Lang_BHO', 'Bhojpuri', 'Bhojpuri'),
(1, 'KC_Lang_BIH', @scm, 'KC_Lang_BIH', 'Bihari languages', 'Bihari languages'),
(1, 'KC_Lang_BIK', @scm, 'KC_Lang_BIK', 'Bikol', 'Bikol'),
(1, 'KC_Lang_BIN', @scm, 'KC_Lang_BIN', 'Bini; Edo', 'Bini; Edo'),
(1, 'KC_Lang_BIS', @scm, 'KC_Lang_BIS', 'Bislama', 'Bislama'),
(1, 'KC_Lang_BLA', @scm, 'KC_Lang_BLA', 'Siksika', 'Siksika'),
(1, 'KC_Lang_BNT', @scm, 'KC_Lang_BNT', 'Bantu languages', 'Bantu languages'),
(1, 'KC_Lang_BOD', @scm, 'KC_Lang_BOD', 'Tibetan', 'Tibetan'),
(1, 'KC_Lang_BOS', @scm, 'KC_Lang_BOS', 'Bosnian', 'Bosnian'),
(1, 'KC_Lang_BRA', @scm, 'KC_Lang_BRA', 'Braj', 'Braj'),
(1, 'KC_Lang_BRE', @scm, 'KC_Lang_BRE', 'Breton', 'Breton'),
(1, 'KC_Lang_BTK', @scm, 'KC_Lang_BTK', 'Batak languages', 'Batak languages'),
(1, 'KC_Lang_BUA', @scm, 'KC_Lang_BUA', 'Buriat', 'Buriat'),
(1, 'KC_Lang_BUG', @scm, 'KC_Lang_BUG', 'Buginese', 'Buginese'),
(1, 'KC_Lang_BUL', @scm, 'KC_Lang_BUL', 'Bulgarian', 'Bulgarian'),
(1, 'KC_Lang_BUR', @scm, 'KC_Lang_BUR', 'Burmese', 'Burmese'),
(1, 'KC_Lang_BYN', @scm, 'KC_Lang_BYN', 'Blin; Bilin', 'Blin; Bilin'),
(1, 'KC_Lang_CAD', @scm, 'KC_Lang_CAD', 'Caddo', 'Caddo'),
(1, 'KC_Lang_CAI', @scm, 'KC_Lang_CAI', 'Central American Indian languages', 'Central American Indian languages'),
(1, 'KC_Lang_CAR', @scm, 'KC_Lang_CAR', 'Galibi Carib', 'Galibi Carib'),
(1, 'KC_Lang_CAT', @scm, 'KC_Lang_CAT', 'Catalan; Valencian', 'Catalan; Valencian'),
(1, 'KC_Lang_CAU', @scm, 'KC_Lang_CAU', 'Caucasian languages', 'Caucasian languages'),
(1, 'KC_Lang_CEB', @scm, 'KC_Lang_CEB', 'Cebuano', 'Cebuano'),
(1, 'KC_Lang_CEL', @scm, 'KC_Lang_CEL', 'Celtic languages', 'Celtic languages'),
(1, 'KC_Lang_CES', @scm, 'KC_Lang_CES', 'Czech', 'Czech'),
(1, 'KC_Lang_CHA', @scm, 'KC_Lang_CHA', 'Chamorro', 'Chamorro'),
(1, 'KC_Lang_CHB', @scm, 'KC_Lang_CHB', 'Chibcha', 'Chibcha'),
(1, 'KC_Lang_CHE', @scm, 'KC_Lang_CHE', 'Chechen', 'Chechen'),
(1, 'KC_Lang_CHG', @scm, 'KC_Lang_CHG', 'Chagatai', 'Chagatai'),
(1, 'KC_Lang_CHI', @scm, 'KC_Lang_CHI', 'Chinese', 'Chinese'),
(1, 'KC_Lang_CHK', @scm, 'KC_Lang_CHK', 'Chuukese', 'Chuukese'),
(1, 'KC_Lang_CHM', @scm, 'KC_Lang_CHM', 'Mari', 'Mari'),
(1, 'KC_Lang_CHN', @scm, 'KC_Lang_CHN', 'Chinook jargon', 'Chinook jargon'),
(1, 'KC_Lang_CHO', @scm, 'KC_Lang_CHO', 'Choctaw', 'Choctaw'),
(1, 'KC_Lang_CHP', @scm, 'KC_Lang_CHP', 'Chipewyan; Dene Suline', 'Chipewyan; Dene Suline'),
(1, 'KC_Lang_CHR', @scm, 'KC_Lang_CHR', 'Cherokee', 'Cherokee'),
(1, 'KC_Lang_CHU', @scm, 'KC_Lang_CHU', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic', 'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'),
(1, 'KC_Lang_CHV', @scm, 'KC_Lang_CHV', 'Chuvash', 'Chuvash'),
(1, 'KC_Lang_CHY', @scm, 'KC_Lang_CHY', 'Cheyenne', 'Cheyenne'),
(1, 'KC_Lang_CMC', @scm, 'KC_Lang_CMC', 'Chamic languages', 'Chamic languages'),
(1, 'KC_Lang_CNR', @scm, 'KC_Lang_CNR', 'Montenegrin', 'Montenegrin'),
(1, 'KC_Lang_COP', @scm, 'KC_Lang_COP', 'Coptic', 'Coptic'),
(1, 'KC_Lang_COR', @scm, 'KC_Lang_COR', 'Cornish', 'Cornish'),
(1, 'KC_Lang_COS', @scm, 'KC_Lang_COS', 'Corsican', 'Corsican'),
(1, 'KC_Lang_CPE', @scm, 'KC_Lang_CPE', 'Creoles and pidgins, English based', 'Creoles and pidgins, English based'),
(1, 'KC_Lang_CPF', @scm, 'KC_Lang_CPF', 'Creoles and pidgins, French-based', 'Creoles and pidgins, French-based'),
(1, 'KC_Lang_CPP', @scm, 'KC_Lang_CPP', 'Creoles and pidgins, Portuguese-based', 'Creoles and pidgins, Portuguese-based'),
(1, 'KC_Lang_CRE', @scm, 'KC_Lang_CRE', 'Cree', 'Cree'),
(1, 'KC_Lang_CRH', @scm, 'KC_Lang_CRH', 'Crimean Tatar; Crimean Turkish', 'Crimean Tatar; Crimean Turkish'),
(1, 'KC_Lang_CRP', @scm, 'KC_Lang_CRP', 'Creoles and pidgins', 'Creoles and pidgins'),
(1, 'KC_Lang_CSB', @scm, 'KC_Lang_CSB', 'Kashubian', 'Kashubian'),
(1, 'KC_Lang_CUS', @scm, 'KC_Lang_CUS', 'Cushitic languages', 'Cushitic languages'),
(1, 'KC_Lang_CYM', @scm, 'KC_Lang_CYM', 'Welsh', 'Welsh'),
(1, 'KC_Lang_CZE', @scm, 'KC_Lang_CZE', 'Czech', 'Czech'),
(1, 'KC_Lang_DAK', @scm, 'KC_Lang_DAK', 'Dakota', 'Dakota'),
(1, 'KC_Lang_DAN', @scm, 'KC_Lang_DAN', 'Danish', 'Danish'),
(1, 'KC_Lang_DAR', @scm, 'KC_Lang_DAR', 'Dargwa', 'Dargwa'),
(1, 'KC_Lang_DAY', @scm, 'KC_Lang_DAY', 'Land Dayak languages', 'Land Dayak languages'),
(1, 'KC_Lang_DEL', @scm, 'KC_Lang_DEL', 'Delaware', 'Delaware'),
(1, 'KC_Lang_DEN', @scm, 'KC_Lang_DEN', 'Slave (Athapascan)', 'Slave (Athapascan)'),
(1, 'KC_Lang_DEU', @scm, 'KC_Lang_DEU', 'German', 'German'),
(1, 'KC_Lang_DGR', @scm, 'KC_Lang_DGR', 'Dogrib', 'Dogrib'),
(1, 'KC_Lang_DIN', @scm, 'KC_Lang_DIN', 'Dinka', 'Dinka'),
(1, 'KC_Lang_DIV', @scm, 'KC_Lang_DIV', 'Divehi; Dhivehi; Maldivian', 'Divehi; Dhivehi; Maldivian'),
(1, 'KC_Lang_DOI', @scm, 'KC_Lang_DOI', 'Dogri', 'Dogri'),
(1, 'KC_Lang_DRA', @scm, 'KC_Lang_DRA', 'Dravidian languages', 'Dravidian languages'),
(1, 'KC_Lang_DSB', @scm, 'KC_Lang_DSB', 'Lower Sorbian', 'Lower Sorbian'),
(1, 'KC_Lang_DUA', @scm, 'KC_Lang_DUA', 'Duala', 'Duala'),
(1, 'KC_Lang_DUM', @scm, 'KC_Lang_DUM', 'Dutch, Middle (ca.1050-1350)', 'Dutch, Middle (ca.1050-1350)'),
(1, 'KC_Lang_DUT', @scm, 'KC_Lang_DUT', 'Dutch; Flemish', 'Dutch; Flemish'),
(1, 'KC_Lang_DYU', @scm, 'KC_Lang_DYU', 'Dyula', 'Dyula'),
(1, 'KC_Lang_DZO', @scm, 'KC_Lang_DZO', 'Dzongkha', 'Dzongkha'),
(1, 'KC_Lang_EFI', @scm, 'KC_Lang_EFI', 'Efik', 'Efik'),
(1, 'KC_Lang_EGY', @scm, 'KC_Lang_EGY', 'Egyptian (Ancient)', 'Egyptian (Ancient)'),
(1, 'KC_Lang_EKA', @scm, 'KC_Lang_EKA', 'Ekajuk', 'Ekajuk'),
(1, 'KC_Lang_ELL', @scm, 'KC_Lang_ELL', 'Greek, Modern (1453-)', 'Greek, Modern (1453-)'),
(1, 'KC_Lang_ELX', @scm, 'KC_Lang_ELX', 'Elamite', 'Elamite'),
(1, 'KC_Lang_ENG', @scm, 'KC_Lang_ENG', 'English', 'English'),
(1, 'KC_Lang_ENM', @scm, 'KC_Lang_ENM', 'English, Middle (1100-1500)', 'English, Middle (1100-1500)'),
(1, 'KC_Lang_EPO', @scm, 'KC_Lang_EPO', 'Esperanto', 'Esperanto'),
(1, 'KC_Lang_EST', @scm, 'KC_Lang_EST', 'Estonian', 'Estonian'),
(1, 'KC_Lang_EUS', @scm, 'KC_Lang_EUS', 'Basque', 'Basque'),
(1, 'KC_Lang_EWE', @scm, 'KC_Lang_EWE', 'Ewe', 'Ewe'),
(1, 'KC_Lang_EWO', @scm, 'KC_Lang_EWO', 'Ewondo', 'Ewondo'),
(1, 'KC_Lang_FAN', @scm, 'KC_Lang_FAN', 'Fang', 'Fang'),
(1, 'KC_Lang_FAO', @scm, 'KC_Lang_FAO', 'Faroese', 'Faroese'),
(1, 'KC_Lang_FAS', @scm, 'KC_Lang_FAS', 'Persian', 'Persian'),
(1, 'KC_Lang_FAT', @scm, 'KC_Lang_FAT', 'Fanti', 'Fanti'),
(1, 'KC_Lang_FIJ', @scm, 'KC_Lang_FIJ', 'Fijian', 'Fijian'),
(1, 'KC_Lang_FIL', @scm, 'KC_Lang_FIL', 'Filipino; Pilipino', 'Filipino; Pilipino'),
(1, 'KC_Lang_FIN', @scm, 'KC_Lang_FIN', 'Finnish', 'Finnish'),
(1, 'KC_Lang_FIU', @scm, 'KC_Lang_FIU', 'Finno-Ugrian languages', 'Finno-Ugrian languages'),
(1, 'KC_Lang_FON', @scm, 'KC_Lang_FON', 'Fon', 'Fon'),
(1, 'KC_Lang_FRA', @scm, 'KC_Lang_FRA', 'French', 'French'),
(1, 'KC_Lang_FRE', @scm, 'KC_Lang_FRE', 'French', 'French'),
(1, 'KC_Lang_FRM', @scm, 'KC_Lang_FRM', 'French, Middle (ca.1400-1600)', 'French, Middle (ca.1400-1600)'),
(1, 'KC_Lang_FRO', @scm, 'KC_Lang_FRO', 'French, Old (842-ca.1400)', 'French, Old (842-ca.1400)'),
(1, 'KC_Lang_FRR', @scm, 'KC_Lang_FRR', 'Northern Frisian', 'Northern Frisian'),
(1, 'KC_Lang_FRS', @scm, 'KC_Lang_FRS', 'Eastern Frisian', 'Eastern Frisian'),
(1, 'KC_Lang_FRY', @scm, 'KC_Lang_FRY', 'Western Frisian', 'Western Frisian'),
(1, 'KC_Lang_FUL', @scm, 'KC_Lang_FUL', 'Fulah', 'Fulah'),
(1, 'KC_Lang_FUR', @scm, 'KC_Lang_FUR', 'Friulian', 'Friulian'),
(1, 'KC_Lang_GAA', @scm, 'KC_Lang_GAA', 'Ga', 'Ga'),
(1, 'KC_Lang_GAY', @scm, 'KC_Lang_GAY', 'Gayo', 'Gayo'),
(1, 'KC_Lang_GBA', @scm, 'KC_Lang_GBA', 'Gbaya', 'Gbaya'),
(1, 'KC_Lang_GEM', @scm, 'KC_Lang_GEM', 'Germanic languages', 'Germanic languages'),
(1, 'KC_Lang_GEO', @scm, 'KC_Lang_GEO', 'Georgian', 'Georgian'),
(1, 'KC_Lang_GER', @scm, 'KC_Lang_GER', 'German', 'German'),
(1, 'KC_Lang_GEZ', @scm, 'KC_Lang_GEZ', 'Geez', 'Geez'),
(1, 'KC_Lang_GIL', @scm, 'KC_Lang_GIL', 'Gilbertese', 'Gilbertese'),
(1, 'KC_Lang_GLA', @scm, 'KC_Lang_GLA', 'Gaelic; Scottish Gaelic', 'Gaelic; Scottish Gaelic'),
(1, 'KC_Lang_GLE', @scm, 'KC_Lang_GLE', 'Irish', 'Irish'),
(1, 'KC_Lang_GLG', @scm, 'KC_Lang_GLG', 'Galician', 'Galician'),
(1, 'KC_Lang_GLV', @scm, 'KC_Lang_GLV', 'Manx', 'Manx'),
(1, 'KC_Lang_GMH', @scm, 'KC_Lang_GMH', 'German, Middle High (ca.1050-1500)', 'German, Middle High (ca.1050-1500)'),
(1, 'KC_Lang_GOH', @scm, 'KC_Lang_GOH', 'German, Old High (ca.750-1050)', 'German, Old High (ca.750-1050)'),
(1, 'KC_Lang_GON', @scm, 'KC_Lang_GON', 'Gondi', 'Gondi'),
(1, 'KC_Lang_GOR', @scm, 'KC_Lang_GOR', 'Gorontalo', 'Gorontalo'),
(1, 'KC_Lang_GOT', @scm, 'KC_Lang_GOT', 'Gothic', 'Gothic'),
(1, 'KC_Lang_GRB', @scm, 'KC_Lang_GRB', 'Grebo', 'Grebo'),
(1, 'KC_Lang_GRC', @scm, 'KC_Lang_GRC', 'Greek, Ancient (to 1453)', 'Greek, Ancient (to 1453)'),
(1, 'KC_Lang_GRE', @scm, 'KC_Lang_GRE', 'Greek, Modern (1453-)', 'Greek, Modern (1453-)'),
(1, 'KC_Lang_GRN', @scm, 'KC_Lang_GRN', 'Guarani', 'Guarani'),
(1, 'KC_Lang_GSW', @scm, 'KC_Lang_GSW', 'Swiss German; Alemannic; Alsatian', 'Swiss German; Alemannic; Alsatian'),
(1, 'KC_Lang_GUJ', @scm, 'KC_Lang_GUJ', 'Gujarati', 'Gujarati'),
(1, 'KC_Lang_GWI', @scm, 'KC_Lang_GWI', 'Gwich''in', 'Gwich''in'),
(1, 'KC_Lang_HAI', @scm, 'KC_Lang_HAI', 'Haida', 'Haida'),
(1, 'KC_Lang_HAT', @scm, 'KC_Lang_HAT', 'Haitian; Haitian Creole', 'Haitian; Haitian Creole'),
(1, 'KC_Lang_HAU', @scm, 'KC_Lang_HAU', 'Hausa', 'Hausa'),
(1, 'KC_Lang_HAW', @scm, 'KC_Lang_HAW', 'Hawaiian', 'Hawaiian'),
(1, 'KC_Lang_HEB', @scm, 'KC_Lang_HEB', 'Hebrew', 'Hebrew'),
(1, 'KC_Lang_HER', @scm, 'KC_Lang_HER', 'Herero', 'Herero'),
(1, 'KC_Lang_HIL', @scm, 'KC_Lang_HIL', 'Hiligaynon', 'Hiligaynon'),
(1, 'KC_Lang_HIM', @scm, 'KC_Lang_HIM', 'Himachali languages; Western Pahari languages', 'Himachali languages; Western Pahari languages'),
(1, 'KC_Lang_HIN', @scm, 'KC_Lang_HIN', 'Hindi', 'Hindi'),
(1, 'KC_Lang_HIT', @scm, 'KC_Lang_HIT', 'Hittite', 'Hittite'),
(1, 'KC_Lang_HMN', @scm, 'KC_Lang_HMN', 'Hmong; Mong', 'Hmong; Mong'),
(1, 'KC_Lang_HMO', @scm, 'KC_Lang_HMO', 'Hiri Motu', 'Hiri Motu'),
(1, 'KC_Lang_HRV', @scm, 'KC_Lang_HRV', 'Croatian', 'Croatian'),
(1, 'KC_Lang_HSB', @scm, 'KC_Lang_HSB', 'Upper Sorbian', 'Upper Sorbian'),
(1, 'KC_Lang_HUN', @scm, 'KC_Lang_HUN', 'Hungarian', 'Hungarian'),
(1, 'KC_Lang_HUP', @scm, 'KC_Lang_HUP', 'Hupa', 'Hupa'),
(1, 'KC_Lang_HYE', @scm, 'KC_Lang_HYE', 'Armenian', 'Armenian'),
(1, 'KC_Lang_IBA', @scm, 'KC_Lang_IBA', 'Iban', 'Iban'),
(1, 'KC_Lang_IBO', @scm, 'KC_Lang_IBO', 'Igbo', 'Igbo'),
(1, 'KC_Lang_ICE', @scm, 'KC_Lang_ICE', 'Icelandic', 'Icelandic'),
(1, 'KC_Lang_IDO', @scm, 'KC_Lang_IDO', 'Ido', 'Ido'),
(1, 'KC_Lang_III', @scm, 'KC_Lang_III', 'Sichuan Yi; Nuosu', 'Sichuan Yi; Nuosu'),
(1, 'KC_Lang_IJO', @scm, 'KC_Lang_IJO', 'Ijo languages', 'Ijo languages'),
(1, 'KC_Lang_IKU', @scm, 'KC_Lang_IKU', 'Inuktitut', 'Inuktitut'),
(1, 'KC_Lang_ILE', @scm, 'KC_Lang_ILE', 'Interlingue; Occidental', 'Interlingue; Occidental'),
(1, 'KC_Lang_ILO', @scm, 'KC_Lang_ILO', 'Iloko', 'Iloko'),
(1, 'KC_Lang_INA', @scm, 'KC_Lang_INA', 'Interlingua (International Auxiliary Language Association)', 'Interlingua (International Auxiliary Language Association)'),
(1, 'KC_Lang_INC', @scm, 'KC_Lang_INC', 'Indic languages', 'Indic languages'),
(1, 'KC_Lang_IND', @scm, 'KC_Lang_IND', 'Indonesian', 'Indonesian'),
(1, 'KC_Lang_INE', @scm, 'KC_Lang_INE', 'Indo-European languages', 'Indo-European languages'),
(1, 'KC_Lang_INH', @scm, 'KC_Lang_INH', 'Ingush', 'Ingush'),
(1, 'KC_Lang_IPK', @scm, 'KC_Lang_IPK', 'Inupiaq', 'Inupiaq'),
(1, 'KC_Lang_IRA', @scm, 'KC_Lang_IRA', 'Iranian languages', 'Iranian languages'),
(1, 'KC_Lang_IRO', @scm, 'KC_Lang_IRO', 'Iroquoian languages', 'Iroquoian languages'),
(1, 'KC_Lang_ISL', @scm, 'KC_Lang_ISL', 'Icelandic', 'Icelandic'),
(1, 'KC_Lang_ITA', @scm, 'KC_Lang_ITA', 'Italian', 'Italian'),
(1, 'KC_Lang_JAV', @scm, 'KC_Lang_JAV', 'Javanese', 'Javanese'),
(1, 'KC_Lang_JBO', @scm, 'KC_Lang_JBO', 'Lojban', 'Lojban'),
(1, 'KC_Lang_JPN', @scm, 'KC_Lang_JPN', 'Japanese', 'Japanese'),
(1, 'KC_Lang_JPR', @scm, 'KC_Lang_JPR', 'Judeo-Persian', 'Judeo-Persian'),
(1, 'KC_Lang_JRB', @scm, 'KC_Lang_JRB', 'Judeo-Arabic', 'Judeo-Arabic'),
(1, 'KC_Lang_KAA', @scm, 'KC_Lang_KAA', 'Kara-Kalpak', 'Kara-Kalpak'),
(1, 'KC_Lang_KAB', @scm, 'KC_Lang_KAB', 'Kabyle', 'Kabyle'),
(1, 'KC_Lang_KAC', @scm, 'KC_Lang_KAC', 'Kachin; Jingpho', 'Kachin; Jingpho'),
(1, 'KC_Lang_KAL', @scm, 'KC_Lang_KAL', 'Kalaallisut; Greenlandic', 'Kalaallisut; Greenlandic'),
(1, 'KC_Lang_KAM', @scm, 'KC_Lang_KAM', 'Kamba', 'Kamba'),
(1, 'KC_Lang_KAN', @scm, 'KC_Lang_KAN', 'Kannada', 'Kannada'),
(1, 'KC_Lang_KAR', @scm, 'KC_Lang_KAR', 'Karen languages', 'Karen languages'),
(1, 'KC_Lang_KAS', @scm, 'KC_Lang_KAS', 'Kashmiri', 'Kashmiri'),
(1, 'KC_Lang_KAT', @scm, 'KC_Lang_KAT', 'Georgian', 'Georgian'),
(1, 'KC_Lang_KAU', @scm, 'KC_Lang_KAU', 'Kanuri', 'Kanuri'),
(1, 'KC_Lang_KAW', @scm, 'KC_Lang_KAW', 'Kawi', 'Kawi'),
(1, 'KC_Lang_KAZ', @scm, 'KC_Lang_KAZ', 'Kazakh', 'Kazakh'),
(1, 'KC_Lang_KBD', @scm, 'KC_Lang_KBD', 'Kabardian', 'Kabardian'),
(1, 'KC_Lang_KHA', @scm, 'KC_Lang_KHA', 'Khasi', 'Khasi'),
(1, 'KC_Lang_KHI', @scm, 'KC_Lang_KHI', 'Khoisan languages', 'Khoisan languages'),
(1, 'KC_Lang_KHM', @scm, 'KC_Lang_KHM', 'Central Khmer', 'Central Khmer'),
(1, 'KC_Lang_KHO', @scm, 'KC_Lang_KHO', 'Khotanese; Sakan', 'Khotanese; Sakan'),
(1, 'KC_Lang_KIK', @scm, 'KC_Lang_KIK', 'Kikuyu; Gikuyu', 'Kikuyu; Gikuyu'),
(1, 'KC_Lang_KIN', @scm, 'KC_Lang_KIN', 'Kinyarwanda', 'Kinyarwanda'),
(1, 'KC_Lang_KIR', @scm, 'KC_Lang_KIR', 'Kirghiz; Kyrgyz', 'Kirghiz; Kyrgyz'),
(1, 'KC_Lang_KMB', @scm, 'KC_Lang_KMB', 'Kimbundu', 'Kimbundu'),
(1, 'KC_Lang_KOK', @scm, 'KC_Lang_KOK', 'Konkani', 'Konkani'),
(1, 'KC_Lang_KOM', @scm, 'KC_Lang_KOM', 'Komi', 'Komi'),
(1, 'KC_Lang_KON', @scm, 'KC_Lang_KON', 'Kongo', 'Kongo'),
(1, 'KC_Lang_KOR', @scm, 'KC_Lang_KOR', 'Korean', 'Korean'),
(1, 'KC_Lang_KOS', @scm, 'KC_Lang_KOS', 'Kosraean', 'Kosraean'),
(1, 'KC_Lang_KPE', @scm, 'KC_Lang_KPE', 'Kpelle', 'Kpelle'),
(1, 'KC_Lang_KRC', @scm, 'KC_Lang_KRC', 'Karachay-Balkar', 'Karachay-Balkar'),
(1, 'KC_Lang_KRL', @scm, 'KC_Lang_KRL', 'Karelian', 'Karelian'),
(1, 'KC_Lang_KRO', @scm, 'KC_Lang_KRO', 'Kru languages', 'Kru languages'),
(1, 'KC_Lang_KRU', @scm, 'KC_Lang_KRU', 'Kurukh', 'Kurukh'),
(1, 'KC_Lang_KUA', @scm, 'KC_Lang_KUA', 'Kuanyama; Kwanyama', 'Kuanyama; Kwanyama'),
(1, 'KC_Lang_KUM', @scm, 'KC_Lang_KUM', 'Kumyk', 'Kumyk'),
(1, 'KC_Lang_KUR', @scm, 'KC_Lang_KUR', 'Kurdish', 'Kurdish'),
(1, 'KC_Lang_KUT', @scm, 'KC_Lang_KUT', 'Kutenai', 'Kutenai'),
(1, 'KC_Lang_LAD', @scm, 'KC_Lang_LAD', 'Ladino', 'Ladino'),
(1, 'KC_Lang_LAH', @scm, 'KC_Lang_LAH', 'Lahnda', 'Lahnda'),
(1, 'KC_Lang_LAM', @scm, 'KC_Lang_LAM', 'Lamba', 'Lamba'),
(1, 'KC_Lang_LAO', @scm, 'KC_Lang_LAO', 'Lao', 'Lao'),
(1, 'KC_Lang_LAT', @scm, 'KC_Lang_LAT', 'Latin', 'Latin'),
(1, 'KC_Lang_LAV', @scm, 'KC_Lang_LAV', 'Latvian', 'Latvian'),
(1, 'KC_Lang_LEZ', @scm, 'KC_Lang_LEZ', 'Lezghian', 'Lezghian'),
(1, 'KC_Lang_LIM', @scm, 'KC_Lang_LIM', 'Limburgan; Limburger; Limburgish', 'Limburgan; Limburger; Limburgish'),
(1, 'KC_Lang_LIN', @scm, 'KC_Lang_LIN', 'Lingala', 'Lingala'),
(1, 'KC_Lang_LIT', @scm, 'KC_Lang_LIT', 'Lithuanian', 'Lithuanian'),
(1, 'KC_Lang_LOL', @scm, 'KC_Lang_LOL', 'Mongo', 'Mongo'),
(1, 'KC_Lang_LOZ', @scm, 'KC_Lang_LOZ', 'Lozi', 'Lozi'),
(1, 'KC_Lang_LTZ', @scm, 'KC_Lang_LTZ', 'Luxembourgish; Letzeburgesch', 'Luxembourgish; Letzeburgesch'),
(1, 'KC_Lang_LUA', @scm, 'KC_Lang_LUA', 'Luba-Lulua', 'Luba-Lulua'),
(1, 'KC_Lang_LUB', @scm, 'KC_Lang_LUB', 'Luba-Katanga', 'Luba-Katanga'),
(1, 'KC_Lang_LUG', @scm, 'KC_Lang_LUG', 'Ganda', 'Ganda'),
(1, 'KC_Lang_LUI', @scm, 'KC_Lang_LUI', 'Luiseno', 'Luiseno'),
(1, 'KC_Lang_LUN', @scm, 'KC_Lang_LUN', 'Lunda', 'Lunda'),
(1, 'KC_Lang_LUO', @scm, 'KC_Lang_LUO', 'Luo (Kenya and Tanzania)', 'Luo (Kenya and Tanzania)'),
(1, 'KC_Lang_LUS', @scm, 'KC_Lang_LUS', 'Lushai', 'Lushai'),
(1, 'KC_Lang_MAC', @scm, 'KC_Lang_MAC', 'Macedonian', 'Macedonian'),
(1, 'KC_Lang_MAD', @scm, 'KC_Lang_MAD', 'Madurese', 'Madurese'),
(1, 'KC_Lang_MAG', @scm, 'KC_Lang_MAG', 'Magahi', 'Magahi'),
(1, 'KC_Lang_MAH', @scm, 'KC_Lang_MAH', 'Marshallese', 'Marshallese'),
(1, 'KC_Lang_MAI', @scm, 'KC_Lang_MAI', 'Maithili', 'Maithili'),
(1, 'KC_Lang_MAK', @scm, 'KC_Lang_MAK', 'Makasar', 'Makasar'),
(1, 'KC_Lang_MAL', @scm, 'KC_Lang_MAL', 'Malayalam', 'Malayalam'),
(1, 'KC_Lang_MAN', @scm, 'KC_Lang_MAN', 'Mandingo', 'Mandingo'),
(1, 'KC_Lang_MAO', @scm, 'KC_Lang_MAO', 'Maori', 'Maori'),
(1, 'KC_Lang_MAP', @scm, 'KC_Lang_MAP', 'Austronesian languages', 'Austronesian languages'),
(1, 'KC_Lang_MAR', @scm, 'KC_Lang_MAR', 'Marathi', 'Marathi'),
(1, 'KC_Lang_MAS', @scm, 'KC_Lang_MAS', 'Masai', 'Masai'),
(1, 'KC_Lang_MAY', @scm, 'KC_Lang_MAY', 'Malay', 'Malay'),
(1, 'KC_Lang_MDF', @scm, 'KC_Lang_MDF', 'Moksha', 'Moksha'),
(1, 'KC_Lang_MDR', @scm, 'KC_Lang_MDR', 'Mandar', 'Mandar'),
(1, 'KC_Lang_MEN', @scm, 'KC_Lang_MEN', 'Mende', 'Mende'),
(1, 'KC_Lang_MGA', @scm, 'KC_Lang_MGA', 'Irish, Middle (900-1200)', 'Irish, Middle (900-1200)'),
(1, 'KC_Lang_MIC', @scm, 'KC_Lang_MIC', 'Mi''kmaq; Micmac', 'Mi''kmaq; Micmac'),
(1, 'KC_Lang_MIN', @scm, 'KC_Lang_MIN', 'Minangkabau', 'Minangkabau'),
(1, 'KC_Lang_MIS', @scm, 'KC_Lang_MIS', 'Uncoded languages', 'Uncoded languages'),
(1, 'KC_Lang_MKD', @scm, 'KC_Lang_MKD', 'Macedonian', 'Macedonian'),
(1, 'KC_Lang_MKH', @scm, 'KC_Lang_MKH', 'Mon-Khmer languages', 'Mon-Khmer languages'),
(1, 'KC_Lang_MLG', @scm, 'KC_Lang_MLG', 'Malagasy', 'Malagasy'),
(1, 'KC_Lang_MLT', @scm, 'KC_Lang_MLT', 'Maltese', 'Maltese'),
(1, 'KC_Lang_MNC', @scm, 'KC_Lang_MNC', 'Manchu', 'Manchu'),
(1, 'KC_Lang_MNI', @scm, 'KC_Lang_MNI', 'Manipuri', 'Manipuri'),
(1, 'KC_Lang_MNO', @scm, 'KC_Lang_MNO', 'Manobo languages', 'Manobo languages'),
(1, 'KC_Lang_MOH', @scm, 'KC_Lang_MOH', 'Mohawk', 'Mohawk'),
(1, 'KC_Lang_MON', @scm, 'KC_Lang_MON', 'Mongolian', 'Mongolian'),
(1, 'KC_Lang_MOS', @scm, 'KC_Lang_MOS', 'Mossi', 'Mossi'),
(1, 'KC_Lang_MRI', @scm, 'KC_Lang_MRI', 'Maori', 'Maori'),
(1, 'KC_Lang_MSA', @scm, 'KC_Lang_MSA', 'Malay', 'Malay'),
(1, 'KC_Lang_MUL', @scm, 'KC_Lang_MUL', 'Multiple languages', 'Multiple languages'),
(1, 'KC_Lang_MUN', @scm, 'KC_Lang_MUN', 'Munda languages', 'Munda languages'),
(1, 'KC_Lang_MUS', @scm, 'KC_Lang_MUS', 'Creek', 'Creek'),
(1, 'KC_Lang_MWL', @scm, 'KC_Lang_MWL', 'Mirandese', 'Mirandese'),
(1, 'KC_Lang_MWR', @scm, 'KC_Lang_MWR', 'Marwari', 'Marwari'),
(1, 'KC_Lang_MYA', @scm, 'KC_Lang_MYA', 'Burmese', 'Burmese'),
(1, 'KC_Lang_MYN', @scm, 'KC_Lang_MYN', 'Mayan languages', 'Mayan languages'),
(1, 'KC_Lang_MYV', @scm, 'KC_Lang_MYV', 'Erzya', 'Erzya'),
(1, 'KC_Lang_NAH', @scm, 'KC_Lang_NAH', 'Nahuatl languages', 'Nahuatl languages'),
(1, 'KC_Lang_NAI', @scm, 'KC_Lang_NAI', 'North American Indian languages', 'North American Indian languages'),
(1, 'KC_Lang_NAP', @scm, 'KC_Lang_NAP', 'Neapolitan', 'Neapolitan'),
(1, 'KC_Lang_NAU', @scm, 'KC_Lang_NAU', 'Nauru', 'Nauru'),
(1, 'KC_Lang_NAV', @scm, 'KC_Lang_NAV', 'Navajo; Navaho', 'Navajo; Navaho'),
(1, 'KC_Lang_NBL', @scm, 'KC_Lang_NBL', 'Ndebele, South; South Ndebele', 'Ndebele, South; South Ndebele'),
(1, 'KC_Lang_NDE', @scm, 'KC_Lang_NDE', 'Ndebele, North; North Ndebele', 'Ndebele, North; North Ndebele'),
(1, 'KC_Lang_NDO', @scm, 'KC_Lang_NDO', 'Ndonga', 'Ndonga'),
(1, 'KC_Lang_NDS', @scm, 'KC_Lang_NDS', 'Low German; Low Saxon; German, Low; Saxon, Low', 'Low German; Low Saxon; German, Low; Saxon, Low'),
(1, 'KC_Lang_NEP', @scm, 'KC_Lang_NEP', 'Nepali', 'Nepali'),
(1, 'KC_Lang_NEW', @scm, 'KC_Lang_NEW', 'Nepal Bhasa; Newari', 'Nepal Bhasa; Newari'),
(1, 'KC_Lang_NIA', @scm, 'KC_Lang_NIA', 'Nias', 'Nias'),
(1, 'KC_Lang_NIC', @scm, 'KC_Lang_NIC', 'Niger-Kordofanian languages', 'Niger-Kordofanian languages'),
(1, 'KC_Lang_NIU', @scm, 'KC_Lang_NIU', 'Niuean', 'Niuean'),
(1, 'KC_Lang_NLD', @scm, 'KC_Lang_NLD', 'Dutch; Flemish', 'Dutch; Flemish'),
(1, 'KC_Lang_NNO', @scm, 'KC_Lang_NNO', 'Norwegian Nynorsk; Nynorsk, Norwegian', 'Norwegian Nynorsk; Nynorsk, Norwegian'),
(1, 'KC_Lang_NOB', @scm, 'KC_Lang_NOB', 'Bokmål, Norwegian; Norwegian Bokmål', 'Bokmål, Norwegian; Norwegian Bokmål'),
(1, 'KC_Lang_NOG', @scm, 'KC_Lang_NOG', 'Nogai', 'Nogai'),
(1, 'KC_Lang_NON', @scm, 'KC_Lang_NON', 'Norse, Old', 'Norse, Old'),
(1, 'KC_Lang_NOR', @scm, 'KC_Lang_NOR', 'Norwegian', 'Norwegian'),
(1, 'KC_Lang_NQO', @scm, 'KC_Lang_NQO', 'N''Ko', 'N''Ko'),
(1, 'KC_Lang_NSO', @scm, 'KC_Lang_NSO', 'Pedi; Sepedi; Northern Sotho', 'Pedi; Sepedi; Northern Sotho'),
(1, 'KC_Lang_NUB', @scm, 'KC_Lang_NUB', 'Nubian languages', 'Nubian languages'),
(1, 'KC_Lang_NWC', @scm, 'KC_Lang_NWC', 'Classical Newari; Old Newari; Classical Nepal Bhasa', 'Classical Newari; Old Newari; Classical Nepal Bhasa'),
(1, 'KC_Lang_NYA', @scm, 'KC_Lang_NYA', 'Chichewa; Chewa; Nyanja', 'Chichewa; Chewa; Nyanja'),
(1, 'KC_Lang_NYM', @scm, 'KC_Lang_NYM', 'Nyamwezi', 'Nyamwezi'),
(1, 'KC_Lang_NYN', @scm, 'KC_Lang_NYN', 'Nyankole', 'Nyankole'),
(1, 'KC_Lang_NYO', @scm, 'KC_Lang_NYO', 'Nyoro', 'Nyoro'),
(1, 'KC_Lang_NZI', @scm, 'KC_Lang_NZI', 'Nzima', 'Nzima'),
(1, 'KC_Lang_OCI', @scm, 'KC_Lang_OCI', 'Occitan (post 1500)', 'Occitan (post 1500)'),
(1, 'KC_Lang_OJI', @scm, 'KC_Lang_OJI', 'Ojibwa', 'Ojibwa'),
(1, 'KC_Lang_ORI', @scm, 'KC_Lang_ORI', 'Oriya', 'Oriya'),
(1, 'KC_Lang_ORM', @scm, 'KC_Lang_ORM', 'Oromo', 'Oromo'),
(1, 'KC_Lang_OSA', @scm, 'KC_Lang_OSA', 'Osage', 'Osage'),
(1, 'KC_Lang_OSS', @scm, 'KC_Lang_OSS', 'Ossetian; Ossetic', 'Ossetian; Ossetic'),
(1, 'KC_Lang_OTA', @scm, 'KC_Lang_OTA', 'Turkish, Ottoman (1500-1928)', 'Turkish, Ottoman (1500-1928)'),
(1, 'KC_Lang_OTO', @scm, 'KC_Lang_OTO', 'Otomian languages', 'Otomian languages'),
(1, 'KC_Lang_PAA', @scm, 'KC_Lang_PAA', 'Papuan languages', 'Papuan languages'),
(1, 'KC_Lang_PAG', @scm, 'KC_Lang_PAG', 'Pangasinan', 'Pangasinan'),
(1, 'KC_Lang_PAL', @scm, 'KC_Lang_PAL', 'Pahlavi', 'Pahlavi'),
(1, 'KC_Lang_PAM', @scm, 'KC_Lang_PAM', 'Pampanga; Kapampangan', 'Pampanga; Kapampangan'),
(1, 'KC_Lang_PAN', @scm, 'KC_Lang_PAN', 'Panjabi; Punjabi', 'Panjabi; Punjabi'),
(1, 'KC_Lang_PAP', @scm, 'KC_Lang_PAP', 'Papiamento', 'Papiamento'),
(1, 'KC_Lang_PAU', @scm, 'KC_Lang_PAU', 'Palauan', 'Palauan'),
(1, 'KC_Lang_PEO', @scm, 'KC_Lang_PEO', 'Persian, Old (ca.600-400 B.C.)', 'Persian, Old (ca.600-400 B.C.)'),
(1, 'KC_Lang_PER', @scm, 'KC_Lang_PER', 'Persian', 'Persian'),
(1, 'KC_Lang_PHI', @scm, 'KC_Lang_PHI', 'Philippine languages', 'Philippine languages'),
(1, 'KC_Lang_PHN', @scm, 'KC_Lang_PHN', 'Phoenician', 'Phoenician'),
(1, 'KC_Lang_PLI', @scm, 'KC_Lang_PLI', 'Pali', 'Pali'),
(1, 'KC_Lang_POL', @scm, 'KC_Lang_POL', 'Polish', 'Polish'),
(1, 'KC_Lang_PON', @scm, 'KC_Lang_PON', 'Pohnpeian', 'Pohnpeian'),
(1, 'KC_Lang_POR', @scm, 'KC_Lang_POR', 'Portuguese', 'Portuguese'),
(1, 'KC_Lang_PRA', @scm, 'KC_Lang_PRA', 'Prakrit languages', 'Prakrit languages'),
(1, 'KC_Lang_PRO', @scm, 'KC_Lang_PRO', 'Provençal, Old (to 1500);Occitan, Old (to 1500)', 'Provençal, Old (to 1500);Occitan, Old (to 1500)'),
(1, 'KC_Lang_PUS', @scm, 'KC_Lang_PUS', 'Pushto; Pashto', 'Pushto; Pashto'),
(1, 'KC_Lang_QAA', @scm, 'KC_Lang_QAA', 'QTZ	Reserved for local use', 'QTZ	Reserved for local use'),
(1, 'KC_Lang_QUE', @scm, 'KC_Lang_QUE', 'Quechua', 'Quechua'),
(1, 'KC_Lang_RAJ', @scm, 'KC_Lang_RAJ', 'Rajasthani', 'Rajasthani'),
(1, 'KC_Lang_RAP', @scm, 'KC_Lang_RAP', 'Rapanui', 'Rapanui'),
(1, 'KC_Lang_RAR', @scm, 'KC_Lang_RAR', 'Rarotongan; Cook Islands Maori', 'Rarotongan; Cook Islands Maori'),
(1, 'KC_Lang_ROA', @scm, 'KC_Lang_ROA', 'Romance languages', 'Romance languages'),
(1, 'KC_Lang_ROH', @scm, 'KC_Lang_ROH', 'Romansh', 'Romansh'),
(1, 'KC_Lang_ROM', @scm, 'KC_Lang_ROM', 'Romany', 'Romany'),
(1, 'KC_Lang_RON', @scm, 'KC_Lang_RON', 'Romanian; Moldavian; Moldovan', 'Romanian; Moldavian; Moldovan'),
(1, 'KC_Lang_RUM', @scm, 'KC_Lang_RUM', 'Romanian; Moldavian; Moldovan', 'Romanian; Moldavian; Moldovan'),
(1, 'KC_Lang_RUN', @scm, 'KC_Lang_RUN', 'Rundi', 'Rundi'),
(1, 'KC_Lang_RUP', @scm, 'KC_Lang_RUP', 'Aromanian; Arumanian; Macedo-Romanian', 'Aromanian; Arumanian; Macedo-Romanian'),
(1, 'KC_Lang_RUS', @scm, 'KC_Lang_RUS', 'Russian', 'Russian'),
(1, 'KC_Lang_SAD', @scm, 'KC_Lang_SAD', 'Sandawe', 'Sandawe'),
(1, 'KC_Lang_SAG', @scm, 'KC_Lang_SAG', 'Sango', 'Sango'),
(1, 'KC_Lang_SAH', @scm, 'KC_Lang_SAH', 'Yakut', 'Yakut'),
(1, 'KC_Lang_SAI', @scm, 'KC_Lang_SAI', 'South American Indian languages', 'South American Indian languages'),
(1, 'KC_Lang_SAL', @scm, 'KC_Lang_SAL', 'Salishan languages', 'Salishan languages'),
(1, 'KC_Lang_SAM', @scm, 'KC_Lang_SAM', 'Samaritan Aramaic', 'Samaritan Aramaic'),
(1, 'KC_Lang_SAN', @scm, 'KC_Lang_SAN', 'Sanskrit', 'Sanskrit'),
(1, 'KC_Lang_SAS', @scm, 'KC_Lang_SAS', 'Sasak', 'Sasak'),
(1, 'KC_Lang_SAT', @scm, 'KC_Lang_SAT', 'Santali', 'Santali'),
(1, 'KC_Lang_SCN', @scm, 'KC_Lang_SCN', 'Sicilian', 'Sicilian'),
(1, 'KC_Lang_SCO', @scm, 'KC_Lang_SCO', 'Scots', 'Scots'),
(1, 'KC_Lang_SEL', @scm, 'KC_Lang_SEL', 'Selkup', 'Selkup'),
(1, 'KC_Lang_SEM', @scm, 'KC_Lang_SEM', 'Semitic languages', 'Semitic languages'),
(1, 'KC_Lang_SGA', @scm, 'KC_Lang_SGA', 'Irish, Old (to 900)', 'Irish, Old (to 900)'),
(1, 'KC_Lang_SGN', @scm, 'KC_Lang_SGN', 'Sign Languages', 'Sign Languages'),
(1, 'KC_Lang_SHN', @scm, 'KC_Lang_SHN', 'Shan', 'Shan'),
(1, 'KC_Lang_SID', @scm, 'KC_Lang_SID', 'Sidamo', 'Sidamo'),
(1, 'KC_Lang_SIN', @scm, 'KC_Lang_SIN', 'Sinhala; Sinhalese', 'Sinhala; Sinhalese'),
(1, 'KC_Lang_SIO', @scm, 'KC_Lang_SIO', 'Siouan languages', 'Siouan languages'),
(1, 'KC_Lang_SIT', @scm, 'KC_Lang_SIT', 'Sino-Tibetan languages', 'Sino-Tibetan languages'),
(1, 'KC_Lang_SLA', @scm, 'KC_Lang_SLA', 'Slavic languages', 'Slavic languages'),
(1, 'KC_Lang_SLK', @scm, 'KC_Lang_SLK', 'Slovak', 'Slovak'),
(1, 'KC_Lang_SLO', @scm, 'KC_Lang_SLO', 'Slovak', 'Slovak'),
(1, 'KC_Lang_SLV', @scm, 'KC_Lang_SLV', 'Slovenian', 'Slovenian'),
(1, 'KC_Lang_SMA', @scm, 'KC_Lang_SMA', 'Southern Sami', 'Southern Sami'),
(1, 'KC_Lang_SME', @scm, 'KC_Lang_SME', 'Northern Sami', 'Northern Sami'),
(1, 'KC_Lang_SMI', @scm, 'KC_Lang_SMI', 'Sami languages', 'Sami languages'),
(1, 'KC_Lang_SMJ', @scm, 'KC_Lang_SMJ', 'Lule Sami', 'Lule Sami'),
(1, 'KC_Lang_SMN', @scm, 'KC_Lang_SMN', 'Inari Sami', 'Inari Sami'),
(1, 'KC_Lang_SMO', @scm, 'KC_Lang_SMO', 'Samoan', 'Samoan'),
(1, 'KC_Lang_SMS', @scm, 'KC_Lang_SMS', 'Skolt Sami', 'Skolt Sami'),
(1, 'KC_Lang_SNA', @scm, 'KC_Lang_SNA', 'Shona', 'Shona'),
(1, 'KC_Lang_SND', @scm, 'KC_Lang_SND', 'Sindhi', 'Sindhi'),
(1, 'KC_Lang_SNK', @scm, 'KC_Lang_SNK', 'Soninke', 'Soninke'),
(1, 'KC_Lang_SOG', @scm, 'KC_Lang_SOG', 'Sogdian', 'Sogdian'),
(1, 'KC_Lang_SOM', @scm, 'KC_Lang_SOM', 'Somali', 'Somali'),
(1, 'KC_Lang_SON', @scm, 'KC_Lang_SON', 'Songhai languages', 'Songhai languages'),
(1, 'KC_Lang_SOT', @scm, 'KC_Lang_SOT', 'Sotho, Southern', 'Sotho, Southern'),
(1, 'KC_Lang_SPA', @scm, 'KC_Lang_SPA', 'Spanish; Castilian', 'Spanish; Castilian'),
(1, 'KC_Lang_SQI', @scm, 'KC_Lang_SQI', 'Albanian', 'Albanian'),
(1, 'KC_Lang_SRD', @scm, 'KC_Lang_SRD', 'Sardinian', 'Sardinian'),
(1, 'KC_Lang_SRN', @scm, 'KC_Lang_SRN', 'Sranan Tongo', 'Sranan Tongo'),
(1, 'KC_Lang_SRP', @scm, 'KC_Lang_SRP', 'Serbian', 'Serbian'),
(1, 'KC_Lang_SRR', @scm, 'KC_Lang_SRR', 'Serer', 'Serer'),
(1, 'KC_Lang_SSA', @scm, 'KC_Lang_SSA', 'Nilo-Saharan languages', 'Nilo-Saharan languages'),
(1, 'KC_Lang_SSW', @scm, 'KC_Lang_SSW', 'Swati', 'Swati'),
(1, 'KC_Lang_SUK', @scm, 'KC_Lang_SUK', 'Sukuma', 'Sukuma'),
(1, 'KC_Lang_SUN', @scm, 'KC_Lang_SUN', 'Sundanese', 'Sundanese'),
(1, 'KC_Lang_SUS', @scm, 'KC_Lang_SUS', 'Susu', 'Susu'),
(1, 'KC_Lang_SUX', @scm, 'KC_Lang_SUX', 'Sumerian', 'Sumerian'),
(1, 'KC_Lang_SWA', @scm, 'KC_Lang_SWA', 'Swahili', 'Swahili'),
(1, 'KC_Lang_SWE', @scm, 'KC_Lang_SWE', 'Swedish', 'Swedish'),
(1, 'KC_Lang_SYC', @scm, 'KC_Lang_SYC', 'Classical Syriac', 'Classical Syriac'),
(1, 'KC_Lang_SYR', @scm, 'KC_Lang_SYR', 'Syriac', 'Syriac'),
(1, 'KC_Lang_TAH', @scm, 'KC_Lang_TAH', 'Tahitian', 'Tahitian'),
(1, 'KC_Lang_TAI', @scm, 'KC_Lang_TAI', 'Tai languages', 'Tai languages'),
(1, 'KC_Lang_TAM', @scm, 'KC_Lang_TAM', 'Tamil', 'Tamil'),
(1, 'KC_Lang_TAT', @scm, 'KC_Lang_TAT', 'Tatar', 'Tatar'),
(1, 'KC_Lang_TEL', @scm, 'KC_Lang_TEL', 'Telugu', 'Telugu'),
(1, 'KC_Lang_TEM', @scm, 'KC_Lang_TEM', 'Timne', 'Timne'),
(1, 'KC_Lang_TER', @scm, 'KC_Lang_TER', 'Tereno', 'Tereno'),
(1, 'KC_Lang_TET', @scm, 'KC_Lang_TET', 'Tetum', 'Tetum'),
(1, 'KC_Lang_TGK', @scm, 'KC_Lang_TGK', 'Tajik', 'Tajik'),
(1, 'KC_Lang_TGL', @scm, 'KC_Lang_TGL', 'Tagalog', 'Tagalog'),
(1, 'KC_Lang_THA', @scm, 'KC_Lang_THA', 'Thai', 'Thai'),
(1, 'KC_Lang_TIB', @scm, 'KC_Lang_TIB', 'Tibetan', 'Tibetan'),
(1, 'KC_Lang_TIG', @scm, 'KC_Lang_TIG', 'Tigre', 'Tigre'),
(1, 'KC_Lang_TIR', @scm, 'KC_Lang_TIR', 'Tigrinya', 'Tigrinya'),
(1, 'KC_Lang_TIV', @scm, 'KC_Lang_TIV', 'Tiv', 'Tiv'),
(1, 'KC_Lang_TKL', @scm, 'KC_Lang_TKL', 'Tokelau', 'Tokelau'),
(1, 'KC_Lang_TLH', @scm, 'KC_Lang_TLH', 'Klingon; tlhIngan-Hol', 'Klingon; tlhIngan-Hol'),
(1, 'KC_Lang_TLI', @scm, 'KC_Lang_TLI', 'Tlingit', 'Tlingit'),
(1, 'KC_Lang_TMH', @scm, 'KC_Lang_TMH', 'Tamashek', 'Tamashek'),
(1, 'KC_Lang_TOG', @scm, 'KC_Lang_TOG', 'Tonga (Nyasa)', 'Tonga (Nyasa)'),
(1, 'KC_Lang_TON', @scm, 'KC_Lang_TON', 'Tonga (Tonga Islands)', 'Tonga (Tonga Islands)'),
(1, 'KC_Lang_TPI', @scm, 'KC_Lang_TPI', 'Tok Pisin', 'Tok Pisin'),
(1, 'KC_Lang_TSI', @scm, 'KC_Lang_TSI', 'Tsimshian', 'Tsimshian'),
(1, 'KC_Lang_TSN', @scm, 'KC_Lang_TSN', 'Tswana', 'Tswana'),
(1, 'KC_Lang_TSO', @scm, 'KC_Lang_TSO', 'Tsonga', 'Tsonga'),
(1, 'KC_Lang_TUK', @scm, 'KC_Lang_TUK', 'Turkmen', 'Turkmen'),
(1, 'KC_Lang_TUM', @scm, 'KC_Lang_TUM', 'Tumbuka', 'Tumbuka'),
(1, 'KC_Lang_TUP', @scm, 'KC_Lang_TUP', 'Tupi languages', 'Tupi languages'),
(1, 'KC_Lang_TUR', @scm, 'KC_Lang_TUR', 'Turkish', 'Turkish'),
(1, 'KC_Lang_TUT', @scm, 'KC_Lang_TUT', 'Altaic languages', 'Altaic languages'),
(1, 'KC_Lang_TVL', @scm, 'KC_Lang_TVL', 'Tuvalu', 'Tuvalu'),
(1, 'KC_Lang_TWI', @scm, 'KC_Lang_TWI', 'Twi', 'Twi'),
(1, 'KC_Lang_TYV', @scm, 'KC_Lang_TYV', 'Tuvinian', 'Tuvinian'),
(1, 'KC_Lang_UDM', @scm, 'KC_Lang_UDM', 'Udmurt', 'Udmurt'),
(1, 'KC_Lang_UGA', @scm, 'KC_Lang_UGA', 'Ugaritic', 'Ugaritic'),
(1, 'KC_Lang_UIG', @scm, 'KC_Lang_UIG', 'Uighur; Uyghur', 'Uighur; Uyghur'),
(1, 'KC_Lang_UKR', @scm, 'KC_Lang_UKR', 'Ukrainian', 'Ukrainian'),
(1, 'KC_Lang_UMB', @scm, 'KC_Lang_UMB', 'Umbundu', 'Umbundu'),
(1, 'KC_Lang_UND', @scm, 'KC_Lang_UND', 'Undetermined', 'Undetermined'),
(1, 'KC_Lang_URD', @scm, 'KC_Lang_URD', 'Urdu', 'Urdu'),
(1, 'KC_Lang_UZB', @scm, 'KC_Lang_UZB', 'Uzbek', 'Uzbek'),
(1, 'KC_Lang_VAI', @scm, 'KC_Lang_VAI', 'Vai', 'Vai'),
(1, 'KC_Lang_VEN', @scm, 'KC_Lang_VEN', 'Venda', 'Venda'),
(1, 'KC_Lang_VIE', @scm, 'KC_Lang_VIE', 'Vietnamese', 'Vietnamese'),
(1, 'KC_Lang_VOL', @scm, 'KC_Lang_VOL', 'Volapük', 'Volapük'),
(1, 'KC_Lang_VOT', @scm, 'KC_Lang_VOT', 'Votic', 'Votic'),
(1, 'KC_Lang_WAK', @scm, 'KC_Lang_WAK', 'Wakashan languages', 'Wakashan languages'),
(1, 'KC_Lang_WAL', @scm, 'KC_Lang_WAL', 'Wolaitta; Wolaytta', 'Wolaitta; Wolaytta'),
(1, 'KC_Lang_WAR', @scm, 'KC_Lang_WAR', 'Waray', 'Waray'),
(1, 'KC_Lang_WAS', @scm, 'KC_Lang_WAS', 'Washo', 'Washo'),
(1, 'KC_Lang_WEL', @scm, 'KC_Lang_WEL', 'Welsh', 'Welsh'),
(1, 'KC_Lang_WEN', @scm, 'KC_Lang_WEN', 'Sorbian languages', 'Sorbian languages'),
(1, 'KC_Lang_WLN', @scm, 'KC_Lang_WLN', 'Walloon', 'Walloon'),
(1, 'KC_Lang_WOL', @scm, 'KC_Lang_WOL', 'Wolof', 'Wolof'),
(1, 'KC_Lang_XAL', @scm, 'KC_Lang_XAL', 'Kalmyk; Oirat', 'Kalmyk; Oirat'),
(1, 'KC_Lang_XHO', @scm, 'KC_Lang_XHO', 'Xhosa', 'Xhosa'),
(1, 'KC_Lang_YAO', @scm, 'KC_Lang_YAO', 'Yao', 'Yao'),
(1, 'KC_Lang_YAP', @scm, 'KC_Lang_YAP', 'Yapese', 'Yapese'),
(1, 'KC_Lang_YID', @scm, 'KC_Lang_YID', 'Yiddish', 'Yiddish'),
(1, 'KC_Lang_YOR', @scm, 'KC_Lang_YOR', 'Yoruba', 'Yoruba'),
(1, 'KC_Lang_YPK', @scm, 'KC_Lang_YPK', 'Yupik languages', 'Yupik languages'),
(1, 'KC_Lang_ZAP', @scm, 'KC_Lang_ZAP', 'Zapotec', 'Zapotec'),
(1, 'KC_Lang_ZBL', @scm, 'KC_Lang_ZBL', 'Blissymbols; Blissymbolics; Bliss', 'Blissymbols; Blissymbolics; Bliss'),
(1, 'KC_Lang_ZEN', @scm, 'KC_Lang_ZEN', 'Zenaga', 'Zenaga'),
(1, 'KC_Lang_ZGH', @scm, 'KC_Lang_ZGH', 'Standard Moroccan Tamazight', 'Standard Moroccan Tamazight'),
(1, 'KC_Lang_ZHA', @scm, 'KC_Lang_ZHA', 'Zhuang; Chuang', 'Zhuang; Chuang'),
(1, 'KC_Lang_ZHO', @scm, 'KC_Lang_ZHO', 'Chinese', 'Chinese'),
(1, 'KC_Lang_ZND', @scm, 'KC_Lang_ZND', 'Zande languages', 'Zande languages'),
(1, 'KC_Lang_ZUL', @scm, 'KC_Lang_ZUL', 'Zulu', 'Zulu'),
(1, 'KC_Lang_ZUN', @scm, 'KC_Lang_ZUN', 'Zuni', 'Zuni'),
(1, 'KC_Lang_ZXX', @scm, 'KC_Lang_ZXX', 'No linguistic content; Not applicable', 'No linguistic content; Not applicable'),
(1, 'KC_Lang_ZZA', @scm, 'KC_Lang_ZZA', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki', 'Zaza; Dimili; Dimli; Kirdki; Kirmanjki; Zazaki'),
(1, 'KC_Lang_ADNOM', @scm, 'KC_Lang_ADNOM', 'Default, No Matching National Value', 'Default, No Matching National Value'),
(1, 'KC_Lang_ADNSP', @scm, 'KC_Lang_ADNSP', 'Not Specified', 'Not Specified');

-- Context
INSERT INTO map_context_meta (provider, `system`, `schema`, `table`, `column`, node)
VALUES ('CM_Org_Kings', 'CM_Sys_PIMS', null, null, 'language', '/KINGS/PIMS/LNGG');    -- Local

-- Property
INSERT INTO map_node_meta (node, concept)
VALUES ('/KINGS/PIMS/LNGG', 'DM_language');

-- Value maps
INSERT INTO map_node_value_meta
(node, value, scheme, concept)
VALUES
    ('/KINGS/PIMS/LNGG', 'AAR', 'KingsPIMS', 'KC_Lang_AAR'),
    ('/KINGS/PIMS/LNGG', 'ABK', 'KingsPIMS', 'KC_Lang_ABK'),
    ('/KINGS/PIMS/LNGG', 'ACE', 'KingsPIMS', 'KC_Lang_ACE'),
    ('/KINGS/PIMS/LNGG', 'ACH', 'KingsPIMS', 'KC_Lang_ACH'),
    ('/KINGS/PIMS/LNGG', 'ADA', 'KingsPIMS', 'KC_Lang_ADA'),
    ('/KINGS/PIMS/LNGG', 'ADY', 'KingsPIMS', 'KC_Lang_ADY'),
    ('/KINGS/PIMS/LNGG', 'AFA', 'KingsPIMS', 'KC_Lang_AFA'),
    ('/KINGS/PIMS/LNGG', 'AFH', 'KingsPIMS', 'KC_Lang_AFH'),
    ('/KINGS/PIMS/LNGG', 'AFR', 'KingsPIMS', 'KC_Lang_AFR'),
    ('/KINGS/PIMS/LNGG', 'AIN', 'KingsPIMS', 'KC_Lang_AIN'),
    ('/KINGS/PIMS/LNGG', 'AKA', 'KingsPIMS', 'KC_Lang_AKA'),
    ('/KINGS/PIMS/LNGG', 'AKK', 'KingsPIMS', 'KC_Lang_AKK'),
    ('/KINGS/PIMS/LNGG', 'ALB', 'KingsPIMS', 'KC_Lang_ALB'),
    ('/KINGS/PIMS/LNGG', 'ALE', 'KingsPIMS', 'KC_Lang_ALE'),
    ('/KINGS/PIMS/LNGG', 'ALG', 'KingsPIMS', 'KC_Lang_ALG'),
    ('/KINGS/PIMS/LNGG', 'ALT', 'KingsPIMS', 'KC_Lang_ALT'),
    ('/KINGS/PIMS/LNGG', 'AMH', 'KingsPIMS', 'KC_Lang_AMH'),
    ('/KINGS/PIMS/LNGG', 'ANG', 'KingsPIMS', 'KC_Lang_ANG'),
    ('/KINGS/PIMS/LNGG', 'ANP', 'KingsPIMS', 'KC_Lang_ANP'),
    ('/KINGS/PIMS/LNGG', 'APA', 'KingsPIMS', 'KC_Lang_APA'),
    ('/KINGS/PIMS/LNGG', 'ARA', 'KingsPIMS', 'KC_Lang_ARA'),
    ('/KINGS/PIMS/LNGG', 'ARC', 'KingsPIMS', 'KC_Lang_ARC'),
    ('/KINGS/PIMS/LNGG', 'ARG', 'KingsPIMS', 'KC_Lang_ARG'),
    ('/KINGS/PIMS/LNGG', 'ARM', 'KingsPIMS', 'KC_Lang_ARM'),
    ('/KINGS/PIMS/LNGG', 'ARN', 'KingsPIMS', 'KC_Lang_ARN'),
    ('/KINGS/PIMS/LNGG', 'ARP', 'KingsPIMS', 'KC_Lang_ARP'),
    ('/KINGS/PIMS/LNGG', 'ART', 'KingsPIMS', 'KC_Lang_ART'),
    ('/KINGS/PIMS/LNGG', 'ARW', 'KingsPIMS', 'KC_Lang_ARW'),
    ('/KINGS/PIMS/LNGG', 'ASM', 'KingsPIMS', 'KC_Lang_ASM'),
    ('/KINGS/PIMS/LNGG', 'AST', 'KingsPIMS', 'KC_Lang_AST'),
    ('/KINGS/PIMS/LNGG', 'ATH', 'KingsPIMS', 'KC_Lang_ATH'),
    ('/KINGS/PIMS/LNGG', 'AUS', 'KingsPIMS', 'KC_Lang_AUS'),
    ('/KINGS/PIMS/LNGG', 'AVA', 'KingsPIMS', 'KC_Lang_AVA'),
    ('/KINGS/PIMS/LNGG', 'AVE', 'KingsPIMS', 'KC_Lang_AVE'),
    ('/KINGS/PIMS/LNGG', 'AWA', 'KingsPIMS', 'KC_Lang_AWA'),
    ('/KINGS/PIMS/LNGG', 'AYM', 'KingsPIMS', 'KC_Lang_AYM'),
    ('/KINGS/PIMS/LNGG', 'AZE', 'KingsPIMS', 'KC_Lang_AZE'),
    ('/KINGS/PIMS/LNGG', 'BAD', 'KingsPIMS', 'KC_Lang_BAD'),
    ('/KINGS/PIMS/LNGG', 'BAI', 'KingsPIMS', 'KC_Lang_BAI'),
    ('/KINGS/PIMS/LNGG', 'BAK', 'KingsPIMS', 'KC_Lang_BAK'),
    ('/KINGS/PIMS/LNGG', 'BAL', 'KingsPIMS', 'KC_Lang_BAL'),
    ('/KINGS/PIMS/LNGG', 'BAM', 'KingsPIMS', 'KC_Lang_BAM'),
    ('/KINGS/PIMS/LNGG', 'BAN', 'KingsPIMS', 'KC_Lang_BAN'),
    ('/KINGS/PIMS/LNGG', 'BAQ', 'KingsPIMS', 'KC_Lang_BAQ'),
    ('/KINGS/PIMS/LNGG', 'BAS', 'KingsPIMS', 'KC_Lang_BAS'),
    ('/KINGS/PIMS/LNGG', 'BAT', 'KingsPIMS', 'KC_Lang_BAT'),
    ('/KINGS/PIMS/LNGG', 'BEJ', 'KingsPIMS', 'KC_Lang_BEJ'),
    ('/KINGS/PIMS/LNGG', 'BEL', 'KingsPIMS', 'KC_Lang_BEL'),
    ('/KINGS/PIMS/LNGG', 'BEM', 'KingsPIMS', 'KC_Lang_BEM'),
    ('/KINGS/PIMS/LNGG', 'BEN', 'KingsPIMS', 'KC_Lang_BEN'),
    ('/KINGS/PIMS/LNGG', 'BER', 'KingsPIMS', 'KC_Lang_BER'),
    ('/KINGS/PIMS/LNGG', 'BHO', 'KingsPIMS', 'KC_Lang_BHO'),
    ('/KINGS/PIMS/LNGG', 'BIH', 'KingsPIMS', 'KC_Lang_BIH'),
    ('/KINGS/PIMS/LNGG', 'BIK', 'KingsPIMS', 'KC_Lang_BIK'),
    ('/KINGS/PIMS/LNGG', 'BIN', 'KingsPIMS', 'KC_Lang_BIN'),
    ('/KINGS/PIMS/LNGG', 'BIS', 'KingsPIMS', 'KC_Lang_BIS'),
    ('/KINGS/PIMS/LNGG', 'BLA', 'KingsPIMS', 'KC_Lang_BLA'),
    ('/KINGS/PIMS/LNGG', 'BNT', 'KingsPIMS', 'KC_Lang_BNT'),
    ('/KINGS/PIMS/LNGG', 'BOD', 'KingsPIMS', 'KC_Lang_BOD'),
    ('/KINGS/PIMS/LNGG', 'BOS', 'KingsPIMS', 'KC_Lang_BOS'),
    ('/KINGS/PIMS/LNGG', 'BRA', 'KingsPIMS', 'KC_Lang_BRA'),
    ('/KINGS/PIMS/LNGG', 'BRE', 'KingsPIMS', 'KC_Lang_BRE'),
    ('/KINGS/PIMS/LNGG', 'BTK', 'KingsPIMS', 'KC_Lang_BTK'),
    ('/KINGS/PIMS/LNGG', 'BUA', 'KingsPIMS', 'KC_Lang_BUA'),
    ('/KINGS/PIMS/LNGG', 'BUG', 'KingsPIMS', 'KC_Lang_BUG'),
    ('/KINGS/PIMS/LNGG', 'BUL', 'KingsPIMS', 'KC_Lang_BUL'),
    ('/KINGS/PIMS/LNGG', 'BUR', 'KingsPIMS', 'KC_Lang_BUR'),
    ('/KINGS/PIMS/LNGG', 'BYN', 'KingsPIMS', 'KC_Lang_BYN'),
    ('/KINGS/PIMS/LNGG', 'CAD', 'KingsPIMS', 'KC_Lang_CAD'),
    ('/KINGS/PIMS/LNGG', 'CAI', 'KingsPIMS', 'KC_Lang_CAI'),
    ('/KINGS/PIMS/LNGG', 'CAR', 'KingsPIMS', 'KC_Lang_CAR'),
    ('/KINGS/PIMS/LNGG', 'CAT', 'KingsPIMS', 'KC_Lang_CAT'),
    ('/KINGS/PIMS/LNGG', 'CAU', 'KingsPIMS', 'KC_Lang_CAU'),
    ('/KINGS/PIMS/LNGG', 'CEB', 'KingsPIMS', 'KC_Lang_CEB'),
    ('/KINGS/PIMS/LNGG', 'CEL', 'KingsPIMS', 'KC_Lang_CEL'),
    ('/KINGS/PIMS/LNGG', 'CES', 'KingsPIMS', 'KC_Lang_CES'),
    ('/KINGS/PIMS/LNGG', 'CHA', 'KingsPIMS', 'KC_Lang_CHA'),
    ('/KINGS/PIMS/LNGG', 'CHB', 'KingsPIMS', 'KC_Lang_CHB'),
    ('/KINGS/PIMS/LNGG', 'CHE', 'KingsPIMS', 'KC_Lang_CHE'),
    ('/KINGS/PIMS/LNGG', 'CHG', 'KingsPIMS', 'KC_Lang_CHG'),
    ('/KINGS/PIMS/LNGG', 'CHI', 'KingsPIMS', 'KC_Lang_CHI'),
    ('/KINGS/PIMS/LNGG', 'CHK', 'KingsPIMS', 'KC_Lang_CHK'),
    ('/KINGS/PIMS/LNGG', 'CHM', 'KingsPIMS', 'KC_Lang_CHM'),
    ('/KINGS/PIMS/LNGG', 'CHN', 'KingsPIMS', 'KC_Lang_CHN'),
    ('/KINGS/PIMS/LNGG', 'CHO', 'KingsPIMS', 'KC_Lang_CHO'),
    ('/KINGS/PIMS/LNGG', 'CHP', 'KingsPIMS', 'KC_Lang_CHP'),
    ('/KINGS/PIMS/LNGG', 'CHR', 'KingsPIMS', 'KC_Lang_CHR'),
    ('/KINGS/PIMS/LNGG', 'CHU', 'KingsPIMS', 'KC_Lang_CHU'),
    ('/KINGS/PIMS/LNGG', 'CHV', 'KingsPIMS', 'KC_Lang_CHV'),
    ('/KINGS/PIMS/LNGG', 'CHY', 'KingsPIMS', 'KC_Lang_CHY'),
    ('/KINGS/PIMS/LNGG', 'CMC', 'KingsPIMS', 'KC_Lang_CMC'),
    ('/KINGS/PIMS/LNGG', 'CNR', 'KingsPIMS', 'KC_Lang_CNR'),
    ('/KINGS/PIMS/LNGG', 'COP', 'KingsPIMS', 'KC_Lang_COP'),
    ('/KINGS/PIMS/LNGG', 'COR', 'KingsPIMS', 'KC_Lang_COR'),
    ('/KINGS/PIMS/LNGG', 'COS', 'KingsPIMS', 'KC_Lang_COS'),
    ('/KINGS/PIMS/LNGG', 'CPE', 'KingsPIMS', 'KC_Lang_CPE'),
    ('/KINGS/PIMS/LNGG', 'CPF', 'KingsPIMS', 'KC_Lang_CPF'),
    ('/KINGS/PIMS/LNGG', 'CPP', 'KingsPIMS', 'KC_Lang_CPP'),
    ('/KINGS/PIMS/LNGG', 'CRE', 'KingsPIMS', 'KC_Lang_CRE'),
    ('/KINGS/PIMS/LNGG', 'CRH', 'KingsPIMS', 'KC_Lang_CRH'),
    ('/KINGS/PIMS/LNGG', 'CRP', 'KingsPIMS', 'KC_Lang_CRP'),
    ('/KINGS/PIMS/LNGG', 'CSB', 'KingsPIMS', 'KC_Lang_CSB'),
    ('/KINGS/PIMS/LNGG', 'CUS', 'KingsPIMS', 'KC_Lang_CUS'),
    ('/KINGS/PIMS/LNGG', 'CYM', 'KingsPIMS', 'KC_Lang_CYM'),
    ('/KINGS/PIMS/LNGG', 'CZE', 'KingsPIMS', 'KC_Lang_CZE'),
    ('/KINGS/PIMS/LNGG', 'DAK', 'KingsPIMS', 'KC_Lang_DAK'),
    ('/KINGS/PIMS/LNGG', 'DAN', 'KingsPIMS', 'KC_Lang_DAN'),
    ('/KINGS/PIMS/LNGG', 'DAR', 'KingsPIMS', 'KC_Lang_DAR'),
    ('/KINGS/PIMS/LNGG', 'DAY', 'KingsPIMS', 'KC_Lang_DAY'),
    ('/KINGS/PIMS/LNGG', 'DEL', 'KingsPIMS', 'KC_Lang_DEL'),
    ('/KINGS/PIMS/LNGG', 'DEN', 'KingsPIMS', 'KC_Lang_DEN'),
    ('/KINGS/PIMS/LNGG', 'DEU', 'KingsPIMS', 'KC_Lang_DEU'),
    ('/KINGS/PIMS/LNGG', 'DGR', 'KingsPIMS', 'KC_Lang_DGR'),
    ('/KINGS/PIMS/LNGG', 'DIN', 'KingsPIMS', 'KC_Lang_DIN'),
    ('/KINGS/PIMS/LNGG', 'DIV', 'KingsPIMS', 'KC_Lang_DIV'),
    ('/KINGS/PIMS/LNGG', 'DOI', 'KingsPIMS', 'KC_Lang_DOI'),
    ('/KINGS/PIMS/LNGG', 'DRA', 'KingsPIMS', 'KC_Lang_DRA'),
    ('/KINGS/PIMS/LNGG', 'DSB', 'KingsPIMS', 'KC_Lang_DSB'),
    ('/KINGS/PIMS/LNGG', 'DUA', 'KingsPIMS', 'KC_Lang_DUA'),
    ('/KINGS/PIMS/LNGG', 'DUM', 'KingsPIMS', 'KC_Lang_DUM'),
    ('/KINGS/PIMS/LNGG', 'DUT', 'KingsPIMS', 'KC_Lang_DUT'),
    ('/KINGS/PIMS/LNGG', 'DYU', 'KingsPIMS', 'KC_Lang_DYU'),
    ('/KINGS/PIMS/LNGG', 'DZO', 'KingsPIMS', 'KC_Lang_DZO'),
    ('/KINGS/PIMS/LNGG', 'EFI', 'KingsPIMS', 'KC_Lang_EFI'),
    ('/KINGS/PIMS/LNGG', 'EGY', 'KingsPIMS', 'KC_Lang_EGY'),
    ('/KINGS/PIMS/LNGG', 'EKA', 'KingsPIMS', 'KC_Lang_EKA'),
    ('/KINGS/PIMS/LNGG', 'ELL', 'KingsPIMS', 'KC_Lang_ELL'),
    ('/KINGS/PIMS/LNGG', 'ELX', 'KingsPIMS', 'KC_Lang_ELX'),
    ('/KINGS/PIMS/LNGG', 'ENG', 'KingsPIMS', 'KC_Lang_ENG'),
    ('/KINGS/PIMS/LNGG', 'ENM', 'KingsPIMS', 'KC_Lang_ENM'),
    ('/KINGS/PIMS/LNGG', 'EPO', 'KingsPIMS', 'KC_Lang_EPO'),
    ('/KINGS/PIMS/LNGG', 'EST', 'KingsPIMS', 'KC_Lang_EST'),
    ('/KINGS/PIMS/LNGG', 'EUS', 'KingsPIMS', 'KC_Lang_EUS'),
    ('/KINGS/PIMS/LNGG', 'EWE', 'KingsPIMS', 'KC_Lang_EWE'),
    ('/KINGS/PIMS/LNGG', 'EWO', 'KingsPIMS', 'KC_Lang_EWO'),
    ('/KINGS/PIMS/LNGG', 'FAN', 'KingsPIMS', 'KC_Lang_FAN'),
    ('/KINGS/PIMS/LNGG', 'FAO', 'KingsPIMS', 'KC_Lang_FAO'),
    ('/KINGS/PIMS/LNGG', 'FAS', 'KingsPIMS', 'KC_Lang_FAS'),
    ('/KINGS/PIMS/LNGG', 'FAT', 'KingsPIMS', 'KC_Lang_FAT'),
    ('/KINGS/PIMS/LNGG', 'FIJ', 'KingsPIMS', 'KC_Lang_FIJ'),
    ('/KINGS/PIMS/LNGG', 'FIL', 'KingsPIMS', 'KC_Lang_FIL'),
    ('/KINGS/PIMS/LNGG', 'FIN', 'KingsPIMS', 'KC_Lang_FIN'),
    ('/KINGS/PIMS/LNGG', 'FIU', 'KingsPIMS', 'KC_Lang_FIU'),
    ('/KINGS/PIMS/LNGG', 'FON', 'KingsPIMS', 'KC_Lang_FON'),
    ('/KINGS/PIMS/LNGG', 'FRA', 'KingsPIMS', 'KC_Lang_FRA'),
    ('/KINGS/PIMS/LNGG', 'FRE', 'KingsPIMS', 'KC_Lang_FRE'),
    ('/KINGS/PIMS/LNGG', 'FRM', 'KingsPIMS', 'KC_Lang_FRM'),
    ('/KINGS/PIMS/LNGG', 'FRO', 'KingsPIMS', 'KC_Lang_FRO'),
    ('/KINGS/PIMS/LNGG', 'FRR', 'KingsPIMS', 'KC_Lang_FRR'),
    ('/KINGS/PIMS/LNGG', 'FRS', 'KingsPIMS', 'KC_Lang_FRS'),
    ('/KINGS/PIMS/LNGG', 'FRY', 'KingsPIMS', 'KC_Lang_FRY'),
    ('/KINGS/PIMS/LNGG', 'FUL', 'KingsPIMS', 'KC_Lang_FUL'),
    ('/KINGS/PIMS/LNGG', 'FUR', 'KingsPIMS', 'KC_Lang_FUR'),
    ('/KINGS/PIMS/LNGG', 'GAA', 'KingsPIMS', 'KC_Lang_GAA'),
    ('/KINGS/PIMS/LNGG', 'GAY', 'KingsPIMS', 'KC_Lang_GAY'),
    ('/KINGS/PIMS/LNGG', 'GBA', 'KingsPIMS', 'KC_Lang_GBA'),
    ('/KINGS/PIMS/LNGG', 'GEM', 'KingsPIMS', 'KC_Lang_GEM'),
    ('/KINGS/PIMS/LNGG', 'GEO', 'KingsPIMS', 'KC_Lang_GEO'),
    ('/KINGS/PIMS/LNGG', 'GER', 'KingsPIMS', 'KC_Lang_GER'),
    ('/KINGS/PIMS/LNGG', 'GEZ', 'KingsPIMS', 'KC_Lang_GEZ'),
    ('/KINGS/PIMS/LNGG', 'GIL', 'KingsPIMS', 'KC_Lang_GIL'),
    ('/KINGS/PIMS/LNGG', 'GLA', 'KingsPIMS', 'KC_Lang_GLA'),
    ('/KINGS/PIMS/LNGG', 'GLE', 'KingsPIMS', 'KC_Lang_GLE'),
    ('/KINGS/PIMS/LNGG', 'GLG', 'KingsPIMS', 'KC_Lang_GLG'),
    ('/KINGS/PIMS/LNGG', 'GLV', 'KingsPIMS', 'KC_Lang_GLV'),
    ('/KINGS/PIMS/LNGG', 'GMH', 'KingsPIMS', 'KC_Lang_GMH'),
    ('/KINGS/PIMS/LNGG', 'GOH', 'KingsPIMS', 'KC_Lang_GOH'),
    ('/KINGS/PIMS/LNGG', 'GON', 'KingsPIMS', 'KC_Lang_GON'),
    ('/KINGS/PIMS/LNGG', 'GOR', 'KingsPIMS', 'KC_Lang_GOR'),
    ('/KINGS/PIMS/LNGG', 'GOT', 'KingsPIMS', 'KC_Lang_GOT'),
    ('/KINGS/PIMS/LNGG', 'GRB', 'KingsPIMS', 'KC_Lang_GRB'),
    ('/KINGS/PIMS/LNGG', 'GRC', 'KingsPIMS', 'KC_Lang_GRC'),
    ('/KINGS/PIMS/LNGG', 'GRE', 'KingsPIMS', 'KC_Lang_GRE'),
    ('/KINGS/PIMS/LNGG', 'GRN', 'KingsPIMS', 'KC_Lang_GRN'),
    ('/KINGS/PIMS/LNGG', 'GSW', 'KingsPIMS', 'KC_Lang_GSW'),
    ('/KINGS/PIMS/LNGG', 'GUJ', 'KingsPIMS', 'KC_Lang_GUJ'),
    ('/KINGS/PIMS/LNGG', 'GWI', 'KingsPIMS', 'KC_Lang_GWI'),
    ('/KINGS/PIMS/LNGG', 'HAI', 'KingsPIMS', 'KC_Lang_HAI'),
    ('/KINGS/PIMS/LNGG', 'HAT', 'KingsPIMS', 'KC_Lang_HAT'),
    ('/KINGS/PIMS/LNGG', 'HAU', 'KingsPIMS', 'KC_Lang_HAU'),
    ('/KINGS/PIMS/LNGG', 'HAW', 'KingsPIMS', 'KC_Lang_HAW'),
    ('/KINGS/PIMS/LNGG', 'HEB', 'KingsPIMS', 'KC_Lang_HEB'),
    ('/KINGS/PIMS/LNGG', 'HER', 'KingsPIMS', 'KC_Lang_HER'),
    ('/KINGS/PIMS/LNGG', 'HIL', 'KingsPIMS', 'KC_Lang_HIL'),
    ('/KINGS/PIMS/LNGG', 'HIM', 'KingsPIMS', 'KC_Lang_HIM'),
    ('/KINGS/PIMS/LNGG', 'HIN', 'KingsPIMS', 'KC_Lang_HIN'),
    ('/KINGS/PIMS/LNGG', 'HIT', 'KingsPIMS', 'KC_Lang_HIT'),
    ('/KINGS/PIMS/LNGG', 'HMN', 'KingsPIMS', 'KC_Lang_HMN'),
    ('/KINGS/PIMS/LNGG', 'HMO', 'KingsPIMS', 'KC_Lang_HMO'),
    ('/KINGS/PIMS/LNGG', 'HRV', 'KingsPIMS', 'KC_Lang_HRV'),
    ('/KINGS/PIMS/LNGG', 'HSB', 'KingsPIMS', 'KC_Lang_HSB'),
    ('/KINGS/PIMS/LNGG', 'HUN', 'KingsPIMS', 'KC_Lang_HUN'),
    ('/KINGS/PIMS/LNGG', 'HUP', 'KingsPIMS', 'KC_Lang_HUP'),
    ('/KINGS/PIMS/LNGG', 'HYE', 'KingsPIMS', 'KC_Lang_HYE'),
    ('/KINGS/PIMS/LNGG', 'IBA', 'KingsPIMS', 'KC_Lang_IBA'),
    ('/KINGS/PIMS/LNGG', 'IBO', 'KingsPIMS', 'KC_Lang_IBO'),
    ('/KINGS/PIMS/LNGG', 'ICE', 'KingsPIMS', 'KC_Lang_ICE'),
    ('/KINGS/PIMS/LNGG', 'IDO', 'KingsPIMS', 'KC_Lang_IDO'),
    ('/KINGS/PIMS/LNGG', 'III', 'KingsPIMS', 'KC_Lang_III'),
    ('/KINGS/PIMS/LNGG', 'IJO', 'KingsPIMS', 'KC_Lang_IJO'),
    ('/KINGS/PIMS/LNGG', 'IKU', 'KingsPIMS', 'KC_Lang_IKU'),
    ('/KINGS/PIMS/LNGG', 'ILE', 'KingsPIMS', 'KC_Lang_ILE'),
    ('/KINGS/PIMS/LNGG', 'ILO', 'KingsPIMS', 'KC_Lang_ILO'),
    ('/KINGS/PIMS/LNGG', 'INA', 'KingsPIMS', 'KC_Lang_INA'),
    ('/KINGS/PIMS/LNGG', 'INC', 'KingsPIMS', 'KC_Lang_INC'),
    ('/KINGS/PIMS/LNGG', 'IND', 'KingsPIMS', 'KC_Lang_IND'),
    ('/KINGS/PIMS/LNGG', 'INE', 'KingsPIMS', 'KC_Lang_INE'),
    ('/KINGS/PIMS/LNGG', 'INH', 'KingsPIMS', 'KC_Lang_INH'),
    ('/KINGS/PIMS/LNGG', 'IPK', 'KingsPIMS', 'KC_Lang_IPK'),
    ('/KINGS/PIMS/LNGG', 'IRA', 'KingsPIMS', 'KC_Lang_IRA'),
    ('/KINGS/PIMS/LNGG', 'IRO', 'KingsPIMS', 'KC_Lang_IRO'),
    ('/KINGS/PIMS/LNGG', 'ISL', 'KingsPIMS', 'KC_Lang_ISL'),
    ('/KINGS/PIMS/LNGG', 'ITA', 'KingsPIMS', 'KC_Lang_ITA'),
    ('/KINGS/PIMS/LNGG', 'JAV', 'KingsPIMS', 'KC_Lang_JAV'),
    ('/KINGS/PIMS/LNGG', 'JBO', 'KingsPIMS', 'KC_Lang_JBO'),
    ('/KINGS/PIMS/LNGG', 'JPN', 'KingsPIMS', 'KC_Lang_JPN'),
    ('/KINGS/PIMS/LNGG', 'JPR', 'KingsPIMS', 'KC_Lang_JPR'),
    ('/KINGS/PIMS/LNGG', 'JRB', 'KingsPIMS', 'KC_Lang_JRB'),
    ('/KINGS/PIMS/LNGG', 'KAA', 'KingsPIMS', 'KC_Lang_KAA'),
    ('/KINGS/PIMS/LNGG', 'KAB', 'KingsPIMS', 'KC_Lang_KAB'),
    ('/KINGS/PIMS/LNGG', 'KAC', 'KingsPIMS', 'KC_Lang_KAC'),
    ('/KINGS/PIMS/LNGG', 'KAL', 'KingsPIMS', 'KC_Lang_KAL'),
    ('/KINGS/PIMS/LNGG', 'KAM', 'KingsPIMS', 'KC_Lang_KAM'),
    ('/KINGS/PIMS/LNGG', 'KAN', 'KingsPIMS', 'KC_Lang_KAN'),
    ('/KINGS/PIMS/LNGG', 'KAR', 'KingsPIMS', 'KC_Lang_KAR'),
    ('/KINGS/PIMS/LNGG', 'KAS', 'KingsPIMS', 'KC_Lang_KAS'),
    ('/KINGS/PIMS/LNGG', 'KAT', 'KingsPIMS', 'KC_Lang_KAT'),
    ('/KINGS/PIMS/LNGG', 'KAU', 'KingsPIMS', 'KC_Lang_KAU'),
    ('/KINGS/PIMS/LNGG', 'KAW', 'KingsPIMS', 'KC_Lang_KAW'),
    ('/KINGS/PIMS/LNGG', 'KAZ', 'KingsPIMS', 'KC_Lang_KAZ'),
    ('/KINGS/PIMS/LNGG', 'KBD', 'KingsPIMS', 'KC_Lang_KBD'),
    ('/KINGS/PIMS/LNGG', 'KHA', 'KingsPIMS', 'KC_Lang_KHA'),
    ('/KINGS/PIMS/LNGG', 'KHI', 'KingsPIMS', 'KC_Lang_KHI'),
    ('/KINGS/PIMS/LNGG', 'KHM', 'KingsPIMS', 'KC_Lang_KHM'),
    ('/KINGS/PIMS/LNGG', 'KHO', 'KingsPIMS', 'KC_Lang_KHO'),
    ('/KINGS/PIMS/LNGG', 'KIK', 'KingsPIMS', 'KC_Lang_KIK'),
    ('/KINGS/PIMS/LNGG', 'KIN', 'KingsPIMS', 'KC_Lang_KIN'),
    ('/KINGS/PIMS/LNGG', 'KIR', 'KingsPIMS', 'KC_Lang_KIR'),
    ('/KINGS/PIMS/LNGG', 'KMB', 'KingsPIMS', 'KC_Lang_KMB'),
    ('/KINGS/PIMS/LNGG', 'KOK', 'KingsPIMS', 'KC_Lang_KOK'),
    ('/KINGS/PIMS/LNGG', 'KOM', 'KingsPIMS', 'KC_Lang_KOM'),
    ('/KINGS/PIMS/LNGG', 'KON', 'KingsPIMS', 'KC_Lang_KON'),
    ('/KINGS/PIMS/LNGG', 'KOR', 'KingsPIMS', 'KC_Lang_KOR'),
    ('/KINGS/PIMS/LNGG', 'KOS', 'KingsPIMS', 'KC_Lang_KOS'),
    ('/KINGS/PIMS/LNGG', 'KPE', 'KingsPIMS', 'KC_Lang_KPE'),
    ('/KINGS/PIMS/LNGG', 'KRC', 'KingsPIMS', 'KC_Lang_KRC'),
    ('/KINGS/PIMS/LNGG', 'KRL', 'KingsPIMS', 'KC_Lang_KRL'),
    ('/KINGS/PIMS/LNGG', 'KRO', 'KingsPIMS', 'KC_Lang_KRO'),
    ('/KINGS/PIMS/LNGG', 'KRU', 'KingsPIMS', 'KC_Lang_KRU'),
    ('/KINGS/PIMS/LNGG', 'KUA', 'KingsPIMS', 'KC_Lang_KUA'),
    ('/KINGS/PIMS/LNGG', 'KUM', 'KingsPIMS', 'KC_Lang_KUM'),
    ('/KINGS/PIMS/LNGG', 'KUR', 'KingsPIMS', 'KC_Lang_KUR'),
    ('/KINGS/PIMS/LNGG', 'KUT', 'KingsPIMS', 'KC_Lang_KUT'),
    ('/KINGS/PIMS/LNGG', 'LAD', 'KingsPIMS', 'KC_Lang_LAD'),
    ('/KINGS/PIMS/LNGG', 'LAH', 'KingsPIMS', 'KC_Lang_LAH'),
    ('/KINGS/PIMS/LNGG', 'LAM', 'KingsPIMS', 'KC_Lang_LAM'),
    ('/KINGS/PIMS/LNGG', 'LAO', 'KingsPIMS', 'KC_Lang_LAO'),
    ('/KINGS/PIMS/LNGG', 'LAT', 'KingsPIMS', 'KC_Lang_LAT'),
    ('/KINGS/PIMS/LNGG', 'LAV', 'KingsPIMS', 'KC_Lang_LAV'),
    ('/KINGS/PIMS/LNGG', 'LEZ', 'KingsPIMS', 'KC_Lang_LEZ'),
    ('/KINGS/PIMS/LNGG', 'LIM', 'KingsPIMS', 'KC_Lang_LIM'),
    ('/KINGS/PIMS/LNGG', 'LIN', 'KingsPIMS', 'KC_Lang_LIN'),
    ('/KINGS/PIMS/LNGG', 'LIT', 'KingsPIMS', 'KC_Lang_LIT'),
    ('/KINGS/PIMS/LNGG', 'LOL', 'KingsPIMS', 'KC_Lang_LOL'),
    ('/KINGS/PIMS/LNGG', 'LOZ', 'KingsPIMS', 'KC_Lang_LOZ'),
    ('/KINGS/PIMS/LNGG', 'LTZ', 'KingsPIMS', 'KC_Lang_LTZ'),
    ('/KINGS/PIMS/LNGG', 'LUA', 'KingsPIMS', 'KC_Lang_LUA'),
    ('/KINGS/PIMS/LNGG', 'LUB', 'KingsPIMS', 'KC_Lang_LUB'),
    ('/KINGS/PIMS/LNGG', 'LUG', 'KingsPIMS', 'KC_Lang_LUG'),
    ('/KINGS/PIMS/LNGG', 'LUI', 'KingsPIMS', 'KC_Lang_LUI'),
    ('/KINGS/PIMS/LNGG', 'LUN', 'KingsPIMS', 'KC_Lang_LUN'),
    ('/KINGS/PIMS/LNGG', 'LUO', 'KingsPIMS', 'KC_Lang_LUO'),
    ('/KINGS/PIMS/LNGG', 'LUS', 'KingsPIMS', 'KC_Lang_LUS'),
    ('/KINGS/PIMS/LNGG', 'MAC', 'KingsPIMS', 'KC_Lang_MAC'),
    ('/KINGS/PIMS/LNGG', 'MAD', 'KingsPIMS', 'KC_Lang_MAD'),
    ('/KINGS/PIMS/LNGG', 'MAG', 'KingsPIMS', 'KC_Lang_MAG'),
    ('/KINGS/PIMS/LNGG', 'MAH', 'KingsPIMS', 'KC_Lang_MAH'),
    ('/KINGS/PIMS/LNGG', 'MAI', 'KingsPIMS', 'KC_Lang_MAI'),
    ('/KINGS/PIMS/LNGG', 'MAK', 'KingsPIMS', 'KC_Lang_MAK'),
    ('/KINGS/PIMS/LNGG', 'MAL', 'KingsPIMS', 'KC_Lang_MAL'),
    ('/KINGS/PIMS/LNGG', 'MAN', 'KingsPIMS', 'KC_Lang_MAN'),
    ('/KINGS/PIMS/LNGG', 'MAO', 'KingsPIMS', 'KC_Lang_MAO'),
    ('/KINGS/PIMS/LNGG', 'MAP', 'KingsPIMS', 'KC_Lang_MAP'),
    ('/KINGS/PIMS/LNGG', 'MAR', 'KingsPIMS', 'KC_Lang_MAR'),
    ('/KINGS/PIMS/LNGG', 'MAS', 'KingsPIMS', 'KC_Lang_MAS'),
    ('/KINGS/PIMS/LNGG', 'MAY', 'KingsPIMS', 'KC_Lang_MAY'),
    ('/KINGS/PIMS/LNGG', 'MDF', 'KingsPIMS', 'KC_Lang_MDF'),
    ('/KINGS/PIMS/LNGG', 'MDR', 'KingsPIMS', 'KC_Lang_MDR'),
    ('/KINGS/PIMS/LNGG', 'MEN', 'KingsPIMS', 'KC_Lang_MEN'),
    ('/KINGS/PIMS/LNGG', 'MGA', 'KingsPIMS', 'KC_Lang_MGA'),
    ('/KINGS/PIMS/LNGG', 'MIC', 'KingsPIMS', 'KC_Lang_MIC'),
    ('/KINGS/PIMS/LNGG', 'MIN', 'KingsPIMS', 'KC_Lang_MIN'),
    ('/KINGS/PIMS/LNGG', 'MIS', 'KingsPIMS', 'KC_Lang_MIS'),
    ('/KINGS/PIMS/LNGG', 'MKD', 'KingsPIMS', 'KC_Lang_MKD'),
    ('/KINGS/PIMS/LNGG', 'MKH', 'KingsPIMS', 'KC_Lang_MKH'),
    ('/KINGS/PIMS/LNGG', 'MLG', 'KingsPIMS', 'KC_Lang_MLG'),
    ('/KINGS/PIMS/LNGG', 'MLT', 'KingsPIMS', 'KC_Lang_MLT'),
    ('/KINGS/PIMS/LNGG', 'MNC', 'KingsPIMS', 'KC_Lang_MNC'),
    ('/KINGS/PIMS/LNGG', 'MNI', 'KingsPIMS', 'KC_Lang_MNI'),
    ('/KINGS/PIMS/LNGG', 'MNO', 'KingsPIMS', 'KC_Lang_MNO'),
    ('/KINGS/PIMS/LNGG', 'MOH', 'KingsPIMS', 'KC_Lang_MOH'),
    ('/KINGS/PIMS/LNGG', 'MON', 'KingsPIMS', 'KC_Lang_MON'),
    ('/KINGS/PIMS/LNGG', 'MOS', 'KingsPIMS', 'KC_Lang_MOS'),
    ('/KINGS/PIMS/LNGG', 'MRI', 'KingsPIMS', 'KC_Lang_MRI'),
    ('/KINGS/PIMS/LNGG', 'MSA', 'KingsPIMS', 'KC_Lang_MSA'),
    ('/KINGS/PIMS/LNGG', 'MUL', 'KingsPIMS', 'KC_Lang_MUL'),
    ('/KINGS/PIMS/LNGG', 'MUN', 'KingsPIMS', 'KC_Lang_MUN'),
    ('/KINGS/PIMS/LNGG', 'MUS', 'KingsPIMS', 'KC_Lang_MUS'),
    ('/KINGS/PIMS/LNGG', 'MWL', 'KingsPIMS', 'KC_Lang_MWL'),
    ('/KINGS/PIMS/LNGG', 'MWR', 'KingsPIMS', 'KC_Lang_MWR'),
    ('/KINGS/PIMS/LNGG', 'MYA', 'KingsPIMS', 'KC_Lang_MYA'),
    ('/KINGS/PIMS/LNGG', 'MYN', 'KingsPIMS', 'KC_Lang_MYN'),
    ('/KINGS/PIMS/LNGG', 'MYV', 'KingsPIMS', 'KC_Lang_MYV'),
    ('/KINGS/PIMS/LNGG', 'NAH', 'KingsPIMS', 'KC_Lang_NAH'),
    ('/KINGS/PIMS/LNGG', 'NAI', 'KingsPIMS', 'KC_Lang_NAI'),
    ('/KINGS/PIMS/LNGG', 'NAP', 'KingsPIMS', 'KC_Lang_NAP'),
    ('/KINGS/PIMS/LNGG', 'NAU', 'KingsPIMS', 'KC_Lang_NAU'),
    ('/KINGS/PIMS/LNGG', 'NAV', 'KingsPIMS', 'KC_Lang_NAV'),
    ('/KINGS/PIMS/LNGG', 'NBL', 'KingsPIMS', 'KC_Lang_NBL'),
    ('/KINGS/PIMS/LNGG', 'NDE', 'KingsPIMS', 'KC_Lang_NDE'),
    ('/KINGS/PIMS/LNGG', 'NDO', 'KingsPIMS', 'KC_Lang_NDO'),
    ('/KINGS/PIMS/LNGG', 'NDS', 'KingsPIMS', 'KC_Lang_NDS'),
    ('/KINGS/PIMS/LNGG', 'NEP', 'KingsPIMS', 'KC_Lang_NEP'),
    ('/KINGS/PIMS/LNGG', 'NEW', 'KingsPIMS', 'KC_Lang_NEW'),
    ('/KINGS/PIMS/LNGG', 'NIA', 'KingsPIMS', 'KC_Lang_NIA'),
    ('/KINGS/PIMS/LNGG', 'NIC', 'KingsPIMS', 'KC_Lang_NIC'),
    ('/KINGS/PIMS/LNGG', 'NIU', 'KingsPIMS', 'KC_Lang_NIU'),
    ('/KINGS/PIMS/LNGG', 'NLD', 'KingsPIMS', 'KC_Lang_NLD'),
    ('/KINGS/PIMS/LNGG', 'NNO', 'KingsPIMS', 'KC_Lang_NNO'),
    ('/KINGS/PIMS/LNGG', 'NOB', 'KingsPIMS', 'KC_Lang_NOB'),
    ('/KINGS/PIMS/LNGG', 'NOG', 'KingsPIMS', 'KC_Lang_NOG'),
    ('/KINGS/PIMS/LNGG', 'NON', 'KingsPIMS', 'KC_Lang_NON'),
    ('/KINGS/PIMS/LNGG', 'NOR', 'KingsPIMS', 'KC_Lang_NOR'),
    ('/KINGS/PIMS/LNGG', 'NQO', 'KingsPIMS', 'KC_Lang_NQO'),
    ('/KINGS/PIMS/LNGG', 'NSO', 'KingsPIMS', 'KC_Lang_NSO'),
    ('/KINGS/PIMS/LNGG', 'NUB', 'KingsPIMS', 'KC_Lang_NUB'),
    ('/KINGS/PIMS/LNGG', 'NWC', 'KingsPIMS', 'KC_Lang_NWC'),
    ('/KINGS/PIMS/LNGG', 'NYA', 'KingsPIMS', 'KC_Lang_NYA'),
    ('/KINGS/PIMS/LNGG', 'NYM', 'KingsPIMS', 'KC_Lang_NYM'),
    ('/KINGS/PIMS/LNGG', 'NYN', 'KingsPIMS', 'KC_Lang_NYN'),
    ('/KINGS/PIMS/LNGG', 'NYO', 'KingsPIMS', 'KC_Lang_NYO'),
    ('/KINGS/PIMS/LNGG', 'NZI', 'KingsPIMS', 'KC_Lang_NZI'),
    ('/KINGS/PIMS/LNGG', 'OCI', 'KingsPIMS', 'KC_Lang_OCI'),
    ('/KINGS/PIMS/LNGG', 'OJI', 'KingsPIMS', 'KC_Lang_OJI'),
    ('/KINGS/PIMS/LNGG', 'ORI', 'KingsPIMS', 'KC_Lang_ORI'),
    ('/KINGS/PIMS/LNGG', 'ORM', 'KingsPIMS', 'KC_Lang_ORM'),
    ('/KINGS/PIMS/LNGG', 'OSA', 'KingsPIMS', 'KC_Lang_OSA'),
    ('/KINGS/PIMS/LNGG', 'OSS', 'KingsPIMS', 'KC_Lang_OSS'),
    ('/KINGS/PIMS/LNGG', 'OTA', 'KingsPIMS', 'KC_Lang_OTA'),
    ('/KINGS/PIMS/LNGG', 'OTO', 'KingsPIMS', 'KC_Lang_OTO'),
    ('/KINGS/PIMS/LNGG', 'PAA', 'KingsPIMS', 'KC_Lang_PAA'),
    ('/KINGS/PIMS/LNGG', 'PAG', 'KingsPIMS', 'KC_Lang_PAG'),
    ('/KINGS/PIMS/LNGG', 'PAL', 'KingsPIMS', 'KC_Lang_PAL'),
    ('/KINGS/PIMS/LNGG', 'PAM', 'KingsPIMS', 'KC_Lang_PAM'),
    ('/KINGS/PIMS/LNGG', 'PAN', 'KingsPIMS', 'KC_Lang_PAN'),
    ('/KINGS/PIMS/LNGG', 'PAP', 'KingsPIMS', 'KC_Lang_PAP'),
    ('/KINGS/PIMS/LNGG', 'PAU', 'KingsPIMS', 'KC_Lang_PAU'),
    ('/KINGS/PIMS/LNGG', 'PEO', 'KingsPIMS', 'KC_Lang_PEO'),
    ('/KINGS/PIMS/LNGG', 'PER', 'KingsPIMS', 'KC_Lang_PER'),
    ('/KINGS/PIMS/LNGG', 'PHI', 'KingsPIMS', 'KC_Lang_PHI'),
    ('/KINGS/PIMS/LNGG', 'PHN', 'KingsPIMS', 'KC_Lang_PHN'),
    ('/KINGS/PIMS/LNGG', 'PLI', 'KingsPIMS', 'KC_Lang_PLI'),
    ('/KINGS/PIMS/LNGG', 'POL', 'KingsPIMS', 'KC_Lang_POL'),
    ('/KINGS/PIMS/LNGG', 'PON', 'KingsPIMS', 'KC_Lang_PON'),
    ('/KINGS/PIMS/LNGG', 'POR', 'KingsPIMS', 'KC_Lang_POR'),
    ('/KINGS/PIMS/LNGG', 'PRA', 'KingsPIMS', 'KC_Lang_PRA'),
    ('/KINGS/PIMS/LNGG', 'PRO', 'KingsPIMS', 'KC_Lang_PRO'),
    ('/KINGS/PIMS/LNGG', 'PUS', 'KingsPIMS', 'KC_Lang_PUS'),
    ('/KINGS/PIMS/LNGG', 'QAA', 'KingsPIMS', 'KC_Lang_QAA'),
    ('/KINGS/PIMS/LNGG', 'QUE', 'KingsPIMS', 'KC_Lang_QUE'),
    ('/KINGS/PIMS/LNGG', 'RAJ', 'KingsPIMS', 'KC_Lang_RAJ'),
    ('/KINGS/PIMS/LNGG', 'RAP', 'KingsPIMS', 'KC_Lang_RAP'),
    ('/KINGS/PIMS/LNGG', 'RAR', 'KingsPIMS', 'KC_Lang_RAR'),
    ('/KINGS/PIMS/LNGG', 'ROA', 'KingsPIMS', 'KC_Lang_ROA'),
    ('/KINGS/PIMS/LNGG', 'ROH', 'KingsPIMS', 'KC_Lang_ROH'),
    ('/KINGS/PIMS/LNGG', 'ROM', 'KingsPIMS', 'KC_Lang_ROM'),
    ('/KINGS/PIMS/LNGG', 'RON', 'KingsPIMS', 'KC_Lang_RON'),
    ('/KINGS/PIMS/LNGG', 'RUM', 'KingsPIMS', 'KC_Lang_RUM'),
    ('/KINGS/PIMS/LNGG', 'RUN', 'KingsPIMS', 'KC_Lang_RUN'),
    ('/KINGS/PIMS/LNGG', 'RUP', 'KingsPIMS', 'KC_Lang_RUP'),
    ('/KINGS/PIMS/LNGG', 'RUS', 'KingsPIMS', 'KC_Lang_RUS'),
    ('/KINGS/PIMS/LNGG', 'SAD', 'KingsPIMS', 'KC_Lang_SAD'),
    ('/KINGS/PIMS/LNGG', 'SAG', 'KingsPIMS', 'KC_Lang_SAG'),
    ('/KINGS/PIMS/LNGG', 'SAH', 'KingsPIMS', 'KC_Lang_SAH'),
    ('/KINGS/PIMS/LNGG', 'SAI', 'KingsPIMS', 'KC_Lang_SAI'),
    ('/KINGS/PIMS/LNGG', 'SAL', 'KingsPIMS', 'KC_Lang_SAL'),
    ('/KINGS/PIMS/LNGG', 'SAM', 'KingsPIMS', 'KC_Lang_SAM'),
    ('/KINGS/PIMS/LNGG', 'SAN', 'KingsPIMS', 'KC_Lang_SAN'),
    ('/KINGS/PIMS/LNGG', 'SAS', 'KingsPIMS', 'KC_Lang_SAS'),
    ('/KINGS/PIMS/LNGG', 'SAT', 'KingsPIMS', 'KC_Lang_SAT'),
    ('/KINGS/PIMS/LNGG', 'SCN', 'KingsPIMS', 'KC_Lang_SCN'),
    ('/KINGS/PIMS/LNGG', 'SCO', 'KingsPIMS', 'KC_Lang_SCO'),
    ('/KINGS/PIMS/LNGG', 'SEL', 'KingsPIMS', 'KC_Lang_SEL'),
    ('/KINGS/PIMS/LNGG', 'SEM', 'KingsPIMS', 'KC_Lang_SEM'),
    ('/KINGS/PIMS/LNGG', 'SGA', 'KingsPIMS', 'KC_Lang_SGA'),
    ('/KINGS/PIMS/LNGG', 'SGN', 'KingsPIMS', 'KC_Lang_SGN'),
    ('/KINGS/PIMS/LNGG', 'SHN', 'KingsPIMS', 'KC_Lang_SHN'),
    ('/KINGS/PIMS/LNGG', 'SID', 'KingsPIMS', 'KC_Lang_SID'),
    ('/KINGS/PIMS/LNGG', 'SIN', 'KingsPIMS', 'KC_Lang_SIN'),
    ('/KINGS/PIMS/LNGG', 'SIO', 'KingsPIMS', 'KC_Lang_SIO'),
    ('/KINGS/PIMS/LNGG', 'SIT', 'KingsPIMS', 'KC_Lang_SIT'),
    ('/KINGS/PIMS/LNGG', 'SLA', 'KingsPIMS', 'KC_Lang_SLA'),
    ('/KINGS/PIMS/LNGG', 'SLK', 'KingsPIMS', 'KC_Lang_SLK'),
    ('/KINGS/PIMS/LNGG', 'SLO', 'KingsPIMS', 'KC_Lang_SLO'),
    ('/KINGS/PIMS/LNGG', 'SLV', 'KingsPIMS', 'KC_Lang_SLV'),
    ('/KINGS/PIMS/LNGG', 'SMA', 'KingsPIMS', 'KC_Lang_SMA'),
    ('/KINGS/PIMS/LNGG', 'SME', 'KingsPIMS', 'KC_Lang_SME'),
    ('/KINGS/PIMS/LNGG', 'SMI', 'KingsPIMS', 'KC_Lang_SMI'),
    ('/KINGS/PIMS/LNGG', 'SMJ', 'KingsPIMS', 'KC_Lang_SMJ'),
    ('/KINGS/PIMS/LNGG', 'SMN', 'KingsPIMS', 'KC_Lang_SMN'),
    ('/KINGS/PIMS/LNGG', 'SMO', 'KingsPIMS', 'KC_Lang_SMO'),
    ('/KINGS/PIMS/LNGG', 'SMS', 'KingsPIMS', 'KC_Lang_SMS'),
    ('/KINGS/PIMS/LNGG', 'SNA', 'KingsPIMS', 'KC_Lang_SNA'),
    ('/KINGS/PIMS/LNGG', 'SND', 'KingsPIMS', 'KC_Lang_SND'),
    ('/KINGS/PIMS/LNGG', 'SNK', 'KingsPIMS', 'KC_Lang_SNK'),
    ('/KINGS/PIMS/LNGG', 'SOG', 'KingsPIMS', 'KC_Lang_SOG'),
    ('/KINGS/PIMS/LNGG', 'SOM', 'KingsPIMS', 'KC_Lang_SOM'),
    ('/KINGS/PIMS/LNGG', 'SON', 'KingsPIMS', 'KC_Lang_SON'),
    ('/KINGS/PIMS/LNGG', 'SOT', 'KingsPIMS', 'KC_Lang_SOT'),
    ('/KINGS/PIMS/LNGG', 'SPA', 'KingsPIMS', 'KC_Lang_SPA'),
    ('/KINGS/PIMS/LNGG', 'SQI', 'KingsPIMS', 'KC_Lang_SQI'),
    ('/KINGS/PIMS/LNGG', 'SRD', 'KingsPIMS', 'KC_Lang_SRD'),
    ('/KINGS/PIMS/LNGG', 'SRN', 'KingsPIMS', 'KC_Lang_SRN'),
    ('/KINGS/PIMS/LNGG', 'SRP', 'KingsPIMS', 'KC_Lang_SRP'),
    ('/KINGS/PIMS/LNGG', 'SRR', 'KingsPIMS', 'KC_Lang_SRR'),
    ('/KINGS/PIMS/LNGG', 'SSA', 'KingsPIMS', 'KC_Lang_SSA'),
    ('/KINGS/PIMS/LNGG', 'SSW', 'KingsPIMS', 'KC_Lang_SSW'),
    ('/KINGS/PIMS/LNGG', 'SUK', 'KingsPIMS', 'KC_Lang_SUK'),
    ('/KINGS/PIMS/LNGG', 'SUN', 'KingsPIMS', 'KC_Lang_SUN'),
    ('/KINGS/PIMS/LNGG', 'SUS', 'KingsPIMS', 'KC_Lang_SUS'),
    ('/KINGS/PIMS/LNGG', 'SUX', 'KingsPIMS', 'KC_Lang_SUX'),
    ('/KINGS/PIMS/LNGG', 'SWA', 'KingsPIMS', 'KC_Lang_SWA'),
    ('/KINGS/PIMS/LNGG', 'SWE', 'KingsPIMS', 'KC_Lang_SWE'),
    ('/KINGS/PIMS/LNGG', 'SYC', 'KingsPIMS', 'KC_Lang_SYC'),
    ('/KINGS/PIMS/LNGG', 'SYR', 'KingsPIMS', 'KC_Lang_SYR'),
    ('/KINGS/PIMS/LNGG', 'TAH', 'KingsPIMS', 'KC_Lang_TAH'),
    ('/KINGS/PIMS/LNGG', 'TAI', 'KingsPIMS', 'KC_Lang_TAI'),
    ('/KINGS/PIMS/LNGG', 'TAM', 'KingsPIMS', 'KC_Lang_TAM'),
    ('/KINGS/PIMS/LNGG', 'TAT', 'KingsPIMS', 'KC_Lang_TAT'),
    ('/KINGS/PIMS/LNGG', 'TEL', 'KingsPIMS', 'KC_Lang_TEL'),
    ('/KINGS/PIMS/LNGG', 'TEM', 'KingsPIMS', 'KC_Lang_TEM'),
    ('/KINGS/PIMS/LNGG', 'TER', 'KingsPIMS', 'KC_Lang_TER'),
    ('/KINGS/PIMS/LNGG', 'TET', 'KingsPIMS', 'KC_Lang_TET'),
    ('/KINGS/PIMS/LNGG', 'TGK', 'KingsPIMS', 'KC_Lang_TGK'),
    ('/KINGS/PIMS/LNGG', 'TGL', 'KingsPIMS', 'KC_Lang_TGL'),
    ('/KINGS/PIMS/LNGG', 'THA', 'KingsPIMS', 'KC_Lang_THA'),
    ('/KINGS/PIMS/LNGG', 'TIB', 'KingsPIMS', 'KC_Lang_TIB'),
    ('/KINGS/PIMS/LNGG', 'TIG', 'KingsPIMS', 'KC_Lang_TIG'),
    ('/KINGS/PIMS/LNGG', 'TIR', 'KingsPIMS', 'KC_Lang_TIR'),
    ('/KINGS/PIMS/LNGG', 'TIV', 'KingsPIMS', 'KC_Lang_TIV'),
    ('/KINGS/PIMS/LNGG', 'TKL', 'KingsPIMS', 'KC_Lang_TKL'),
    ('/KINGS/PIMS/LNGG', 'TLH', 'KingsPIMS', 'KC_Lang_TLH'),
    ('/KINGS/PIMS/LNGG', 'TLI', 'KingsPIMS', 'KC_Lang_TLI'),
    ('/KINGS/PIMS/LNGG', 'TMH', 'KingsPIMS', 'KC_Lang_TMH'),
    ('/KINGS/PIMS/LNGG', 'TOG', 'KingsPIMS', 'KC_Lang_TOG'),
    ('/KINGS/PIMS/LNGG', 'TON', 'KingsPIMS', 'KC_Lang_TON'),
    ('/KINGS/PIMS/LNGG', 'TPI', 'KingsPIMS', 'KC_Lang_TPI'),
    ('/KINGS/PIMS/LNGG', 'TSI', 'KingsPIMS', 'KC_Lang_TSI'),
    ('/KINGS/PIMS/LNGG', 'TSN', 'KingsPIMS', 'KC_Lang_TSN'),
    ('/KINGS/PIMS/LNGG', 'TSO', 'KingsPIMS', 'KC_Lang_TSO'),
    ('/KINGS/PIMS/LNGG', 'TUK', 'KingsPIMS', 'KC_Lang_TUK'),
    ('/KINGS/PIMS/LNGG', 'TUM', 'KingsPIMS', 'KC_Lang_TUM'),
    ('/KINGS/PIMS/LNGG', 'TUP', 'KingsPIMS', 'KC_Lang_TUP'),
    ('/KINGS/PIMS/LNGG', 'TUR', 'KingsPIMS', 'KC_Lang_TUR'),
    ('/KINGS/PIMS/LNGG', 'TUT', 'KingsPIMS', 'KC_Lang_TUT'),
    ('/KINGS/PIMS/LNGG', 'TVL', 'KingsPIMS', 'KC_Lang_TVL'),
    ('/KINGS/PIMS/LNGG', 'TWI', 'KingsPIMS', 'KC_Lang_TWI'),
    ('/KINGS/PIMS/LNGG', 'TYV', 'KingsPIMS', 'KC_Lang_TYV'),
    ('/KINGS/PIMS/LNGG', 'UDM', 'KingsPIMS', 'KC_Lang_UDM'),
    ('/KINGS/PIMS/LNGG', 'UGA', 'KingsPIMS', 'KC_Lang_UGA'),
    ('/KINGS/PIMS/LNGG', 'UIG', 'KingsPIMS', 'KC_Lang_UIG'),
    ('/KINGS/PIMS/LNGG', 'UKR', 'KingsPIMS', 'KC_Lang_UKR'),
    ('/KINGS/PIMS/LNGG', 'UMB', 'KingsPIMS', 'KC_Lang_UMB'),
    ('/KINGS/PIMS/LNGG', 'UND', 'KingsPIMS', 'KC_Lang_UND'),
    ('/KINGS/PIMS/LNGG', 'URD', 'KingsPIMS', 'KC_Lang_URD'),
    ('/KINGS/PIMS/LNGG', 'UZB', 'KingsPIMS', 'KC_Lang_UZB'),
    ('/KINGS/PIMS/LNGG', 'VAI', 'KingsPIMS', 'KC_Lang_VAI'),
    ('/KINGS/PIMS/LNGG', 'VEN', 'KingsPIMS', 'KC_Lang_VEN'),
    ('/KINGS/PIMS/LNGG', 'VIE', 'KingsPIMS', 'KC_Lang_VIE'),
    ('/KINGS/PIMS/LNGG', 'VOL', 'KingsPIMS', 'KC_Lang_VOL'),
    ('/KINGS/PIMS/LNGG', 'VOT', 'KingsPIMS', 'KC_Lang_VOT'),
    ('/KINGS/PIMS/LNGG', 'WAK', 'KingsPIMS', 'KC_Lang_WAK'),
    ('/KINGS/PIMS/LNGG', 'WAL', 'KingsPIMS', 'KC_Lang_WAL'),
    ('/KINGS/PIMS/LNGG', 'WAR', 'KingsPIMS', 'KC_Lang_WAR'),
    ('/KINGS/PIMS/LNGG', 'WAS', 'KingsPIMS', 'KC_Lang_WAS'),
    ('/KINGS/PIMS/LNGG', 'WEL', 'KingsPIMS', 'KC_Lang_WEL'),
    ('/KINGS/PIMS/LNGG', 'WEN', 'KingsPIMS', 'KC_Lang_WEN'),
    ('/KINGS/PIMS/LNGG', 'WLN', 'KingsPIMS', 'KC_Lang_WLN'),
    ('/KINGS/PIMS/LNGG', 'WOL', 'KingsPIMS', 'KC_Lang_WOL'),
    ('/KINGS/PIMS/LNGG', 'XAL', 'KingsPIMS', 'KC_Lang_XAL'),
    ('/KINGS/PIMS/LNGG', 'XHO', 'KingsPIMS', 'KC_Lang_XHO'),
    ('/KINGS/PIMS/LNGG', 'YAO', 'KingsPIMS', 'KC_Lang_YAO'),
    ('/KINGS/PIMS/LNGG', 'YAP', 'KingsPIMS', 'KC_Lang_YAP'),
    ('/KINGS/PIMS/LNGG', 'YID', 'KingsPIMS', 'KC_Lang_YID'),
    ('/KINGS/PIMS/LNGG', 'YOR', 'KingsPIMS', 'KC_Lang_YOR'),
    ('/KINGS/PIMS/LNGG', 'YPK', 'KingsPIMS', 'KC_Lang_YPK'),
    ('/KINGS/PIMS/LNGG', 'ZAP', 'KingsPIMS', 'KC_Lang_ZAP'),
    ('/KINGS/PIMS/LNGG', 'ZBL', 'KingsPIMS', 'KC_Lang_ZBL'),
    ('/KINGS/PIMS/LNGG', 'ZEN', 'KingsPIMS', 'KC_Lang_ZEN'),
    ('/KINGS/PIMS/LNGG', 'ZGH', 'KingsPIMS', 'KC_Lang_ZGH'),
    ('/KINGS/PIMS/LNGG', 'ZHA', 'KingsPIMS', 'KC_Lang_ZHA'),
    ('/KINGS/PIMS/LNGG', 'ZHO', 'KingsPIMS', 'KC_Lang_ZHO'),
    ('/KINGS/PIMS/LNGG', 'ZND', 'KingsPIMS', 'KC_Lang_ZND'),
    ('/KINGS/PIMS/LNGG', 'ZUL', 'KingsPIMS', 'KC_Lang_ZUL'),
    ('/KINGS/PIMS/LNGG', 'ZUN', 'KingsPIMS', 'KC_Lang_ZUN'),
    ('/KINGS/PIMS/LNGG', 'ZXX', 'KingsPIMS', 'KC_Lang_ZXX'),
    ('/KINGS/PIMS/LNGG', 'ZZA', 'KingsPIMS', 'KC_Lang_ZZA'),
    ('/KINGS/PIMS/LNGG', 'ADNOM', 'KingsPIMS', 'KC_Lang_ADNOM'),
    ('/KINGS/PIMS/LNGG', 'ADNSP', 'KingsPIMS', 'KC_Lang_ADNSP');
